'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode =
  | 'en' | 'ar' | 'fr' | 'es' | 'fa'
  | 'de' | 'tr' | 'it' | 'pt' | 'ru'
  | 'zh' | 'ja' | 'hi' | 'ur' | 'he'
  | 'el' | 'nl' | 'id' | 'sv' | 'pl';

export interface LanguageMeta {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'ltr' | 'rtl';
  isPinned?: boolean;
}

export const RTL_LANGUAGES: LanguageCode[] = ['ar', 'fa', 'ur', 'he'];

export function isRTL(lang: LanguageCode): boolean {
  return RTL_LANGUAGES.includes(lang);
}

export const PINNED_LANGUAGES: LanguageMeta[] = [
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇱🇧', dir: 'rtl', isPinned: true },
  { code: 'en', name: 'English', nativeName: 'English (US)', flag: '🇺🇸', dir: 'ltr', isPinned: true },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', dir: 'ltr', isPinned: true },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr', isPinned: true },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷', dir: 'rtl', isPinned: true },
];

export const EXTENDED_LANGUAGES: LanguageMeta[] = [
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷', dir: 'ltr' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'zh', name: 'Chinese', nativeName: '中文 (简体)', flag: '🇨🇳', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰', dir: 'rtl' },
  { code: 'he', name: 'Hebrew', nativeName: 'עבריت', flag: '🇮🇱', dir: 'rtl' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷', dir: 'ltr' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱', dir: 'ltr' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', dir: 'ltr' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪', dir: 'ltr' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱', dir: 'ltr' },
];

export const ALL_LANGUAGES: LanguageMeta[] = [...PINNED_LANGUAGES, ...EXTENDED_LANGUAGES];

export interface LanguageContextType {
  language: LanguageCode;
  dir: 'ltr' | 'rtl';
  direction?: 'ltr' | 'rtl';
  isRtl: boolean;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallbackEn?: string) => string;
  languages: LanguageMeta[];
  pinnedLanguages: LanguageMeta[];
  extendedLanguages: LanguageMeta[];
}

const translations: Partial<Record<LanguageCode, Record<string, string>>> = {
  en: {
    // Top Modules
    'workspace': 'Workspace',
    'sales_control': '1. Sales Control',
    'operations_center': '2. Operations Center',
    'purchases': '3. Purchasing & Procurement',
    'crm_debtors': '4. Customer Management (CRM)',
    'complaints_dashboard': '5. Feedback & Surveys',
    'loyalty_program': '6. Loyalty Management',
    'accounting_finance': '7. Accounting & Financials',
    'hr_payroll': '8. Human Resources & Payroll',
    'supersonic_fleet': '9. Supersonic Fleet / V-Driver',
    'social_crm': '10. V-Connect (Social CRM)',
    'pressing_mill_nav': '11. Pressing Mill Engine',
    'olive_pressing': 'Olive Pressing & Production',
    'pressing_mill': 'Pressing Mill',
    'oil_pressing_short': 'Oil Pressing',

    // Shared / Core
    'dashboard': 'Dashboard',
    'reports': 'Reports',
    'reports_hub': 'Reports Hub',
    'online_orders': 'Online Orders',
    'end_of_day': 'End of Day',
    'setup': 'Setup',
    'more_setup': 'More Setup',
    'actions': 'Actions',
    'settings': 'Settings',
    'more': 'More',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'saving': 'Saving Changes...',
    'search_menu': 'search menu...',
    'search_placeholder': 'Quick search in screens & transactions...',
    'alerts': 'Alerts',
    'exchange_rate': 'Exchange Rate',
    'system_active': 'System Active & Online',
    'vanguard_system': 'Vanguard ERP System',
    'all_rights_reserved': '© 2026 All Rights Reserved',
    'privacy_policy': 'Privacy Policy',

    // Sales Control Sub-Items
    'pos_terminal': 'POS Cashier Terminal',
    'pos_layout_config': 'POS Screen Config',
    'screens': 'Screens',
    'payment_types': 'Payment Types',
    'coupons_vouchers': 'Coupons & Vouchers',
    'coupons_gift_cert': 'Coupons & Gift Certificates',
    'discounts': 'Discounts',
    'price_modes': 'Price Modes',
    'workstations_printers': 'Workstations & Printers',
    'void_reasons': 'Void Reasons',
    'vat_exemptions': 'Vat Exemption Reason',
    'vat_exemption_reasons': 'VAT Exemption Reasons',
    'invoice_message': 'Invoice Message',
    'invoice_messages': 'Message On Invoice',
    'zone_setup': 'Zone Setup',
    'currency_setup': 'Currency Setup',

    // Operations Center Sub-Items
    'sales': 'Sales',
    'quotations': 'Quotations',
    'delivery_goods': 'Delivery of Goods',
    'purchase_orders': 'Purchase Orders',
    'reorder_guide': 'Reorder Guide',
    'transfers': 'Transfers',
    'stock_transfer': 'Stock Transfer',
    'lost_goods': 'Lost Goods',
    'lost_damaged_goods': 'Lost & Damaged Goods',
    'item_assembly': 'Item Assembly',
    'bom_assembly': 'BOM Assembly',
    'adjustments': 'Adjustments',
    'inventory_adjustments': 'Inventory Adjustments',
    'product_request': 'Product Request',
    'product_requests': 'Product Requests',
    'manage_product_requests': 'Manage Product Requests',
    'product_req_prep': 'Product Req. Preparation',
    'receiving_goods': 'Receiving of goods',
    'product_req_reports': 'Product Request Reports',
    'request_reject_reasons': 'Request Reject Reasons',
    'events': 'Events',
    'events_management': 'Events & Occasions',
    'event_venues': 'Event Venues',
    'event_resources': 'Event Resources',
    'event_types': 'Event Types',
    'quick_setup': 'Quick Setup',
    'products_services': 'Products & Services',
    'product_groups': 'Product Groups',
    'groups': 'Groups',
    'divisions': 'Divisions',
    'categories': 'Categories',
    'units': 'Units',
    'uom_tanks': 'Units of Measure & Tanks',
    'locations': 'Locations',
    'warehouses_locations': 'Warehouses & Locations',
    'suppliers': 'Suppliers',
    'departments': 'Departments',
    'lost_goods_reason': 'Lost Goods Reason',
    'sizes_groups': 'Sizes Groups',
    'sizes': 'Sizes',
    'colors': 'Colors',
    'inventory_brands': 'Inventory Brands',
    'delivery_providers': 'Delivery Providers',

    // Purchasing Sub-Items
    'purchases_ap_bills': 'Purchases & AP Bills',
    'goods_receiving_grn': 'Goods Receiving (GRN)',
    'suppliers_directory': 'Suppliers Directory',
    'procurement_reports': 'Procurement Reports',

    // Customer CRM Sub-Items
    'customer_directory': 'Customer Accounts Directory',
    'customers_directory': 'Customers Directory',
    'customer_receipts': 'Customer Receipts',
    'receipts_vouchers': 'Receipt Vouchers',
    'aged_debtors': 'Aged Debtors Analysis',
    'customer_aged_receivables': 'Customer Aged Receivables',
    'customer_insights': 'Customer Insights',
    'ltv_insights': 'Customer LTV Insights',
    'tasks_appointments': 'Tasks and Appointments',
    'leads_opportunities': 'Leads & Opportunities',
    'sales_team_performance': 'Sales Team Performance',
    'sales_rep_performance': 'Sales Rep Performance',
    'customers_groups': 'Customers Groups',
    'customers_categories': 'Customers Categories',
    'customers_tags': 'Customers Tags',

    // Feedback Sub-Items
    'manage_complaints': 'Manage Complaints',
    'add_complaints': 'Add Complaints',
    'manage_surveys': 'Manage Surveys',
    'send_survey_emails': 'Send Survey Emails',
    'complaint_sources': 'Complaint Sources',
    'complaint_categories': 'Complaint Categories',
    'complaint_action_types': 'Complaint Action Types',
    'customer_care': 'Customer Care',
    'surveys_setup': 'Surveys Setup',

    // Loyalty Sub-Items
    'members': 'Members',
    'loyalty_levels': 'Loyalty Levels',
    'loyalty_programs': 'Loyalty Programs',
    'send_messages': 'Send Messages',
    'company_info': 'Company Info',

    // Accounting Sub-Items
    'chart_of_accounts': 'Chart of Accounts (COA)',
    'journal_voucher': 'Journal Voucher',
    'journal_vouchers': 'Journal Vouchers (JV)',
    'purchase': 'Purchase',
    'payments': 'Payments',
    'receipts': 'Receipts',
    'receivables': 'Accounts Receivables',
    'payables': 'Accounts Payables',
    'payables_ap': 'Accounts Payable (AP)',
    'bank_reconciliation': 'Bank Reconciliation',
    'vat_closing': 'VAT Period Closing',
    'accounts': 'Accounts',
    'account_auxiliaries': 'Account Auxiliaries',
    'aux_classes': 'Accounts Classes',
    'aux_header1': 'Account Header 1',
    'aux_header2': 'Account Header 2',
    'aux_header3': 'Account Header 3',
    'aux_group': 'Account Group',
    'jv_description': 'Jv Description',
    'jv_types': 'Jv Types',
    'currency': 'Currency',
    'currency_rates': 'Currency Rates',
    'dept_groups': 'Department Groups',
    'department': 'Department',
    'cash_flow_setup': 'Cash Flow Report Setup',
    'sub_department': 'Sub Department',

    // HR Sub-Items
    'schedule_overview': 'Schedule Overview',
    'personnel': 'Personnel',
    'schedules': 'Schedules',
    'organization_setup': 'Organization Setup',
    'internal_departments': 'Internal Departments',
    'designations': 'Designations',
    'pos_employee_roles': 'POS Employee Roles',
    'time_attendance': 'Time & Attendance',
    'time_off_requests': 'Time Off Requests',
    'schedule_templates': 'Schedule Templates',
    'time_off_reasons': 'Time Off Reasons',
    'attendance_summary': 'Attendance Summary',
    'attendance_log': 'Attendance Log',
    'payroll': 'Payroll',
    'payroll_dashboard': 'Payroll Dashboard',
    'salary_processing': 'Salary Processing',
    'payment_settings': 'Payment Settings',
    'earnings_deductions': 'Earnings & Deductions',
    'employee_schedule': 'Employee Schedule',
    'employee_directory': 'Employee Directory',
    'payroll_management': 'Payroll Management',

    // Fleet Sub-Items
    'fleet_dashboard': 'Fleet Dashboard',
    'fleet_reports': 'Fleet Reports',
    'active_dispatches': 'Active Dispatches',
    'driver_management': 'Driver Management',
    'route_optimization': 'Route Optimization',
    'vehicle_maintenance': 'Vehicle Maintenance',
    'driver_settlements': 'Driver Settlements',
    'vtrack_geographics': 'V-Track Geographics',
    'gps_fleet_map': 'Live GPS Fleet Map',
    'km_odometer_logs': 'KM & Odometer Logs',
    'fuel_consumption': 'Fuel Consumption',
    'route_playback': 'Route Playback',
    'driver_directory': 'Drivers Directory',

    // Social CRM Sub-Items
    'vconnect_hub': 'V-Connect Hub',
    'social_crm_dashboard': 'Social CRM Dashboard',
    'lead_pipeline_acquisition': 'Lead Pipeline & Acquisition',
    'lead_pipeline_cpl': 'Lead Pipeline & CPL Campaigns',
    'omnichannel_inbox': 'Omnichannel Inbox',
    'unified_inbox': 'Unified Social Inbox',
    'platform_orders': 'Platform Orders',
    'publishing_calendar': 'Publishing Calendar',
    'ad_campaigns': 'Ad Campaigns',
    'support_agents': 'Support Agents',
    'distributors': 'Distributors',
    'distributors_directory': 'Distributors Directory',
    'campaign_analytics': 'Campaign Analytics',
    'automation_bots': 'Automation Bots',
    'wholesale_sales': 'Wholesale Sales',

    // Pressing Mill Sub-Items
    'pm_dashboard': 'Dashboard',
    'pm_seasons': 'Season Management',
    'pm_intake': 'Weighbridge & Intake',
    'pm_batches': 'Pressing Lines & Batches',
    'pm_tanks': 'Tanks Matrix (1-50)',
    'pm_settlements': 'Settlements & Milling Fees',
    'pm_dispatch': 'Oil Handover & Dispatch',
    'pm_pos': 'Direct Counter Sales & POS',
    'pm_directory': 'Directory & Ledgers',
    'pm_setup': 'Mill Settings & Line Config',
    'in_kind_retention': 'In-Kind Retention',
    'cash_fee': 'Cash Fee',
    'mixed_settlement': 'Mixed Split',
    'gross_weight': 'Gross Weight',
    'tare_weight': 'Tare Weight',
    'net_weight': 'Net Weight',
    'acidity_pct': 'Acidity %',
    'yield_pct': 'Yield %',

    // V-Store Sub-Items & Footer
    'customer_storefront': 'Customer Storefront',
    'identity_settings': 'Identity & Settings',
    'license_certificate': 'License Certificate',

    // Global Header & Account
    'organization': 'Organization',
    'users': 'Users',
    'roles': 'Roles & Permissions',
    'my_account': 'My Account',
    'language': 'Language',
    'support_center': 'Support Center',
    'feedback': 'Feedback',
    'logout': 'Logout',
    'latest_updates': 'Latest Updates',
    'notifications_inbox': 'Notifications & Inbox',
    'grid_dashboard': 'Grid Dashboard',
    'recently_visited': 'Recently Visited',
    'end_of_month': 'End of Month',
    'tenant_identity_settings': 'Identity & License Settings',
    'tenant_profile_title': 'Company Identity & Legal Settings',
    'tenant_profile_subtitle': 'Edit official name, logo, commercial registration, and tax ID.',
    'brand_identity': '1. Brand Identity & Official Logo',
    'company_name_ar': 'Company Name (Arabic)',
    'company_name_en': 'Enterprise Brand Name (English)',
    'logo_url': 'External Logo Image URL',
    'add_picture': 'Add Picture',
    'click_to_upload': 'Click to upload photo',
    'legal_registration': '2. Legal Registration Numbers',
    'commercial_reg': 'Commercial Registration No. (CR)',
    'tax_id': 'Tax Identification Number (MOF)',
  },

  ar: {
    // Top Modules
    'workspace': 'مساحة العمل',
    'sales_control': '1. إدارة المبيعات ونقطة البيع',
    'operations_center': '2. مركز العمليات والمعاصر',
    'purchases': '3. المشتريات والتوريد',
    'crm_debtors': '4. إدارة العملاء والذمم (CRM)',
    'complaints_dashboard': '5. الشكاوى واستطلاعات الرأي',
    'loyalty_program': '6. إدارة برنامج الولاء',
    'accounting_finance': '7. المحاسبة والإدارة المالية',
    'hr_payroll': '8. الموارد البشرية والرواتب',
    'supersonic_fleet': '9. أسطول الشحن والتوصيل V-Driver',
    'social_crm': '10. منصة التواصل الاجتماعي V-Connect',
    'pressing_mill_nav': '11. منظومة معصرة الزيتون',
    'olive_pressing': 'عصر الزيتون والإنتاج',
    'pressing_mill': 'معصرة الزيتون',
    'oil_pressing_short': 'عصر الزيتون',

    // Shared / Core
    'dashboard': 'لوحة التحكم',
    'reports': 'التقارير',
    'reports_hub': 'مركز التقارير',
    'online_orders': 'الطلبات عبر الإنترنت',
    'end_of_day': 'إغلاق اليومية',
    'setup': 'الإعدادات والتهيئة',
    'more_setup': 'إعدادات إضافية',
    'actions': 'العمليات والإجراءات',
    'settings': 'الإعدادات',
    'more': 'المزيد',
    'cancel': 'إلغاء',
    'save_changes': 'حفظ التغييرات',
    'saving': 'جاري الحفظ...',
    'search_menu': 'بحث في القوائم والشاشات...',
    'search_placeholder': 'بحث سريع في الشاشات والعمليات...',
    'alerts': 'التنبيهات',
    'exchange_rate': 'سعر الصرف',
    'system_active': 'النظام يعمل ومتصل بالإنترنت',
    'vanguard_system': 'نظام Vanguard ERP',
    'all_rights_reserved': '© 2026 جميع الحقوق محفوظة',
    'privacy_policy': 'سياسة الخصوصية',

    // Sales Control Sub-Items
    'pos_terminal': 'نقطة البيع الكاشير',
    'pos_layout_config': 'تنسيق شاشات الكاشير',
    'screens': 'الشاشات ونقاط البيع',
    'payment_types': 'طرق وأنواع الدفع',
    'coupons_vouchers': 'الكوبونات وقسائم الخصم',
    'coupons_gift_cert': 'الكوبونات وقسائم الهدايا',
    'discounts': 'الخصومات والتخفيضات',
    'price_modes': 'شرائح وأنماط الأسعار',
    'workstations_printers': 'محطات العمل والطابعات',
    'void_reasons': 'أسباب إلغاء الفواتير',
    'vat_exemptions': 'أسباب الإعفاء الضريبي',
    'vat_exemption_reasons': 'أسباب الإعفاء الضريبي',
    'invoice_message': 'رسالة أسفل الفاتورة',
    'invoice_messages': 'رسالة أسفل الفاتورة',
    'zone_setup': 'إعداد المناطق والتوصيل',
    'currency_setup': 'إعداد العملات وسعر الصرف',

    // Operations Center Sub-Items
    'sales': 'المبيعات',
    'quotations': 'عروض الأسعار',
    'delivery_goods': 'إرساليات تسليم البضائع',
    'purchase_orders': 'أوامر الشراء للموردين',
    'reorder_guide': 'دليل إعادة الطلب',
    'transfers': 'المناقلات والتحويلات',
    'stock_transfer': 'مناقلات بين المستودعات',
    'lost_goods': 'بضائع مفقودة وتالفة',
    'lost_damaged_goods': 'سجل التالف والمفقودات',
    'item_assembly': 'تجميع وتفكيك الأصناف',
    'bom_assembly': 'تجميع المنتجات BOM',
    'adjustments': 'تسويات الجرد المخزني',
    'inventory_adjustments': 'تسوية الجرد المخزني',
    'product_request': 'طلب منتجات',
    'product_requests': 'طلبات المنتجات الداخلية',
    'manage_product_requests': 'إدارة طلبات المنتجات',
    'product_req_prep': 'تحضير طلبات المنتجات',
    'receiving_goods': 'استلام البضائع',
    'product_req_reports': 'تقارير طلبات المنتجات',
    'request_reject_reasons': 'أسباب رفض الطلبات',
    'events': 'الفعاليات والمناسبات',
    'events_management': 'المناسبات والفعاليات',
    'event_venues': 'أماكن وصالات الفعاليات',
    'event_resources': 'موارد ومعدات الفعاليات',
    'event_types': 'أنواع الفعاليات',
    'quick_setup': 'الإعداد السريع للنظام',
    'products_services': 'المنتجات والخدمات',
    'product_groups': 'مجموعات المنتجات',
    'groups': 'المجموعات',
    'divisions': 'الأقسام الرئيسية',
    'categories': 'الفئات والتصنيفات',
    'units': 'وحدات القياس',
    'uom_tanks': 'وحدات القياس والخزانات',
    'locations': 'المستودعات والمواقع',
    'warehouses_locations': 'المستودعات والمواقع',
    'suppliers': 'الموردون والشركات',
    'departments': 'الأقسام الإدارية',
    'lost_goods_reason': 'أسباب فقدان البضائع',
    'sizes_groups': 'مجموعات المقاسات',
    'sizes': 'المقاسات والأحجام',
    'colors': 'الألوان',
    'inventory_brands': 'العلامات التجارية',
    'delivery_providers': 'شركات التوصيل والشحن',

    // Purchasing Sub-Items
    'purchases_ap_bills': 'المشتريات وفواتير الموردين',
    'goods_receiving_grn': 'سندات استلام البضائع (GRN)',
    'suppliers_directory': 'دليل الموردين والشركات',
    'procurement_reports': 'تقارير المشتريات والتوريد',

    // Customer CRM Sub-Items
    'customer_directory': 'دليل حسابات العملاء',
    'customers_directory': 'دليل العملاء',
    'customer_receipts': 'سندات قبض العملاء',
    'receipts_vouchers': 'سندات القبض المالية',
    'aged_debtors': 'تحليل أعمار الديون والذمم',
    'customer_aged_receivables': 'أعمار الذمم والديون',
    'customer_insights': 'تحليلات ورؤى العملاء الذكية',
    'ltv_insights': 'تحليلات القيمة الممتدة LTV',
    'tasks_appointments': 'المهام والمواعيد',
    'leads_opportunities': 'الفرص والعملاء المحتملين',
    'sales_team_performance': 'أداء فريق المبيعات',
    'sales_rep_performance': 'أداء مندوبي المبيعات',
    'customers_groups': 'مجموعات العملاء',
    'customers_categories': 'فئات وتصنيفات العملاء',
    'customers_tags': 'وسوم وعلامات العملاء',

    // Feedback Sub-Items
    'manage_complaints': 'إدارة الشكاوى',
    'add_complaints': 'إضافة شكوى جديدة',
    'manage_surveys': 'إدارة الاستطلاعات',
    'send_survey_emails': 'إرسال الاستطلاعات بالبريد',
    'complaint_sources': 'مصادر الشكاوى',
    'complaint_categories': 'تصنيفات الشكاوى',
    'complaint_action_types': 'أنواع إجراءات المعالجة',
    'customer_care': 'العناية بالعملاء',
    'surveys_setup': 'إعداد الاستطلاعات',

    // Loyalty Sub-Items
    'members': 'الأعضاء والمشتركون',
    'loyalty_levels': 'مستويات وفئات الولاء',
    'loyalty_programs': 'برامج الولاء والمكافآت',
    'send_messages': 'إرسال الرسائل والعروض',
    'company_info': 'بيانات الشركة والفرع',

    // Accounting Sub-Items
    'chart_of_accounts': 'دليل الحسابات (COA)',
    'journal_voucher': 'سند القيد اليومي (JV)',
    'journal_vouchers': 'سندات القيد اليومية',
    'purchase': 'فواتير المشتريات',
    'payments': 'سندات الصرف والدفع',
    'receipts': 'سندات القبض المالي',
    'receivables': 'حسابات المدينين والذمم',
    'payables': 'حسابات الموردين والدائنين',
    'payables_ap': 'حسابات الموردين (AP)',
    'bank_reconciliation': 'مطابقة الحسابات البنكية',
    'vat_closing': 'إقفال الفترة الضريبية TVA',
    'accounts': 'الحسابات والدليل المالي',
    'account_auxiliaries': 'الحسابات المساعدة والمكملة',
    'aux_classes': 'طبقات وفئات الحسابات',
    'aux_header1': 'ترويسة الحساب المستوى 1',
    'aux_header2': 'ترويسة الحساب المستوى 2',
    'aux_header3': 'ترويسة الحساب المستوى 3',
    'aux_group': 'مجموعات الحسابات',
    'jv_description': 'شروحات قيود اليومية',
    'jv_types': 'أنواع القيود اليومية',
    'currency': 'العملات والوحدات النقدية',
    'currency_rates': 'أسعار الصرف والتحويل',
    'dept_groups': 'مجموعات الأقسام والمراكز',
    'department': 'الأقسام ومراكز التكلفة',
    'cash_flow_setup': 'إعداد تقرير التدفقات النقدية',
    'sub_department': 'الأقسام الفرعية',

    // HR Sub-Items
    'schedule_overview': 'نظرة عامة على الجداول',
    'personnel': 'سجل الموظفين والكادر',
    'schedules': 'جداول المناوبات والدوام',
    'organization_setup': 'الهيكل التنظيمي للمؤسسة',
    'internal_departments': 'الأقسام والوحدات الداخلية',
    'designations': 'المسميات الوظيفية والرتب',
    'pos_employee_roles': 'أدوار موظفي الكاشير',
    'time_attendance': 'الحضور والإنصراف والبصمة',
    'time_off_requests': 'طلبات الإجازات والمغادرات',
    'schedule_templates': 'قوالب جداول الدوام',
    'time_off_reasons': 'أسباب الإجازات والغياب',
    'attendance_summary': 'ملخص الحضور والغياب',
    'attendance_log': 'سجل البصمة والحركات اليومية',
    'payroll': 'مسير الرواتب والأجور',
    'payroll_dashboard': 'لوحة تحكم الرواتب',
    'salary_processing': 'معالجة وصرف الرواتب',
    'payment_settings': 'إعدادات الصرف والتحويل',
    'earnings_deductions': 'الاستحقاقات والاستقطاعات',
    'employee_schedule': 'جدول المناوبات والدوام',
    'employee_directory': 'سجل الموظفين والكادر',
    'payroll_management': 'مسير الرواتب والأجور',

    // Fleet Sub-Items
    'fleet_dashboard': 'لوحة تحكم الأسطول',
    'fleet_reports': 'تقارير الأسطول والرحلات',
    'active_dispatches': 'الإرساليات والرحلات النشطة',
    'driver_management': 'إدارة السائقين والمندوبين',
    'route_optimization': 'تحسين مسارات التوزيع',
    'vehicle_maintenance': 'صيانة ومعاينة السيارات',
    'driver_settlements': 'تسويات ومحاسبة السائقين',
    'vtrack_geographics': 'التتبع الجغرافي المباشر V-Track',
    'gps_fleet_map': 'خريطة التتبع المباشر GPS',
    'km_odometer_logs': 'سجل عدادات الكيلومترات',
    'fuel_consumption': 'متابعة استهلاك المحروقات',
    'route_playback': 'إعادة تشغيل مسار الرحلات',
    'driver_directory': 'دليل السائقين والمندوبين',

    // Social CRM Sub-Items
    'vconnect_hub': 'منصة التواصل V-Connect',
    'social_crm_dashboard': 'لوحة تحكم التواصل CRM',
    'lead_pipeline_acquisition': 'مسار واكتساب العملاء المحتملين',
    'lead_pipeline_cpl': 'مسار العملاء وحملات CPL',
    'omnichannel_inbox': 'صندوق الوارد الموحد لكافة القنوات',
    'unified_inbox': 'صندوق الرسائل الموحد',
    'platform_orders': 'طلبات المنصات الذكية',
    'publishing_calendar': 'تقويم المنشورات والحملات',
    'ad_campaigns': 'إدارة الحملات الإعلانية',
    'support_agents': 'فريق الدعم والممثلين',
    'distributors': 'الموزعون والتجار المعتمدون',
    'distributors_directory': 'دليل الموزعين والتجار',
    'campaign_analytics': 'تحليلات الحملات الإعلانية',
    'automation_bots': 'روبوتات الرد التلقائي الذكية',
    'wholesale_sales': 'مبيعات الجملة والبراميل',

    // Pressing Mill Sub-Items
    'pm_dashboard': 'لوحة التحكم والعمليات',
    'pm_seasons': 'إدارة المواسم والحملات',
    'pm_intake': 'القبان واستلام الزيتون',
    'pm_batches': 'خطوط العصر والدفعات',
    'pm_tanks': 'مصفوفة الخزانات (1-50)',
    'pm_settlements': 'المحاسبة وأجور العصر',
    'pm_dispatch': 'تسليم الزيت وتصريح الخروج',
    'pm_pos': 'نقطة البيع والصندوق المباشر',
    'pm_directory': 'دليل المزارعين والأرصدة',
    'pm_setup': 'إعدادات المعصرة والخطوط',
    'in_kind_retention': 'الردة العينية (نسبة الزيت)',
    'cash_fee': 'الأجرة النقدية',
    'mixed_settlement': 'تسوية مختلطة (نقد + زيت)',
    'gross_weight': 'الوزن القائم (الإجمالي)',
    'tare_weight': 'وزن الشاحنة الفارغة (الطار)',
    'net_weight': 'الوزن الصافي للزيتون',
    'acidity_pct': 'نسبة الأسيد (الحموضة)',
    'yield_pct': 'نسبة الاستخراج (السيالة)',

    // V-Store Sub-Items & Footer
    'customer_storefront': 'واجهة متجر العملاء',
    'identity_settings': 'هوية المنشأة والإعدادات',
    'license_certificate': 'شهادة الترخيص الرسمية',

    // Global Header & Account
    'organization': 'بيانات المنشأة والمؤسسة',
    'users': 'إدارة المستخدمين',
    'roles': 'الأدوار ومصفوفة الصلاحيات',
    'my_account': 'حسابي الشخصي',
    'language': 'اللغة',
    'support_center': 'مركز المساعدة والدعم',
    'feedback': 'الملاحظات والاقتراحات',
    'logout': 'تسجيل الخروج',
    'latest_updates': 'آخر التحديثات',
    'notifications_inbox': 'الإشعارات وصندوق الوارد',
    'grid_dashboard': 'لوحة الشبكة الرئيسية',
    'recently_visited': 'الزيارات الأخيرة',
    'end_of_month': 'إغلاق الشهر',
    'tenant_identity_settings': 'إعدادات الشعار والترخيص',
    'tenant_profile_title': 'إعدادات هوية المؤسسة والبيانات القانونية',
    'tenant_profile_subtitle': 'تعديل الاسم والشعار الرسمي وتضمين رقم السجل التجاري والرقم المالي.',
    'brand_identity': '1. الاسم التجاري والشعار الرسمي',
    'company_name_ar': 'اسم الشركة / المؤسسة (بالعربي)',
    'company_name_en': 'Enterprise Brand Name (English)',
    'logo_url': 'رابط الشعار الخارجي',
    'add_picture': 'إضافة صورة',
    'click_to_upload': 'انقر لتحميل صورة',
    'legal_registration': '2. البيانات القانونية والترخيص',
    'commercial_reg': 'رقم السجل التجاري (CR)',
    'tax_id': 'الرقم المالي (MOF)',
  },

  fr: {
    // Top Modules
    'workspace': 'Espace de Travail',
    'sales_control': '1. Gestion des Ventes & POS',
    'operations_center': '2. Centre d\'Opérations & Pressage',
    'purchases': '3. Achats & Approvisionnement',
    'crm_debtors': '4. Gestion Clients & Créances (CRM)',
    'complaints_dashboard': '5. Réclamations & Enquêtes',
    'loyalty_program': '6. Gestion de Fidélité',
    'accounting_finance': '7. Comptabilité & Finance',
    'hr_payroll': '8. Ressources Humaines & Paie',
    'supersonic_fleet': '9. Flotte SuperSonic / V-Driver',
    'social_crm': '10. CRM Réseaux Sociaux V-Connect',
    'pressing_mill_nav': '11. Moteur Pressoir à Olives',
    'olive_pressing': 'Pressage d\'Olives & Production',
    'pressing_mill': 'Pressoir à Olives',
    'oil_pressing_short': 'Pressage Oléicole',

    // Shared / Core
    'dashboard': 'Tableau de Bord',
    'reports': 'Rapports',
    'reports_hub': 'Centre de Rapports',
    'online_orders': 'Commandes en Ligne',
    'end_of_day': 'Clôture Journalière',
    'setup': 'Configuration',
    'more_setup': 'Configuration Avancée',
    'actions': 'Actions',
    'settings': 'Paramètres',
    'more': 'Plus',
    'cancel': 'Annuler',
    'save_changes': 'Enregistrer les Modifications',
    'saving': 'Enregistrement...',
    'search_menu': 'rechercher dans le menu...',
    'search_placeholder': 'Recherche rapide dans le système...',
    'alerts': 'Alertes',
    'exchange_rate': 'Taux de Change',
    'system_active': 'Système Actif & En Ligne',
    'vanguard_system': 'Système Vanguard ERP',
    'all_rights_reserved': '© 2026 Tous Droits Réservés',
    'privacy_policy': 'Politique de Confidentialité',

    // Sales Control Sub-Items
    'pos_terminal': 'Terminal Caisse POS',
    'pos_layout_config': 'Configuration Écrans POS',
    'screens': 'Écrans & Caisses',
    'payment_types': 'Modes de Paiement',
    'coupons_vouchers': 'Coupons & Bons',
    'coupons_gift_cert': 'Coupons & Cartes Cadeaux',
    'discounts': 'Remises & Tarifs',
    'price_modes': 'Grilles Tarifaires',
    'workstations_printers': 'Postes & Imprimantes',
    'void_reasons': 'Motifs d\'Annulation',
    'vat_exemptions': 'Motifs d\'Exonération TVA',
    'vat_exemption_reasons': 'Motifs d\'Exonération TVA',
    'invoice_message': 'Message de Facture',
    'invoice_messages': 'Message sur Facture',
    'zone_setup': 'Zones de Livraison',
    'currency_setup': 'Devises & Taux de Change',

    // Operations Center Sub-Items
    'sales': 'Ventes',
    'quotations': 'Devis & Estimations',
    'delivery_goods': 'Bons de Livraison',
    'purchase_orders': 'Bons de Commande',
    'reorder_guide': 'Guide de Réapprovisionnement',
    'transfers': 'Transferts Inter-Dépôts',
    'stock_transfer': 'Transferts de Stock',
    'lost_goods': 'Marchandises Perdues',
    'lost_damaged_goods': 'Pertes & Dommages',
    'item_assembly': 'Assemblage d\'Articles',
    'bom_assembly': 'Assemblage Nomenclature BOM',
    'adjustments': 'Ajustements de Stock',
    'inventory_adjustments': 'Ajustements d\'Inventaire',
    'product_request': 'Demande de Produits',
    'product_requests': 'Demandes de Produits',
    'manage_product_requests': 'Gestion des Demandes',
    'product_req_prep': 'Préparation des Demandes',
    'receiving_goods': 'Réception de Marchandises',
    'product_req_reports': 'Rapports de Demandes',
    'request_reject_reasons': 'Motifs de Rejet',
    'events': 'Événements',
    'events_management': 'Événements & Occasions',
    'event_venues': 'Lieux d\'Événements',
    'event_resources': 'Ressources d\'Événements',
    'event_types': 'Types d\'Événements',
    'quick_setup': 'Configuration Rapide',
    'products_services': 'Produits & Services',
    'product_groups': 'Groupes de Produits',
    'groups': 'Groupes',
    'divisions': 'Divisions',
    'categories': 'Catégories',
    'units': 'Unités de Mesure',
    'uom_tanks': 'Unités de Mesure & Cuves',
    'locations': 'Emplacements & Dépôts',
    'warehouses_locations': 'Entrepôts & Emplacements',
    'suppliers': 'Fournisseurs',
    'departments': 'Départements',
    'lost_goods_reason': 'Motifs de Perte',
    'sizes_groups': 'Groupes de Tailles',
    'sizes': 'Tailles',
    'colors': 'Couleurs',
    'inventory_brands': 'Marques',
    'delivery_providers': 'Prestataires de Livraison',

    // Purchasing Sub-Items
    'purchases_ap_bills': 'Achats & Factures Fournisseurs',
    'goods_receiving_grn': 'Bons de Réception (GRN)',
    'suppliers_directory': 'Annuaire Fournisseurs',
    'procurement_reports': 'Rapports d\'Approvisionnement',

    // Customer CRM Sub-Items
    'customer_directory': 'Annuaire Comptes Clients',
    'customers_directory': 'Annuaire Clients',
    'customer_receipts': 'Reçus Clients',
    'receipts_vouchers': 'Bons de Recette',
    'aged_debtors': 'Balance Âgée des Créances',
    'customer_aged_receivables': 'Balance Âgée Clients',
    'customer_insights': 'Analyses Clients Intelligentes',
    'ltv_insights': 'Analyse LTV Clients',
    'tasks_appointments': 'Tâches & Rendez-vous',
    'leads_opportunities': 'Pistes & Opportunités',
    'sales_team_performance': 'Performance Commerciale',
    'sales_rep_performance': 'Performance des Vendeurs',
    'customers_groups': 'Groupes de Clients',
    'customers_categories': 'Catégories de Clients',
    'customers_tags': 'Tags Clients',

    // Feedback Sub-Items
    'manage_complaints': 'Gestion des Réclamations',
    'add_complaints': 'Ajouter une Réclamation',
    'manage_surveys': 'Gestion des Enquêtes',
    'send_survey_emails': 'Envoyer Enquêtes par Email',
    'complaint_sources': 'Sources des Réclamations',
    'complaint_categories': 'Catégories de Réclamations',
    'complaint_action_types': 'Types d\'Actions Correctives',
    'customer_care': 'Service Client & Support',
    'surveys_setup': 'Configuration des Enquêtes',

    // Loyalty Sub-Items
    'members': 'Membres & Adhérents',
    'loyalty_levels': 'Niveaux de Fidélité',
    'loyalty_programs': 'Programmes de Fidélité',
    'send_messages': 'Diffuser des Messages',
    'company_info': 'Informations Société',

    // Accounting Sub-Items
    'chart_of_accounts': 'Plan Comptable (COA)',
    'journal_voucher': 'Écriture Journal (JV)',
    'journal_vouchers': 'Écritures Comptables (JV)',
    'purchase': 'Achats Comptables',
    'payments': 'Règlements Fournisseurs',
    'receipts': 'Encaissements Clients',
    'receivables': 'Comptes Clients & Créances',
    'payables': 'Comptes Fournisseurs & Dettes',
    'payables_ap': 'Comptes Fournisseurs (AP)',
    'bank_reconciliation': 'Rapprochement Bancaire',
    'vat_closing': 'Clôture Période TVA',
    'accounts': 'Comptes Comptables',
    'account_auxiliaries': 'Comptes Auxiliaires',
    'aux_classes': 'Classes de Comptes',
    'aux_header1': 'En-tête de Compte 1',
    'aux_header2': 'En-tête de Compte 2',
    'aux_header3': 'En-tête de Compte 3',
    'aux_group': 'Groupes de Comptes',
    'jv_description': 'Libellés des Écritures',
    'jv_types': 'Types d\'Écritures',
    'currency': 'Devises',
    'currency_rates': 'Taux de Change',
    'dept_groups': 'Groupes de Départements',
    'department': 'Département',
    'cash_flow_setup': 'Configuration Tableau de Flux',
    'sub_department': 'Sous-Département',

    // HR Sub-Items
    'schedule_overview': 'Vue d\'Ensemble des Plannings',
    'personnel': 'Personnel & Salariés',
    'schedules': 'Horaires de Travail',
    'organization_setup': 'Structure Organisationnelle',
    'internal_departments': 'Départements Internes',
    'designations': 'Fonctions & Postes',
    'pos_employee_roles': 'Rôles Employés POS',
    'time_attendance': 'Présence & Pointage',
    'time_off_requests': 'Demandes de Congé',
    'schedule_templates': 'Modèles de Planning',
    'time_off_reasons': 'Motifs d\'Absence',
    'attendance_summary': 'Récapitulatif Présences',
    'attendance_log': 'Journal de Pointage',
    'payroll': 'Gestion de la Paie',
    'payroll_dashboard': 'Tableau de Bord Paie',
    'salary_processing': 'Traitement des Salaires',
    'payment_settings': 'Paramètres de Paiement',
    'earnings_deductions': 'Gains & Déductions',
    'employee_schedule': 'Planning Employés',
    'employee_directory': 'Annuaire Personnel',
    'payroll_management': 'Gestion de Paie',

    // Fleet Sub-Items
    'fleet_dashboard': 'Tableau de Bord Flotte',
    'fleet_reports': 'Rapports de Flotte',
    'active_dispatches': 'Expéditions Actives',
    'driver_management': 'Gestion des Chauffeurs',
    'route_optimization': 'Optimisation des Itinéraires',
    'vehicle_maintenance': 'Entretien des Véhicules',
    'driver_settlements': 'Règlements Chauffeurs',
    'vtrack_geographics': 'Suivi Géographique V-Track',
    'gps_fleet_map': 'Carte GPS en Direct',
    'km_odometer_logs': 'Relevés Kilométriques',
    'fuel_consumption': 'Consommation de Carburant',
    'route_playback': 'Historique des Trajets',
    'driver_directory': 'Annuaire Chauffeurs',

    // Social CRM Sub-Items
    'vconnect_hub': 'Hub V-Connect',
    'social_crm_dashboard': 'Tableau de Bord Social CRM',
    'lead_pipeline_acquisition': 'Pipeline Commercial & Prospects',
    'lead_pipeline_cpl': 'Pipeline & Campagnes CPL',
    'omnichannel_inbox': 'Boîte de Réception Omnicanale',
    'unified_inbox': 'Boîte de Réception Unique',
    'platform_orders': 'Commandes Plateformes',
    'publishing_calendar': 'Calendrier de Publication',
    'ad_campaigns': 'Campagnes Publicitaires',
    'support_agents': 'Agents de Support',
    'distributors': 'Distributeurs & Partenaires',
    'distributors_directory': 'Annuaire Distributeurs',
    'campaign_analytics': 'Analyses de Campagnes',
    'automation_bots': 'Bots d\'Automatisation',
    'wholesale_sales': 'Ventes en Gros',

    // Pressing Mill Sub-Items
    'pm_dashboard': 'Tableau de Bord',
    'pm_seasons': 'Gestion des Campagnes',
    'pm_intake': 'Pont-Bascule & Réception',
    'pm_batches': 'Lignes d\'Extraction & Lots',
    'pm_tanks': 'Matrice des Cuves (1-50)',
    'pm_settlements': 'Règlements & Frais',
    'pm_dispatch': 'Remise d\'Huile & Expédition',
    'pm_pos': 'Vente Directe & Caisse TPV',
    'pm_directory': 'Annuaire & Grands Livres',
    'pm_setup': 'Paramètres du Pressoir',
    'in_kind_retention': 'Rétention en Nature',
    'cash_fee': 'Frais en Espèces',
    'mixed_settlement': 'Règlement Mixte',
    'gross_weight': 'Poids Brut',
    'tare_weight': 'Tare',
    'net_weight': 'Poids Net',
    'acidity_pct': 'Acidité %',
    'yield_pct': 'Rendement %',

    // V-Store Sub-Items & Footer
    'customer_storefront': 'Boutique en Ligne Clients',
    'identity_settings': 'Identité & Paramètres',
    'license_certificate': 'Certificat de Licence',

    // Global Header & Account
    'organization': 'Organisation & Entreprise',
    'users': 'Utilisateurs',
    'roles': 'Rôles & Permissions',
    'my_account': 'Mon Compte',
    'language': 'Langue',
    'support_center': 'Centre d\'Assistance',
    'feedback': 'Commentaires & Suggestions',
    'logout': 'Déconnexion',
    'latest_updates': 'Dernières Mises à Jour',
    'notifications_inbox': 'Notifications & Boîte',
    'grid_dashboard': 'Tableau de Bord Grille',
    'recently_visited': 'Récemment Visités',
    'end_of_month': 'Clôture Mensuelle',
    'tenant_identity_settings': 'Identité & Licence',
    'tenant_profile_title': 'Identité d\'Entreprise & Mentions Légales',
    'tenant_profile_subtitle': 'Modifier le nom officiel, le logo, le registre du commerce et l\'ID fiscal.',
    'brand_identity': '1. Identité de Marque & Logo Officiel',
    'company_name_ar': 'Nom de la Société (Arabe)',
    'company_name_en': 'Nom de la Marque (Anglais)',
    'logo_url': 'URL du Logo Externe',
    'add_picture': 'Ajouter une Image',
    'click_to_upload': 'Cliquer pour télécharger',
    'legal_registration': '2. Numéros d\'Immatriculation Légale',
    'commercial_reg': 'Registre du Commerce (RC)',
    'tax_id': 'Numéro d\'Identification Fiscale (NIF)',
  },

  es: {
    // Top Modules
    'workspace': 'Espacio de Trabajo',
    'sales_control': '1. Control de Ventas y TPV',
    'operations_center': '2. Centro de Operaciones y Prensado',
    'purchases': '3. Compras y Suministros',
    'crm_debtors': '4. Gestión de Clientes y Cuentas (CRM)',
    'complaints_dashboard': '5. Reclamaciones y Encuestas',
    'loyalty_program': '6. Gestión de Fidelización',
    'accounting_finance': '7. Contabilidad y Finanzas',
    'hr_payroll': '8. Recursos Humanos y Nóminas',
    'supersonic_fleet': '9. Flota SuperSonic / V-Driver',
    'social_crm': '10. CRM Redes Sociales V-Connect',
    'pressing_mill_nav': '11. Motor Almazara de Aceitunas',
    'olive_pressing': 'Prensado de Aceitunas y Producción',
    'pressing_mill': 'Almazara de Aceitunas',
    'oil_pressing_short': 'Prensado de Aceite',

    // Shared / Core
    'dashboard': 'Panel de Control',
    'reports': 'Informes',
    'reports_hub': 'Centro de Informes',
    'online_orders': 'Pedidos en Línea',
    'end_of_day': 'Informe Cierre Z-Report',
    'setup': 'Configuración',
    'more_setup': 'Más Configuración',
    'actions': 'Acciones',
    'settings': 'Configuración',
    'more': 'Más',
    'cancel': 'Cancelar',
    'save_changes': 'Guardar Cambios',
    'saving': 'Guardando...',
    'search_menu': 'buscar en el menú...',
    'search_placeholder': 'Búsqueda rápida en el sistema...',
    'alerts': 'Alertas',
    'exchange_rate': 'Tipo de Cambio',
    'system_active': 'Sistema Activo y En Línea',
    'vanguard_system': 'Sistema Vanguard ERP',
    'all_rights_reserved': '© 2026 Todos los Derechos Reservados',
    'privacy_policy': 'Política de Privacidad',

    // Sales Control Sub-Items
    'pos_terminal': 'Terminal Caja TPV',
    'pos_layout_config': 'Configuración Pantallas TPV',
    'screens': 'Pantallas y TPV',
    'payment_types': 'Métodos de Pago',
    'coupons_vouchers': 'Cupones y Vouchers',
    'coupons_gift_cert': 'Cupones y Tarjetas Regalo',
    'discounts': 'Descuentos y Tarifas',
    'price_modes': 'Modos de Precios',
    'workstations_printers': 'Estaciones e Impresoras',
    'void_reasons': 'Motivos de Anulación',
    'vat_exemptions': 'Exenciones de IVA',
    'vat_exemption_reasons': 'Exenciones de IVA',
    'invoice_message': 'Mensaje en Factura',
    'invoice_messages': 'Mensaje en Factura',
    'zone_setup': 'Zonas de Envío',
    'currency_setup': 'Monedas y Tipo de Cambio',

    // Operations Center Sub-Items
    'sales': 'Ventas',
    'quotations': 'Presupuestos y Cotizaciones',
    'delivery_goods': 'Albaranes de Entrega',
    'purchase_orders': 'Órdenes de Compra',
    'reorder_guide': 'Guía de Reaprovisionamiento',
    'transfers': 'Transferencias de Stock',
    'stock_transfer': 'Transferencias entre Almacenes',
    'lost_goods': 'Bajas y Daños',
    'lost_damaged_goods': 'Pérdidas y Daños',
    'item_assembly': 'Ensamblaje de Artículos',
    'bom_assembly': 'Ensamblaje Lista BOM',
    'adjustments': 'Ajustes de Inventario',
    'inventory_adjustments': 'Ajustes de Inventario',
    'product_request': 'Solicitud de Productos',
    'product_requests': 'Solicitudes de Productos',
    'manage_product_requests': 'Gestión de Solicitudes',
    'product_req_prep': 'Preparación de Solicitudes',
    'receiving_goods': 'Recepción de Mercancías',
    'product_req_reports': 'Informes de Solicitudes',
    'request_reject_reasons': 'Motivos de Rechazo',
    'events': 'Eventos y Ocasiones',
    'events_management': 'Eventos y Ocasiones',
    'event_venues': 'Sedes de Eventos',
    'event_resources': 'Recursos de Eventos',
    'event_types': 'Tipos de Eventos',
    'quick_setup': 'Configuración Rápida',
    'products_services': 'Productos y Servicios',
    'product_groups': 'Grupos de Productos',
    'groups': 'Grupos',
    'divisions': 'Divisiones',
    'categories': 'Categorías',
    'units': 'Unidades de Medida',
    'uom_tanks': 'Unidades de Medida y Tanques',
    'locations': 'Ubicaciones y Almacenes',
    'warehouses_locations': 'Almacenes y Ubicaciones',
    'suppliers': 'Proveedores',
    'departments': 'Departamentos',
    'lost_goods_reason': 'Motivos de Pérdida',
    'sizes_groups': 'Grupos de Tallas',
    'sizes': 'Tallas',
    'colors': 'Colores',
    'inventory_brands': 'Marcas de Inventario',
    'delivery_providers': 'Proveedores de Entrega',

    // Purchasing Sub-Items
    'purchases_ap_bills': 'Compras y Facturas de Proveedores',
    'goods_receiving_grn': 'Recepción de Bienes (GRN)',
    'suppliers_directory': 'Directorio de Proveedores',
    'procurement_reports': 'Informes de Compras',

    // Customer CRM Sub-Items
    'customer_directory': 'Directorio Cuentas de Clientes',
    'customers_directory': 'Directorio de Clientes',
    'customer_receipts': 'Recibos de Clientes',
    'receipts_vouchers': 'Comprobantes de Ingreso',
    'aged_debtors': 'Análisis de Deuda y Antigüedad',
    'customer_aged_receivables': 'Antigüedad de Saldos',
    'customer_insights': 'Perspectivas de Clientes IA',
    'ltv_insights': 'Análisis LTV Clientes',
    'tasks_appointments': 'Tareas y Citas',
    'leads_opportunities': 'Oportunidades de Venta',
    'sales_team_performance': 'Rendimiento del Equipo',
    'sales_rep_performance': 'Rendimiento de Vendedores',
    'customers_groups': 'Grupos de Clientes',
    'customers_categories': 'Categorías de Clientes',
    'customers_tags': 'Etiquetas de Clientes',

    // Feedback Sub-Items
    'manage_complaints': 'Gestión de Reclamaciones',
    'add_complaints': 'Agregar Reclamación',
    'manage_surveys': 'Gestión de Encuestas',
    'send_survey_emails': 'Enviar Encuestas por Correo',
    'complaint_sources': 'Fuentes de Reclamaciones',
    'complaint_categories': 'Categorías de Reclamaciones',
    'complaint_action_types': 'Tipos de Acciones',
    'customer_care': 'Atención al Cliente',
    'surveys_setup': 'Configuración de Encuestas',

    // Loyalty Sub-Items
    'members': 'Miembros',
    'loyalty_levels': 'Niveles de Fidelidad',
    'loyalty_programs': 'Programas de Fidelización',
    'send_messages': 'Enviar Mensajes',
    'company_info': 'Información de la Empresa',

    // Accounting Sub-Items
    'chart_of_accounts': 'Plan de Cuentas (COA)',
    'journal_voucher': 'Asiento de Diario (JV)',
    'journal_vouchers': 'Asientos Contables (JV)',
    'purchase': 'Compras Contables',
    'payments': 'Pagos y Liquidaciones',
    'receipts': 'Cobros y Recibos',
    'receivables': 'Cuentas por Cobrar',
    'payables': 'Cuentas por Pagar (AP)',
    'payables_ap': 'Cuentas por Pagar (AP)',
    'bank_reconciliation': 'Conciliación Bancaria',
    'vat_closing': 'Cierre del Período de IVA',
    'accounts': 'Cuentas Contables',
    'account_auxiliaries': 'Cuentas Auxiliares',
    'aux_classes': 'Clases de Cuentas',
    'aux_header1': 'Encabezado de Cuenta 1',
    'aux_header2': 'Encabezado de Cuenta 2',
    'aux_header3': 'Encabezado de Cuenta 3',
    'aux_group': 'Grupo de Cuentas',
    'jv_description': 'Descripción de Asientos',
    'jv_types': 'Tipos de Asientos',
    'currency': 'Moneda',
    'currency_rates': 'Tipos de Cambio',
    'dept_groups': 'Grupos de Departamentos',
    'department': 'Departamento',
    'cash_flow_setup': 'Configuración de Flujo de Caja',
    'sub_department': 'Subdepartamento',

    // HR Sub-Items
    'schedule_overview': 'Resumen de Horarios',
    'personnel': 'Personal y Empleados',
    'schedules': 'Horarios de Trabajo',
    'organization_setup': 'Estructura Organizacional',
    'internal_departments': 'Departamentos Internos',
    'designations': 'Puestos y Cargos',
    'pos_employee_roles': 'Roles de Empleados TPV',
    'time_attendance': 'Control de Presencia y Turnos',
    'time_off_requests': 'Solicitudes de Permiso',
    'schedule_templates': 'Plantillas de Horarios',
    'time_off_reasons': 'Motivos de Permiso',
    'attendance_summary': 'Resumen de Asistencia',
    'attendance_log': 'Registro de Asistencia',
    'payroll': 'Gestión de Nóminas',
    'payroll_dashboard': 'Panel de Nóminas',
    'salary_processing': 'Procesamiento de Salarios',
    'payment_settings': 'Ajustes de Pago',
    'earnings_deductions': 'Devengos y Deducciones',
    'employee_schedule': 'Turnos de Empleados',
    'employee_directory': 'Directorio de Personal',
    'payroll_management': 'Gestión de Nóminas',

    // Fleet Sub-Items
    'fleet_dashboard': 'Panel de Flota',
    'fleet_reports': 'Informes de Flota',
    'active_dispatches': 'Despachos Activos',
    'driver_management': 'Gestión de Conductores',
    'route_optimization': 'Optimización de Rutas',
    'vehicle_maintenance': 'Mantenimiento de Vehículos',
    'driver_settlements': 'Liquidaciones de Conductores',
    'vtrack_geographics': 'Seguimiento V-Track',
    'gps_fleet_map': 'Mapa GPS en Vivo',
    'km_odometer_logs': 'Registros de Kilometraje',
    'fuel_consumption': 'Consumo de Combustible',
    'route_playback': 'Historial de Rutas',
    'driver_directory': 'Directorio de Conductores',

    // Social CRM Sub-Items
    'vconnect_hub': 'Hub V-Connect',
    'social_crm_dashboard': 'Panel Social CRM',
    'lead_pipeline_acquisition': 'Embudo de Clientes Potenciales',
    'lead_pipeline_cpl': 'Embudo y Campañas CPL',
    'omnichannel_inbox': 'Bandeja Omnicanal',
    'unified_inbox': 'Bandeja Social Unificada',
    'platform_orders': 'Pedidos de Plataforma',
    'publishing_calendar': 'Calendario de Publicación',
    'ad_campaigns': 'Campañas Publicitarias',
    'support_agents': 'Agentes de Soporte',
    'distributors': 'Distribuidores',
    'distributors_directory': 'Directorio de Distribuidores',
    'campaign_analytics': 'Analítica de Campañas',
    'automation_bots': 'Bots de Automatización',
    'wholesale_sales': 'Ventas al Por Mayor',

    // Pressing Mill Sub-Items
    'pm_dashboard': 'Panel de Control',
    'pm_seasons': 'Gestión de Campañas',
    'pm_intake': 'Báscula y Recepción',
    'pm_batches': 'Líneas de Prensado y Lotes',
    'pm_tanks': 'Matriz de Tanques (1-50)',
    'pm_settlements': 'Liquidaciones y Tarifas',
    'pm_dispatch': 'Entrega de Aceite y Despacho',
    'pm_pos': 'Ventas Directas y TPV',
    'pm_directory': 'Directorio y Balances',
    'pm_setup': 'Configuración de Almazara',
    'in_kind_retention': 'Retención en Especie',
    'cash_fee': 'Tarifa en Efectivo',
    'mixed_settlement': 'Liquidación Mixta',
    'gross_weight': 'Peso Bruto',
    'tare_weight': 'Tara',
    'net_weight': 'Peso Neto',
    'acidity_pct': 'Acidez %',
    'yield_pct': 'Rendimiento %',

    // V-Store Sub-Items & Footer
    'customer_storefront': 'Tienda de Clientes',
    'identity_settings': 'Identidad y Ajustes',
    'license_certificate': 'Certificado de Licencia',

    // Global Header & Account
    'organization': 'Organización y Empresa',
    'users': 'Usuarios',
    'roles': 'Roles y Permisos',
    'my_account': 'Mi Cuenta',
    'language': 'Idioma',
    'support_center': 'Centro de Soporte',
    'feedback': 'Comentarios y Sugerencias',
    'logout': 'Cerrar Sesión',
    'latest_updates': 'Últimas Actualizaciones',
    'notifications_inbox': 'Notificaciones y Bandeja',
    'grid_dashboard': 'Panel Cuadrícula',
    'recently_visited': 'Visitados Recientemente',
    'end_of_month': 'Cierre Mensual',
    'tenant_identity_settings': 'Identidad y Licencia',
    'tenant_profile_title': 'Identidad de la Empresa y Registro Legal',
    'tenant_profile_subtitle': 'Editar nombre oficial, logotipo, registro comercial e ID fiscal.',
    'brand_identity': '1. Identidad de Marca y Logotipo',
    'company_name_ar': 'Nombre de la Empresa (Árabe)',
    'company_name_en': 'Nombre de Marca (Inglés)',
    'logo_url': 'URL del Logotipo Externo',
    'add_picture': 'Agregar Imagen',
    'click_to_upload': 'Hacer clic para subir',
    'legal_registration': '2. Registro Legal y Licencia',
    'commercial_reg': 'Registro Mercantil (CR)',
    'tax_id': 'Número de Identificación Fiscal (NIF)',
  },

  fa: {
    // Top Modules
    'workspace': 'فضای کاری',
    'sales_control': '۱. مدیریت فروش و صندوق POS',
    'operations_center': '۲. مرکز عملیات و انبارداری',
    'purchases': '۳. خرید و تدارکات',
    'crm_debtors': '۴. مدیریت مشتریان و مطالبات (CRM)',
    'complaints_dashboard': '۵. شکایات و نظرسنجی‌ها',
    'loyalty_program': '۶. مدیریت باشگاه مشتریان',
    'accounting_finance': '۷. حسابداری و امور مالی',
    'hr_payroll': '۸. منابع انسانی و حقوق و دستمزد',
    'supersonic_fleet': '۹. مدیریت ناوگان و رانندگان V-Driver',
    'social_crm': '۱۰. مدیریت شبکه‌های اجتماعی V-Connect',
    'pressing_mill_nav': '۱۱. سیستم کارخانه روغن‌کشی',
    'olive_pressing': 'روغن‌کشی زیتون و تولید',
    'pressing_mill': 'روغن‌کشی زیتون',
    'oil_pressing_short': 'استخراج روغن',

    // Shared / Core
    'dashboard': 'داشبورد اصلی',
    'reports': 'گزارش‌ها',
    'reports_hub': 'مرکز گزارش‌ها',
    'online_orders': 'سفارش‌های آنلاین',
    'end_of_day': 'بستن روزانه (Z-Report)',
    'setup': 'تنظیمات و پیکربندی',
    'more_setup': 'تنظیمات بیشتر',
    'actions': 'عملیات و اقدامات',
    'settings': 'تنظیمات',
    'more': 'بیشتر',
    'cancel': 'انصراف',
    'save_changes': 'ذخیره تغییرات',
    'saving': 'در حال ذخیره‌سازی...',
    'search_menu': 'جستجو در منو و بخش‌ها...',
    'search_placeholder': 'جستجوی سریع در بخش‌ها و تراکنش‌ها...',
    'alerts': 'هشدارها',
    'exchange_rate': 'نرخ ارز',
    'system_active': 'سیستم فعال و آنلاین',
    'vanguard_system': 'سیستم Vanguard ERP',
    'all_rights_reserved': '© 2026 تمامی حقوق محفوظ است',
    'privacy_policy': 'حریم خصوصی',

    // Sales Control Sub-Items
    'pos_terminal': 'ترمینال صندوقدار POS',
    'pos_layout_config': 'تنظیمات صفحه صندوق',
    'screens': 'صفحه‌ها و پایانه‌های فروش',
    'payment_types': 'روش‌ها و انواع پرداخت',
    'coupons_vouchers': 'کوپن‌ها و تخفیف‌ها',
    'coupons_gift_cert': 'کوپن‌ها و کارت‌های هدیه',
    'discounts': 'تخفیف‌ها و سیاست‌های قیمت',
    'price_modes': 'سطوح و رده‌های قیمت‌گذاری',
    'workstations_printers': 'ایستگاه‌های کاری و چاپگرها',
    'void_reasons': 'دلایل ابطال فاکتور',
    'vat_exemptions': 'دلایل معافیت مالیاتی',
    'vat_exemption_reasons': 'دلایل معافیت مالیاتی',
    'invoice_message': 'پیام زیر فاکتور',
    'invoice_messages': 'پیام زیر فاکتور',
    'zone_setup': 'تنظیم مناطق و ارسال',
    'currency_setup': 'تنظیم ارزها و نرخ برابری',

    // Operations Center Sub-Items
    'sales': 'فروش',
    'quotations': 'پیش‌فاکتورها',
    'delivery_goods': 'حوالم‌های تحویل کالا',
    'purchase_orders': 'سفارش‌های خرید',
    'reorder_guide': 'راهنمای سفارش مجدد',
    'transfers': 'انتقال بین انبارها',
    'stock_transfer': 'انتقال بین انبارها',
    'lost_goods': 'کالاهای مفقودی و ضایعات',
    'lost_damaged_goods': 'کالاهای ضایعاتی و مفقودی',
    'item_assembly': 'مونتاژ و تفکیک کالاها',
    'bom_assembly': 'مونتاژ محصولات BOM',
    'adjustments': 'تعدیلات انبار',
    'inventory_adjustments': 'تعدیلات انبار',
    'product_request': 'درخواست کالا',
    'product_requests': 'درخواست‌های کالای داخلی',
    'manage_product_requests': 'مدیریت درخواست‌های کالا',
    'product_req_prep': 'آماده‌سازی درخواست‌های کالا',
    'receiving_goods': 'دریافت کالا',
    'product_req_reports': 'گزارش‌های درخواست کالا',
    'request_reject_reasons': 'دلایل رد درخواست',
    'events': 'رویدادها و مناسبت‌ها',
    'events_management': 'رویدادها و مناسبت‌ها',
    'event_venues': 'مکان‌های رویداد',
    'event_resources': 'منابع و تجهیزات رویداد',
    'event_types': 'انواع رویدادها',
    'quick_setup': 'راه‌اندازی سریع',
    'products_services': 'محصولات و خدمات',
    'product_groups': 'گروه‌های کالا',
    'groups': 'گروه‌ها',
    'divisions': 'بخش‌ها',
    'categories': 'دسته‌بندی‌های اصلی',
    'units': 'واحدهای سنجش',
    'uom_tanks': 'واحدهای سنجش و مخازن',
    'locations': 'انبارها و موقعیت‌ها',
    'warehouses_locations': 'انبارها و موقعیت‌ها',
    'suppliers': 'تامین‌کنندگان',
    'departments': 'دپارتمان‌ها',
    'lost_goods_reason': 'دلایل ضایعات کالا',
    'sizes_groups': 'گروه‌های سایز',
    'sizes': 'سایزها',
    'colors': 'رنگ‌ها',
    'inventory_brands': 'برندهای تجاری',
    'delivery_providers': 'شرکت‌های حمل و ارسال',

    // Purchasing Sub-Items
    'purchases_ap_bills': 'خریدها و فاکتورهای تامین‌کنندگان',
    'goods_receiving_grn': 'سندهای رسید انبار (GRN)',
    'suppliers_directory': 'دفترچه تامین‌کنندگان',
    'procurement_reports': 'گزارش‌های خرید و تامین',

    // Customer CRM Sub-Items
    'customer_directory': 'دفترچه حساب‌های مشتریان',
    'customers_directory': 'دفترچه مشتریان',
    'customer_receipts': 'رسیدهای دریافت مشتریان',
    'receipts_vouchers': 'رسیدهای دریافت وجه',
    'aged_debtors': 'تحلیل سن بدهی‌ها و مطالبات',
    'customer_aged_receivables': 'تحلیل سن مطالبات مشتریان',
    'customer_insights': 'تحلیل‌ها و هوش مشتریان AI',
    'ltv_insights': 'تحلیل ارزش طول عمر مشتری (LTV)',
    'tasks_appointments': 'وظایف و قرارهای ملاقات',
    'leads_opportunities': 'فرصت‌های فروش و لیدها',
    'sales_team_performance': 'عملکرد تیم فروش',
    'sales_rep_performance': 'عملکرد فروشندگان',
    'customers_groups': 'گروه‌های مشتریان',
    'customers_categories': 'دسته‌بندی‌های مشتریان',
    'customers_tags': 'برچسب‌های مشتریان',

    // Feedback Sub-Items
    'manage_complaints': 'مدیریت شکایات',
    'add_complaints': 'افزودن شکایت جدید',
    'manage_surveys': 'مدیریت نظرسنجی‌ها',
    'send_survey_emails': 'ارسال ایمیل نظرسنجی',
    'complaint_sources': 'منابع شکایات',
    'complaint_categories': 'دسته‌بندی‌های شکایات',
    'complaint_action_types': 'انواع اقدامات رسیدگی',
    'customer_care': 'پشتیبانی و مراقبت از مشتری',
    'surveys_setup': 'تنظیمات نظرسنجی',

    // Loyalty Sub-Items
    'members': 'اعضا و مشترکین',
    'loyalty_levels': 'سطوح باشگاه مشتریان',
    'loyalty_programs': 'برنامه‌های وفاداری و پاداش',
    'send_messages': 'ارسال پیام‌ها و آفرها',
    'company_info': 'اطلاعات شرکت و شعبه',

    // Accounting Sub-Items
    'chart_of_accounts': 'کدینگ حساب‌ها (COA)',
    'journal_voucher': 'سند حسابداری روزنامه (JV)',
    'journal_vouchers': 'اسناد حسابداری (JV)',
    'purchase': 'خرید و فاکتورها',
    'payments': 'پرداخت‌ها و اسناد هزینه',
    'receipts': 'رسیدهای دریافت وجه',
    'receivables': 'حساب‌های دریافتنی و بدهکاران',
    'payables': 'بدهی‌ها و بستانکاران (AP)',
    'payables_ap': 'بدهی‌ها و بستانکاران (AP)',
    'bank_reconciliation': 'مغایرت‌گیری بانکی',
    'vat_closing': 'بستن دوره مالیات ارزش افزوده TVA',
    'accounts': 'دفتر حساب‌ها',
    'account_auxiliaries': 'حساب‌های معین و کمکی',
    'aux_classes': 'طبقات و گروه‌های حساب‌ها',
    'aux_header1': 'سربرگ حساب سطح ۱',
    'aux_header2': 'سربرگ حساب سطح ۲',
    'aux_header3': 'سربرگ حساب سطح ۳',
    'aux_group': 'گروه حساب‌ها',
    'jv_description': 'شرح اسناد حسابداری',
    'jv_types': 'انواع اسناد حسابداری',
    'currency': 'ارزها',
    'currency_rates': 'نرخ‌های برابری ارز',
    'dept_groups': 'گروه‌های دپارتمان',
    'department': 'دپارتمان و مراکز هزینه',
    'cash_flow_setup': 'تنظیم جریان نقدینگی',
    'sub_department': 'زیردپارتمان',

    // HR Sub-Items
    'schedule_overview': 'نمای کلی برنامه‌ها',
    'personnel': 'پرسنل و کارکنان',
    'schedules': 'برنامه‌های کاری و شیفت‌ها',
    'organization_setup': 'ساختار سازمانی',
    'internal_departments': 'بخش‌های داخلی',
    'designations': 'عناوین و پست‌های شغلی',
    'pos_employee_roles': 'نقش‌های پرسنل صندوق',
    'time_attendance': 'زمان و حضور و غیاب',
    'time_off_requests': 'درخواست‌های مرخصی',
    'schedule_templates': 'الگوهای شیفت کاری',
    'time_off_reasons': 'دلایل مرخصی و غیبت',
    'attendance_summary': 'خلاصه حضور و غیاب',
    'attendance_log': 'گزارش تردد و ورود و خروج',
    'payroll': 'حقوق و دستمزد',
    'payroll_dashboard': 'داشبورد حقوق و دستمزد',
    'salary_processing': 'محاسبه و واریز حقوق',
    'payment_settings': 'تنظیمات پرداخت',
    'earnings_deductions': 'مزایا و کسورات',
    'employee_schedule': 'برنامه شیفت کاری',
    'employee_directory': 'دفترچه پرسنل',
    'payroll_management': 'حقوق و دستمزد',

    // Fleet Sub-Items
    'fleet_dashboard': 'داشبورد ناوگان',
    'fleet_reports': 'گزارش‌های ناوگان',
    'active_dispatches': 'ماموریت‌ها و بارهای فعال',
    'driver_management': 'مدیریت رانندگان',
    'route_optimization': 'بهینه‌سازی مسیرها',
    'vehicle_maintenance': 'سرویس و نگهداری خودروها',
    'driver_settlements': 'تسویه‌حساب رانندگان',
    'vtrack_geographics': 'ردیابی جغرافیایی V-Track',
    'gps_fleet_map': 'نقشه ردیابی زنده GPS',
    'km_odometer_logs': 'ثبت کیلومترشمار',
    'fuel_consumption': 'مصرف سوخت',
    'route_playback': 'بازپخش مسیر حرکت',
    'driver_directory': 'دفترچه رانندگان',

    // Social CRM Sub-Items
    'vconnect_hub': 'پلتفرم V-Connect',
    'social_crm_dashboard': 'داشبورد CRM شبکه‌های اجتماعی',
    'lead_pipeline_acquisition': 'قیف جذب سرنخ‌ها',
    'lead_pipeline_cpl': 'سرنخ‌ها و کمپین‌های CPL',
    'omnichannel_inbox': 'صندوق پیام‌های همه‌کاناله',
    'unified_inbox': 'صندوق پیام‌های یکپارچه',
    'platform_orders': 'سفارش‌های پلتفرم',
    'publishing_calendar': 'تقویم انتشار محتوا',
    'ad_campaigns': 'کمپین‌های تبلیغاتی',
    'support_agents': 'تیم پشتیبانی',
    'distributors': 'توزیع‌کنندگان',
    'distributors_directory': 'دفترچه توزیع‌کنندگان',
    'campaign_analytics': 'تحلیل کمپین‌ها',
    'automation_bots': 'ربات‌های خودکارسازی',
    'wholesale_sales': 'فروش عمده',

    // Pressing Mill Sub-Items
    'pm_dashboard': 'داشبورد عملیات',
    'pm_seasons': 'مدیریت فصول و دوره‌ها',
    'pm_intake': 'باسکول و دریافت زیتون',
    'pm_batches': 'خطوط استخراج و دسته‌ها',
    'pm_tanks': 'ماتریس مخازن (۱-۵۰)',
    'pm_settlements': 'تسویه‌حساب و دستمزد',
    'pm_dispatch': 'تحویل روغن و خروج',
    'pm_pos': 'صندوق فروش مستقیم و POS',
    'pm_directory': 'دفتر حساب کشاورزان',
    'pm_setup': 'تنظیمات خطوط و کارخانه',
    'in_kind_retention': 'رد روغن (درصد روغن)',
    'cash_fee': 'دستمزد نقدی',
    'mixed_settlement': 'تسویه ترکیبی',
    'gross_weight': 'وزن ناخالص',
    'tare_weight': 'وزن خالی (تار)',
    'net_weight': 'وزن خالص زیتون',
    'acidity_pct': 'درصد اسیدیته',
    'yield_pct': 'درصد بازدهی',

    // V-Store Sub-Items & Footer
    'customer_storefront': 'فروشگاه اینترنتی مشتریان',
    'identity_settings': 'مشخصات و تنظیمات سیستم',
    'license_certificate': 'گواهینامه مجوز نرم‌افزار',

    // Global Header & Account
    'organization': 'مشخصات سازمان و شرکت',
    'users': 'مدیریت کاربران',
    'roles': 'نقش‌ها و دسترسی‌ها',
    'my_account': 'حساب کاربری من',
    'language': 'زبان',
    'support_center': 'مرکز پشتیبانی و راهنما',
    'feedback': 'نظرات و پیشنهادات',
    'logout': 'خروج از سیستم',
    'latest_updates': 'آخرین بروزرسانی‌ها',
    'notifications_inbox': 'اعلان‌ها و صندوق پیام',
    'grid_dashboard': 'داشبورد شبکه‌ای',
    'recently_visited': 'بازدیدهای اخیر',
    'end_of_month': 'بستن ماهانه',
    'tenant_identity_settings': 'تنظیمات برند و مجوز',
    'tenant_profile_title': 'تنظیمات هویت شرکت و اطلاعات قانونی',
    'tenant_profile_subtitle': 'ویرایش نام رسمی، لوگو، شماره ثبت تجاری و شناسه مالیاتی.',
    'brand_identity': '۱. هویت برند و لوگوی رسمی',
    'company_name_ar': 'نام شرکت (عربی/فارسی)',
    'company_name_en': 'نام برند تجاری (انگلیسی)',
    'logo_url': 'آدرس اینترنتی لوگو',
    'add_picture': 'افزودن تصویر',
    'click_to_upload': 'کلیک برای بارگذاری',
    'legal_registration': '۲. شماره‌های ثبت قانونی',
    'commercial_reg': 'شماره ثبت تجاری (CR)',
    'tax_id': 'شناسه مالیاتی (MOF)',
  },

  // Extended World Languages - Core Starter Dictionaries (Falls back gracefully to English)
  de: {
    'dashboard': 'Dashboard',
    'reports': 'Berichte',
    'reports_hub': 'Berichtszentrum',
    'online_orders': 'Online-Bestellungen',
    'end_of_day': 'Tagesabschluss',
    'setup': 'Einrichtung',
    'purchases': 'Einkauf & Beschaffung',
    'purchase_orders': 'Bestellungen',
    'reorder_guide': 'Nachbestellhilfe',
    'actions': 'Aktionen',
    'settings': 'Einstellungen',
    'search_menu': 'Menü durchsuchen...',
    'logout': 'Abmelden',
  },
  tr: {
    'dashboard': 'Kontrol Paneli',
    'reports': 'Raporlar',
    'reports_hub': 'Rapor Merkezi',
    'online_orders': 'Çevrimiçi Siparişler',
    'end_of_day': 'Gün Sonu Kapanışı',
    'setup': 'Yapılandırma',
    'purchases': 'Satın Alma & Tedarik',
    'purchase_orders': 'Satın Alma Siparişleri',
    'reorder_guide': 'Yeniden Sipariş Kılavuzu',
    'actions': 'İşlemler',
    'settings': 'Ayarlar',
    'search_menu': 'Menüde ara...',
    'logout': 'Çıkış Yap',
  },
  it: {
    'dashboard': 'Cruscotto',
    'reports': 'Rapporti',
    'reports_hub': 'Centro Rapporti',
    'online_orders': 'Ordini Online',
    'end_of_day': 'Chiusura Giornaliera',
    'setup': 'Configurazione',
    'purchases': 'Acquisti & Approvvigionamento',
    'purchase_orders': 'Ordini di Acquisto',
    'reorder_guide': 'Guida al Riordino',
    'actions': 'Azioni',
    'settings': 'Impostazioni',
    'search_menu': 'cerca nel menu...',
    'logout': 'Disconnettersi',
  },
  pt: {
    'dashboard': 'Painel de Controle',
    'reports': 'Relatórios',
    'reports_hub': 'Central de Relatórios',
    'online_orders': 'Pedidos Online',
    'end_of_day': 'Fechamento do Dia',
    'setup': 'Configurações',
    'purchases': 'Compras & Suprimentos',
    'purchase_orders': 'Ordens de Compra',
    'reorder_guide': 'Guia de Reposição',
    'actions': 'Ações',
    'settings': 'Definições',
    'search_menu': 'pesquisar no menu...',
    'logout': 'Sair',
  },
  ru: {
    'dashboard': 'Панель управления',
    'reports': 'Отчеты',
    'reports_hub': 'Центр отчетов',
    'online_orders': 'Онлайн заказы',
    'end_of_day': 'Закрытие смены',
    'setup': 'Настройка',
    'purchases': 'Закупки и снабжение',
    'purchase_orders': 'Заказы на закупку',
    'reorder_guide': 'Руководство дозаказа',
    'actions': 'Действия',
    'settings': 'Настройки',
    'search_menu': 'поиск в меню...',
    'logout': 'Выйти',
  },
  zh: {
    'dashboard': '控制面板',
    'reports': '报表中心',
    'reports_hub': '综合报表中心',
    'online_orders': '线上订单',
    'end_of_day': '日结结算',
    'setup': '系统设置',
    'purchases': '采购与供应链',
    'purchase_orders': '采购订单',
    'reorder_guide': '补货指南',
    'actions': '操作菜单',
    'settings': '设置',
    'search_menu': '搜索菜单...',
    'logout': '退出登录',
  }
};

export interface LanguageProviderProps {
  children: React.ReactNode;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');
  const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr');

  // Initialize language from localStorage on client mount
  useEffect(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = localStorage.getItem('vanguard_language') as LanguageCode;
        if (saved && ALL_LANGUAGES.some(l => l.code === saved)) {
          setLanguageState(saved);
          const newDir = isRTL(saved) ? 'rtl' : 'ltr';
          setDir(newDir);
          document.documentElement.dir = newDir;
          document.documentElement.lang = saved;
        }
      } catch (e) {
        console.warn('Failed to load language preference:', e);
      }
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    const newDir = isRTL(lang) ? 'rtl' : 'ltr';
    setDir(newDir);

    if (typeof window !== 'undefined') {
      try {
        localStorage.setItem('vanguard_language', lang);
      } catch (e) {
        console.warn('Failed to persist language preference:', e);
      }
      document.documentElement.dir = newDir;
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.dir = dir;
      document.documentElement.lang = language;
    }
  }, [dir, language]);

  const t = (key: string, fallbackEn?: string): string => {
    const langMap = translations[language];
    if (langMap && langMap[key]) {
      return langMap[key];
    }
    // Fallback to English dictionary
    if (translations['en']?.[key]) {
      return translations['en'][key];
    }
    // Fallback to provided fallbackEn or key
    return fallbackEn || key;
  };

  const contextValue: LanguageContextType = {
    language,
    dir,
    direction: dir,
    isRtl: dir === 'rtl',
    setLanguage,
    t,
    languages: ALL_LANGUAGES,
    pinnedLanguages: PINNED_LANGUAGES,
    extendedLanguages: EXTENDED_LANGUAGES,
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      <div dir={dir} className="w-full min-h-screen">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      dir: 'ltr',
      direction: 'ltr',
      isRtl: false,
      setLanguage: () => {},
      t: (key: string, fallbackEn?: string) => fallbackEn || key,
      languages: ALL_LANGUAGES,
      pinnedLanguages: PINNED_LANGUAGES,
      extendedLanguages: EXTENDED_LANGUAGES,
    };
  }
  return context;
};
