'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'ar' | 'fr' | 'es' | 'fa';

export interface LanguageContextType {
  language: LanguageCode;
  dir: 'ltr' | 'rtl';
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallbackEn?: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    'workspace': 'Workspace',
    'sales_control': 'Sales Control & POS',
    'supersonic_fleet': 'SuperSonic Fleet Management',
    'social_crm': 'Social Media CRM',
    'operations_center': 'Operations & Pressing Center',
    'olive_pressing': 'Olive Pressing & Production',
    'crm_debtors': 'Customer Management & AR',
    'accounting_finance': 'Accounting & Finance',
    'hr_payroll': 'HR & Payroll',
    'dashboard': 'Dashboard',
    'pos_terminal': 'POS Cashier Terminal',
    'reports': 'Reports',
    'online_orders': 'Online Orders',
    'end_of_day': 'End of Day Z-Report',
    'pos_layout_config': 'POS Screen Config',
    'payment_types': 'Payment Types',
    'coupons_vouchers': 'Coupons & Vouchers',
    'discounts': 'Discounts',
    'price_modes': 'Price Modes',
    'workstations_printers': 'Workstations & Printers',
    'void_reasons': 'Void Reasons',
    'vat_exemption_reasons': 'VAT Exemption Reasons',
    'invoice_message': 'Invoice Message',
    'zone_setup': 'Zone Setup',
    'currency_setup': 'Currency Setup',
    'gps_fleet_map': 'Live GPS Fleet Map',
    'km_odometer_logs': 'KM & Odometer Logs',
    'fuel_consumption': 'Fuel Consumption',
    'vehicle_maintenance': 'Vehicle Maintenance',
    'route_playback': 'Route Playback',
    'driver_directory': 'Drivers Directory',
    'unified_inbox': 'Unified Social Inbox',
    'platform_orders': 'Platform Orders',
    'publishing_calendar': 'Publishing Calendar',
    'ad_campaigns': 'Ad Campaigns',
    'support_agents': 'Support Agents',
    'distributors_directory': 'Distributors Directory',
    'wholesale_sales': 'Wholesale Sales',
    'quotations': 'Quotations',
    'delivery_goods': 'Delivery of Goods',
    'purchases': 'Purchases',
    'purchase_orders': 'Purchase Orders',
    'reorder_guide': 'Reorder Guide',
    'stock_transfer': 'Stock Transfer',
    'lost_damaged_goods': 'Lost & Damaged Goods',
    'bom_assembly': 'BOM Assembly',
    'inventory_adjustments': 'Inventory Adjustments',
    'product_requests': 'Product Requests',
    'events_management': 'Events & Occasions',
    'quick_setup': 'Quick Setup',
    'products_services': 'Products & Services',
    'product_groups': 'Product Groups',
    'categories': 'Categories',
    'uom_tanks': 'Units of Measure & Tanks',
    'warehouses_locations': 'Warehouses & Locations',
    'suppliers_directory': 'Suppliers Directory',
    'customer_directory': 'Customer Accounts Directory',
    'receipts_vouchers': 'Receipt Vouchers',
    'aged_debtors': 'Aged Debtors Analysis',
    'ltv_insights': 'Customer LTV Insights',
    'tasks_appointments': 'Tasks & Appointments',
    'leads_opportunities': 'Leads & Opportunities',
    'sales_rep_performance': 'Sales Rep Performance',
    'complaints_dashboard': 'Complaints & Surveys',
    'loyalty_program': 'Loyalty & Rewards',
    'chart_of_accounts': 'Chart of Accounts (COA)',
    'journal_vouchers': 'Journal Vouchers (JV)',
    'payables_ap': 'Accounts Payable (AP)',
    'bank_reconciliation': 'Bank Reconciliation',
    'vat_closing': 'VAT Tax Closing',
    'employee_schedule': 'Employee Schedule',
    'employee_directory': 'Employee Directory',
    'payroll_management': 'Payroll Management',
    'recently_visited': 'Recently Visited',
    'end_of_month': 'End of Month',
    'alerts': 'Alerts',
    'exchange_rate': 'Exchange Rate',
    'search_placeholder': 'Quick search in screens & transactions...',
    'grid_dashboard': 'Grid Dashboard',
    'oil_pressing_short': 'Oil Pressing',
    'system_active': 'System Active & Online',
    'tenant_identity_settings': 'Identity & License Settings',
    'vanguard_system': 'Vanguard ERP System',
    'all_rights_reserved': '© 2026 All Rights Reserved',
    'privacy_policy': 'Privacy Policy',
    'tenant_profile_title': 'Company Identity & Legal Settings',
    'tenant_profile_subtitle': 'Edit official name, logo, commercial registration, and tax ID.',
    'brand_identity': '1. Brand Identity & Official Logo',
    'company_name_ar': 'Company Name (Arabic)',
    'company_name_en': 'Enterprise Brand Name (English)',
    'logo_url': 'External Logo Image URL',
    'add_picture': 'Add Picture',
    'click_to_upload': 'Click to upload photo',
    'legal_registration': '2. Legal Registration Numbers',
    'commercial_reg': 'Commercial Registration No. (CR)',
    'tax_id': 'Tax Identification Number (MOF)',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'saving': 'Saving Changes...'
  },
  ar: {
    'workspace': 'مساحة العمل',
    'sales_control': 'إدارة المبيعات ونقطة البيع',
    'supersonic_fleet': 'أسطول الشحن والسيارات',
    'social_crm': 'التواصل الاجتماعي والدعم',
    'operations_center': 'مركز العمليات والمعاصر',
    'olive_pressing': 'عصر الزيتون والإنتاج',
    'crm_debtors': 'إدارة العملاء والذمم',
    'accounting_finance': 'المحاسبة والمالية',
    'hr_payroll': 'الموارد البشرية والرواتب',
    'dashboard': 'لوحة التحكم',
    'pos_terminal': 'نقطة البيع الكاشير',
    'reports': 'التقارير المالية والتشغيلية',
    'online_orders': 'طلبات المتجر الإلكتروني',
    'end_of_day': 'تقرير إغلاق اليوم Z-Report',
    'pos_layout_config': 'تنسيق شاشات الكاشير',
    'payment_types': 'أنواع وطرق الدفع',
    'coupons_vouchers': 'الكوبونات وقسائم الخصم',
    'discounts': 'سياسات وتخفيضات الأسعار',
    'price_modes': 'أنماط وشرايح الأسعار',
    'workstations_printers': 'محطات العمل والطابعات',
    'void_reasons': 'أسباب إلغاء الفواتير',
    'vat_exemption_reasons': 'أسباب الإعفاء الضريبي',
    'invoice_message': 'رسالة أسفل الفاتورة',
    'zone_setup': 'إعداد المناطق والتوصيل',
    'currency_setup': 'إعداد العملات وسعر الصرف',
    'gps_fleet_map': 'خريطة التتبع المباشر GPS',
    'km_odometer_logs': 'سجل عدادات الكيلومترات',
    'fuel_consumption': 'متابعة استهلاك المحروقات',
    'vehicle_maintenance': 'صيانة ومعاينة السيارات',
    'route_playback': 'إعادة تشغيل مسار الرحلات',
    'driver_directory': 'دليل السائقين والمندوبين',
    'unified_inbox': 'صندوق الرسائل الموحد',
    'platform_orders': 'طلبات المنصات الذكية',
    'publishing_calendar': 'تقويم المنشورات والحملات',
    'ad_campaigns': 'إدارات الحملات الإعلانية',
    'support_agents': 'فريق الدعم الفني',
    'distributors_directory': 'دليل الموزعين والتجار',
    'wholesale_sales': 'مبيعات الجملة والبراميل',
    'quotations': 'عروض الأسعار والتخمين',
    'delivery_goods': 'إرساليات تسليم البضائع',
    'purchases': 'المشتريات والتوريد',
    'purchase_orders': 'أوامر الشراء للموردين',
    'reorder_guide': 'دليل إعادة الطلب التلقائي',
    'stock_transfer': 'مناقلات بين المستودعات',
    'lost_damaged_goods': 'سجل التالف والمفقودات',
    'bom_assembly': 'تجميع المنتجات BOM',
    'inventory_adjustments': 'تسوية الجرد المخزني',
    'product_requests': 'طلبات المنتجات الداخلية',
    'events_management': 'المناسبات والفعاليات',
    'quick_setup': 'الإعداد السريع للنظام',
    'products_services': 'المنتجات والخدمات',
    'product_groups': 'مجموعات المنتجات',
    'categories': 'فئات المنتجات الرئيسية',
    'uom_tanks': 'وحدات القياس والخزانات',
    'warehouses_locations': 'المستودعات والمواقع',
    'suppliers_directory': 'دليل الموردين والشركات',
    'customer_directory': 'دليل حسابات العملاء',
    'receipts_vouchers': 'سندات القبض المالية',
    'aged_debtors': 'تحليل أعمار الديون والذمم',
    'ltv_insights': 'تحليلات القيمة الممتدة LTV',
    'tasks_appointments': 'المهام والمواعيد',
    'leads_opportunities': 'الفرص والعملاء المحتملين',
    'sales_rep_performance': 'أداء مندوبي المبيعات',
    'complaints_dashboard': 'الشكاوى واستطلاعات الرأي',
    'loyalty_program': 'برنامج الولاء المكافآت',
    'chart_of_accounts': 'دليل الحسابات COA',
    'journal_vouchers': 'سندات القيد اليومية JV',
    'payables_ap': 'حسابات الموردين AP',
    'bank_reconciliation': 'مطابقة الحسابات البنكية',
    'vat_closing': 'الإقرار وإغلاق TVA الضريبي',
    'employee_schedule': 'جدول المناوبات والدوام',
    'employee_directory': 'سجل الموظفين والكادر',
    'payroll_management': 'مسير الرواتب والأجور',
    'recently_visited': 'الزيارات الأخيرة',
    'end_of_month': 'إغلاق الشهر',
    'alerts': 'التنبيهات',
    'exchange_rate': 'سعر الصرف',
    'search_placeholder': 'بحث سريع في الشاشات والعمليات...',
    'grid_dashboard': 'لوحة الشبكة الرئيسية',
    'oil_pressing_short': 'عصر الزيتون',
    'system_active': 'النظام يعمل ومتصل بالإنترنت',
    'tenant_identity_settings': 'إعدادات الشعار والترخيص',
    'vanguard_system': 'نظام Vanguard ERP',
    'all_rights_reserved': '© 2026 جميع الحقوق محفوظة',
    'privacy_policy': 'سياسة الخصوصية',
    'tenant_profile_title': 'إعدادات هوية المؤسسة والبيانات القانونية',
    'tenant_profile_subtitle': 'تعديل الاسم والشعار الرسمي وتضمين رقم السجل التجاري والرقم المالي.',
    'brand_identity': '1. الاسم التجاري والشعار الرسمي',
    'company_name_ar': 'اسم الشركة / المؤسسة (بالعربي)',
    'company_name_en': 'Enterprise Brand Name (English)',
    'logo_url': 'رابط الشعار الخارجي',
    'add_picture': 'إضافة صورة',
    'click_to_upload': 'انقر لتحميل صورة',
    'legal_registration': '2. البيانات القانونية والترخيص',
    'commercial_reg': 'رقم السجل التجاري (CR)',
    'tax_id': 'الرقم المالي (MOF)',
    'cancel': 'إلغاء',
    'save_changes': 'حفظ التغييرات',
    'saving': 'جاري الحفظ...'
  },
  fr: {
    'workspace': 'Espace de Travail',
    'sales_control': 'Gestion des Ventes & POS',
    'supersonic_fleet': 'Gestion de Flotte SuperSonic',
    'social_crm': 'CRM Réseaux Sociaux & Support',
    'operations_center': 'Centre d\'Opérations & Pressage',
    'olive_pressing': 'Pressage d\'Olives & Production',
    'crm_debtors': 'Gestion Clients & Créances',
    'accounting_finance': 'Comptabilité & Finance',
    'hr_payroll': 'RH & Paie',
    'dashboard': 'Tableau de Bord',
    'pos_terminal': 'Terminal Caisse POS',
    'reports': 'Rapports Financiers & Opérationnels',
    'online_orders': 'Commandes en Ligne',
    'end_of_day': 'Rapport de Clôture Z-Report',
    'pos_layout_config': 'Configuration Écrans POS',
    'payment_types': 'Modes de Paiement',
    'coupons_vouchers': 'Coupons & Bons',
    'discounts': 'Remises & Tarifs',
    'price_modes': 'Grilles Tarifaires',
    'workstations_printers': 'Postes & Imprimantes',
    'void_reasons': 'Motifs d\'Annulation',
    'vat_exemption_reasons': 'Motifs d\'Exonération TVA',
    'invoice_message': 'Message de Facture',
    'zone_setup': 'Zones de Livraison',
    'currency_setup': 'Devises & Taux de Change',
    'gps_fleet_map': 'Carte GPS en Direct',
    'km_odometer_logs': 'Relevés Kilométriques',
    'fuel_consumption': 'Consommation de Carburant',
    'vehicle_maintenance': 'Entretien des Véhicules',
    'route_playback': 'Historique des Trajets',
    'driver_directory': 'Annuaire Chauffeurs',
    'unified_inbox': 'Boîte de Réception Unique',
    'platform_orders': 'Commandes Plateformes',
    'publishing_calendar': 'Calendrier de Publication',
    'ad_campaigns': 'Campagnes Publicitaires',
    'support_agents': 'Agents de Support',
    'distributors_directory': 'Annuaire Distributeurs',
    'wholesale_sales': 'Ventes en Gros',
    'quotations': 'Devis & Estimations',
    'delivery_goods': 'Bons de Livraison',
    'purchases': 'Achats & Approvisionnement',
    'purchase_orders': 'Commandes Fournisseurs',
    'reorder_guide': 'Guide de Réapprovisionnement',
    'stock_transfer': 'Transferts de Stock',
    'lost_damaged_goods': 'Pertes & Dommages',
    'bom_assembly': 'Assemblage Nomenclature BOM',
    'inventory_adjustments': 'Ajustements de Stock',
    'product_requests': 'Demandes de Produits',
    'events_management': 'Événements & Occasions',
    'quick_setup': 'Configuration Rapide',
    'products_services': 'Produits & Services',
    'product_groups': 'Groupes de Produits',
    'categories': 'Catégories',
    'uom_tanks': 'Unités de Mesure & Cuves',
    'warehouses_locations': 'Entrepôts & Emplacements',
    'suppliers_directory': 'Annuaire Fournisseurs',
    'customer_directory': 'Annuaire Comptes Clients',
    'receipts_vouchers': 'Bons de Recette',
    'aged_debtors': 'Analyse de Créances',
    'ltv_insights': 'Analyse LTV Clients',
    'tasks_appointments': 'Tâches & Rendez-vous',
    'leads_opportunities': 'Pistes & Opportunités',
    'sales_rep_performance': 'Performance Commerciale',
    'complaints_dashboard': 'Réclamations & Sondages',
    'loyalty_program': 'Programme de Fidélité',
    'chart_of_accounts': 'Plan Comptable (COA)',
    'journal_vouchers': 'Écritures Comptables (JV)',
    'payables_ap': 'Comptes Fournisseurs (AP)',
    'bank_reconciliation': 'Rapprochement Bancaire',
    'vat_closing': 'Déclaration TVA',
    'employee_schedule': 'Planning Employés',
    'employee_directory': 'Annuaire Personnel',
    'payroll_management': 'Gestion de Paie',
    'recently_visited': 'Récemment Visités',
    'end_of_month': 'Clôture Mensuelle',
    'alerts': 'Alertes',
    'exchange_rate': 'Taux de Change',
    'search_placeholder': 'Recherche rapide dans le système...',
    'grid_dashboard': 'Tableau de Bord Grille',
    'oil_pressing_short': 'Pressage Oléicole',
    'system_active': 'Système Actif & En Ligne',
    'tenant_identity_settings': 'Identité & Licence',
    'vanguard_system': 'Système Vanguard ERP',
    'all_rights_reserved': '© 2026 Tous Droits Réservés',
    'privacy_policy': 'Politique de Confidentialité',
    'tenant_profile_title': 'Identité d\'Entreprise & Mentions Légales',
    'tenant_profile_subtitle': 'Modifier le nom officiel, le logo, le registre du commerce et l\'ID fiscal.',
    'brand_identity': '1. Identité de Marque & Logo Officiel',
    'company_name_ar': 'Nom de la Société (Arabe)',
    'company_name_en': 'Nom de la Marque (Anglais)',
    'logo_url': 'URL du Logo Externe',
    'add_picture': 'Ajouter une Image',
    'click_to_upload': 'Cliquer pour télécharger',
    'legal_registration': '2. Numéros d\'Immatriculation Légale',
    'commercial_reg': 'Registre du Commerce (RC)',
    'tax_id': 'Numéro d\'Identification Fiscale (NIF)',
    'cancel': 'Annuler',
    'save_changes': 'Enregistrer les Modifications',
    'saving': 'Enregistrement...'
  },
  es: {
    'workspace': 'Espacio de Trabajo',
    'sales_control': 'Control de Ventas y TPV',
    'supersonic_fleet': 'Gestión de Flota SuperSonic',
    'social_crm': 'CRM Redes Sociales y Soporte',
    'operations_center': 'Centro de Operaciones y Prensado',
    'olive_pressing': 'Prensado de Aceitunas y Producción',
    'crm_debtors': 'Gestión de Clientes y Cuentas',
    'accounting_finance': 'Contabilidad y Finanzas',
    'hr_payroll': 'RRHH y Nóminas',
    'dashboard': 'Panel de Control',
    'pos_terminal': 'Terminal Caja TPV',
    'reports': 'Informes Financieros y Operativos',
    'online_orders': 'Pedidos en Línea',
    'end_of_day': 'Informe Cierre Z-Report',
    'pos_layout_config': 'Configuración Pantallas TPV',
    'payment_types': 'Métodos de Pago',
    'coupons_vouchers': 'Cupones y Vouchers',
    'discounts': 'Descuentos y Tarifas',
    'price_modes': 'Modos de Precios',
    'workstations_printers': 'Estaciones e Impresoras',
    'void_reasons': 'Motivos de Anulación',
    'vat_exemption_reasons': 'Exenciones de IVA',
    'invoice_message': 'Mensaje en Factura',
    'zone_setup': 'Zonas de Envío',
    'currency_setup': 'Monedas y Tipo de Cambio',
    'gps_fleet_map': 'Mapa GPS en Vivo',
    'km_odometer_logs': 'Registros de Kilometraje',
    'fuel_consumption': 'Consumo de Combustible',
    'vehicle_maintenance': 'Mantenimiento de Vehículos',
    'route_playback': 'Historial de Rutas',
    'driver_directory': 'Directorio de Conductores',
    'unified_inbox': 'Bandeja Social Unificada',
    'platform_orders': 'Pedidos de Plataforma',
    'publishing_calendar': 'Calendario de Publicación',
    'ad_campaigns': 'Campañas Publicitarias',
    'support_agents': 'Agentes de Soporte',
    'distributors_directory': 'Directorio de Distribuidores',
    'wholesale_sales': 'Ventas al Por Mayor',
    'quotations': 'Presupuestos y Cotizaciones',
    'delivery_goods': 'Albaranes de Entrega',
    'purchases': 'Compras y Suministros',
    'purchase_orders': 'Órdenes de Compra',
    'reorder_guide': 'Guía de Reaprovisionamiento',
    'stock_transfer': 'Transferencia de Stock',
    'lost_damaged_goods': 'Bajas y Daños',
    'bom_assembly': 'Ensamblaje Lista BOM',
    'inventory_adjustments': 'Ajustes de Inventario',
    'product_requests': 'Solicitudes de Productos',
    'events_management': 'Eventos y Ocasiones',
    'quick_setup': 'Configuración Rápida',
    'products_services': 'Productos y Servicios',
    'product_groups': 'Grupos de Productos',
    'categories': 'Categorías',
    'uom_tanks': 'Unidades de Medida y Tanques',
    'warehouses_locations': 'Almacenes y Ubicaciones',
    'suppliers_directory': 'Directorio de Proveedores',
    'customer_directory': 'Directorio Cuentas de Clientes',
    'receipts_vouchers': 'Comprobantes de Ingreso',
    'aged_debtors': 'Análisis de Deuda',
    'ltv_insights': 'Análisis LTV Clientes',
    'tasks_appointments': 'Tareas y Citas',
    'leads_opportunities': 'Oportunidades de Venta',
    'sales_rep_performance': 'Rendimiento de Vendedores',
    'complaints_dashboard': 'Reclamaciones y Encuestas',
    'loyalty_program': 'Programa de Fidelización',
    'chart_of_accounts': 'Plan de Cuentas (COA)',
    'journal_vouchers': 'Asientos Contables (JV)',
    'payables_ap': 'Cuentas por Pagar (AP)',
    'bank_reconciliation': 'Conciliación Bancaria',
    'vat_closing': 'Declaración de IVA',
    'employee_schedule': 'Turnos de Empleados',
    'employee_directory': 'Directorio de Personal',
    'payroll_management': 'Gestión de Nóminas',
    'recently_visited': 'Visitados Recientemente',
    'end_of_month': 'Cierre Mensual',
    'alerts': 'Alertas',
    'exchange_rate': 'Tipo de Cambio',
    'search_placeholder': 'Búsqueda rápida en el sistema...',
    'grid_dashboard': 'Panel Cuadrícula',
    'oil_pressing_short': 'Prensado de Aceite',
    'system_active': 'Sistema Activo y En Línea',
    'tenant_identity_settings': 'Identidad y Licencia',
    'vanguard_system': 'Sistema Vanguard ERP',
    'all_rights_reserved': '© 2026 Todos los Derechos Reservados',
    'privacy_policy': 'Política de Privacidad',
    'tenant_profile_title': 'Identidad de la Empresa y Registro Legal',
    'tenant_profile_subtitle': 'Editar nombre oficial, logotipo, registro comercial e ID fiscal.',
    'brand_identity': '1. Identidad de Marca y Logotipo',
    'company_name_ar': 'Nombre de la Empresa (Árabe)',
    'company_name_en': 'Nombre de Marca (Inglés)',
    'logo_url': 'URL del Logotipo Externo',
    'add_picture': 'Agregar Imagen',
    'click_to_upload': 'Hacer clic para subir',
    'legal_registration': '2. Registro Legal y Licencia',
    'commercial_reg': 'Registro Mercantil (CR)',
    'tax_id': 'Número de Identificación Fiscal (NIF)',
    'cancel': 'Cancelar',
    'save_changes': 'Guardar Cambios',
    'saving': 'Guardando...'
  },
  fa: {
    'workspace': 'فضای کاری',
    'sales_control': 'مدیریت فروش و صندوق POS',
    'supersonic_fleet': 'مدیریت ناوگان حمل و نقل',
    'social_crm': 'پشتیبانی و شبکه‌های اجتماعی',
    'operations_center': 'مرکز عملیات و روغن‌کشی',
    'olive_pressing': 'روغن‌کشی زیتون و تولید',
    'crm_debtors': 'مدیریت مشتریان و مطالبات',
    'accounting_finance': 'حسابداری و امور مالی',
    'hr_payroll': 'منابع انسانی و حقوق و دستمزد',
    'dashboard': 'داشبورد اصلی',
    'pos_terminal': 'ترمینال صندوقدار POS',
    'reports': 'گزارش‌های مالی و عملیاتی',
    'online_orders': 'سفارش‌های فروشگاه آنلاین',
    'end_of_day': 'گزارش بستن روزانه Z-Report',
    'pos_layout_config': 'تنظیمات صفحه صندوق',
    'payment_types': 'روش‌های پرداخت',
    'coupons_vouchers': 'کوپن‌ها و تخفیف‌ها',
    'discounts': 'تخفیف‌ها و سیاست‌های قیمت‌گذاری',
    'price_modes': 'سطوح قیمت‌گذاری',
    'workstations_printers': 'ایستگاه‌های کاری و چاپگرها',
    'void_reasons': 'دلایل ابطال فاکتور',
    'vat_exemption_reasons': 'دلایل معافیت مالیاتی',
    'invoice_message': 'پیام زیر فاکتور',
    'zone_setup': 'تنظیم مناطق و ارسال',
    'currency_setup': 'تنظیم ارزها و نرخ برابری',
    'gps_fleet_map': 'نقشه ردیابی زنده GPS',
    'km_odometer_logs': 'ثبت کیلومترشمار',
    'fuel_consumption': 'مصرف سوخت',
    'vehicle_maintenance': 'سرویس و نگهداری خودروها',
    'route_playback': 'بازپخش مسیر حرکت',
    'driver_directory': 'دفترچه رانندگان',
    'unified_inbox': 'صندوق پیام‌های یکپارچه',
    'platform_orders': 'سفارش‌های پلتفرم',
    'publishing_calendar': 'تقویم انتشار محتوا',
    'ad_campaigns': 'کمپین‌های تبلیغاتی',
    'support_agents': 'تیم پشتیبانی',
    'distributors_directory': 'دفترچه توزیع‌کنندگان',
    'wholesale_sales': 'فروش عمده',
    'quotations': 'پیش‌فاکتورها',
    'delivery_goods': 'حوالم‌های تحویل کالا',
    'purchases': 'خرید و تامین',
    'purchase_orders': 'سفارش‌های خرید',
    'reorder_guide': 'راهنمای سفارش مجدد',
    'stock_transfer': 'انتقال بین انبارها',
    'lost_damaged_goods': 'کالاهای ضایعاتی و مفقودی',
    'bom_assembly': 'مونتاژ محصولات BOM',
    'inventory_adjustments': 'تعدیلات انبار',
    'product_requests': 'درخواست‌های کالای داخلی',
    'events_management': 'رویدادها و مناسبت‌ها',
    'quick_setup': 'راه‌اندازی سریع',
    'products_services': 'محصولات و خدمات',
    'product_groups': 'گروه‌های کالا',
    'categories': 'دسته‌بندی‌های اصلی',
    'uom_tanks': 'واحدهای سنجش و مخازن',
    'warehouses_locations': 'انبارها و موقعیت‌ها',
    'suppliers_directory': 'دفترچه تامین‌کنندگان',
    'customer_directory': 'دفترچه حساب‌های مشتریان',
    'receipts_vouchers': 'رسیدهای دریافت وجه',
    'aged_debtors': 'تحلیل سن بدهی‌ها',
    'ltv_insights': 'تحلیل ارزش طول عمر مشتری (LTV)',
    'tasks_appointments': 'وظایف و قرارهای ملاقات',
    'leads_opportunities': 'فرصت‌های فروش',
    'sales_rep_performance': 'عملکرد فروشندگان',
    'complaints_dashboard': 'شکایات و نظرسنجی‌ها',
    'loyalty_program': 'باشگاه مشتریان و پاداش‌ها',
    'chart_of_accounts': 'کدینگ حساب‌ها (COA)',
    'journal_vouchers': 'اسناد حسابداری (JV)',
    'payables_ap': 'بدهی‌ها و بستانکاران (AP)',
    'bank_reconciliation': 'مغایرت‌گیری بانکی',
    'vat_closing': 'اظهارنامه ارزش افزوده TVA',
    'employee_schedule': 'برنامه شیفت کاری',
    'employee_directory': 'دفترچه پرسنل',
    'payroll_management': 'حقوق و دستمزد',
    'recently_visited': 'بازدیدهای اخیر',
    'end_of_month': 'بستن ماهانه',
    'alerts': 'هشدارها',
    'exchange_rate': 'نرخ ارز',
    'search_placeholder': 'جستجوی سریع در بخش‌ها و تراکنش‌ها...',
    'grid_dashboard': 'داشبورد شبکه‌ای',
    'oil_pressing_short': 'استخراج روغن',
    'system_active': 'سیستم فعال و آنلاین',
    'tenant_identity_settings': 'تنظیمات برند و مجوز',
    'vanguard_system': 'سیستم Vanguard ERP',
    'all_rights_reserved': '© 2026 تمامی حقوق محفوظ است',
    'privacy_policy': 'حریم خصوصی',
    'tenant_profile_title': 'تنظیمات هویت شرکت و اطلاعات قانونی',
    'tenant_profile_subtitle': 'ویرایش نام رسمی، لوگو، شماره ثبت تجاری و شناسه مالیاتی.',
    'brand_identity': '۱. هویت برند و لوگوی رسمی',
    'company_name_ar': 'نام شرکت (عربی/فارسی)',
    'company_name_en': 'نام برند تجاری (انگلیسی)',
    'logo_url': 'آدرس اینترنتی لوگو',
    'add_picture': 'افزودن تصویر',
    'click_to_upload': 'کلیک برای بارگذاری',
    'legal_registration': '۲. شماره‌های ثبت قانونی',
    'commercial_reg': 'شماره ثبت تجاری (CR)',
    'tax_id': 'شناسه مالیاتی (MOF)',
    'cancel': 'انصراف',
    'save_changes': 'ذخیره تغییرات',
    'saving': 'در حال ذخیره‌سازی...'
  }
};

export interface LanguageProviderProps {
  children: React.ReactNode;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');
  const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr');

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    const newDir = (lang === 'ar' || lang === 'fa') ? 'rtl' : 'ltr';
    setDir(newDir);

    if (typeof document !== 'undefined') {
      document.documentElement.dir = newDir;
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.dir = dir;
      document.documentElement.lang = language;
    }
  }, [dir, language]);

  const t = (key: string, fallbackEn?: string): string => {
    const langMap = translations[language] || translations['en'];
    return langMap[key] || translations['en'][key] || fallbackEn || key;
  };

  return (
    <LanguageContext.Provider value={{ language, dir, setLanguage, t }}>
      <div dir={dir} className="w-full min-h-screen">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      dir: 'ltr',
      setLanguage: () => {},
      t: (key: string, fallbackEn?: string) => fallbackEn || key
    };
  }
  return context;
};
