'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'ar' | 'fr' | 'es';

export interface LanguageContextType {
  language: LanguageCode;
  dir: 'ltr' | 'rtl';
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, fallbackEn?: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    'workspace': 'Workspace',
    'sales_control': 'Sales Control & POS',
    'supersonic_fleet': 'SuperSonic Fleet Management',
    'social_crm': 'Social Media CRM',
    'operations_center': 'Operations & Pressing Center',
    'olive_pressing': 'Olive Pressing & Production',
    'crm_debtors': 'Customer Management & AR',
    'accounting_finance': 'Accounting & Finance',
    'hr_payroll': 'HR & Payroll',
    'dashboard': 'Dashboard',
    'pos_terminal': 'POS Cashier Terminal',
    'reports': 'Reports',
    'online_orders': 'Online Orders',
    'end_of_day': 'End of Day Z-Report',
    'pos_layout_config': 'POS Screen Config',
    'payment_types': 'Payment Types',
    'coupons_vouchers': 'Coupons & Vouchers',
    'discounts': 'Discounts',
    'price_modes': 'Price Modes',
    'workstations_printers': 'Workstations & Printers',
    'void_reasons': 'Void Reasons',
    'vat_exemption_reasons': 'VAT Exemption Reasons',
    'invoice_message': 'Invoice Message',
    'zone_setup': 'Zone Setup',
    'currency_setup': 'Currency Setup',
    'gps_fleet_map': 'Live GPS Fleet Map',
    'km_odometer_logs': 'KM & Odometer Logs',
    'fuel_consumption': 'Fuel Consumption',
    'vehicle_maintenance': 'Vehicle Maintenance',
    'route_playback': 'Route Playback',
    'driver_directory': 'Drivers Directory',
    'unified_inbox': 'Unified Social Inbox',
    'platform_orders': 'Platform Orders',
    'publishing_calendar': 'Publishing Calendar',
    'ad_campaigns': 'Ad Campaigns',
    'support_agents': 'Support Agents',
    'distributors_directory': 'Distributors Directory',
    'wholesale_sales': 'Wholesale Sales',
    'quotations': 'Quotations',
    'delivery_goods': 'Delivery of Goods',
    'purchases': 'Purchases',
    'purchase_orders': 'Purchase Orders',
    'reorder_guide': 'Reorder Guide',
    'stock_transfer': 'Stock Transfer',
    'lost_damaged_goods': 'Lost & Damaged Goods',
    'bom_assembly': 'BOM Assembly',
    'inventory_adjustments': 'Inventory Adjustments',
    'product_requests': 'Product Requests',
    'events_management': 'Events & Occasions',
    'quick_setup': 'Quick Setup',
    'products_services': 'Products & Services',
    'product_groups': 'Product Groups',
    'categories': 'Categories',
    'uom_tanks': 'Units of Measure & Tanks',
    'warehouses_locations': 'Warehouses & Locations',
    'suppliers_directory': 'Suppliers Directory',
    'customer_directory': 'Customer Accounts Directory',
    'receipts_vouchers': 'Receipt Vouchers',
    'aged_debtors': 'Aged Debtors Analysis',
    'ltv_insights': 'Customer LTV Insights',
    'tasks_appointments': 'Tasks & Appointments',
    'leads_opportunities': 'Leads & Opportunities',
    'sales_rep_performance': 'Sales Rep Performance',
    'complaints_dashboard': 'Complaints & Surveys',
    'loyalty_program': 'Loyalty & Rewards',
    'chart_of_accounts': 'Chart of Accounts (COA)',
    'journal_vouchers': 'Journal Vouchers (JV)',
    'payables_ap': 'Accounts Payable (AP)',
    'bank_reconciliation': 'Bank Reconciliation',
    'vat_closing': 'VAT Tax Closing',
    'employee_schedule': 'Employee Schedule',
    'employee_directory': 'Employee Directory',
    'payroll_management': 'Payroll Management',
    'recently_visited': 'Recently Visited',
    'end_of_month': 'End of Month',
    'alerts': 'Alerts',
    'exchange_rate': 'Exchange Rate',
    'search_placeholder': 'Quick search in screens & transactions...',
    'grid_dashboard': 'Grid Dashboard',
    'oil_pressing_short': 'Oil Pressing',
    'system_active': 'System Active & Online',
    'tenant_identity_settings': 'Identity & License Settings',
    'vanguard_system': 'Vanguard ERP System',
    'all_rights_reserved': '© 2026 All Rights Reserved',
    'privacy_policy': 'Privacy Policy',
    'terms_of_service': 'Terms of Service',
    'support_contact': 'Support & Contact',
    'search_menu': 'Search menu...',
  },
  ar: {
    'workspace': 'مساحة العمل',
    'sales_control': 'إدارة المبيعات ونقطة البيع',
    'supersonic_fleet': 'إدارة أسطول الشحن SuperSonic',
    'social_crm': 'التواصل الاجتماعي والدعم CRM',
    'operations_center': 'مركز العمليات والمعاصر',
    'olive_pressing': 'معصرة واستلام وإنتاج الزيت',
    'crm_debtors': 'إدارة العملاء والذمم',
    'accounting_finance': 'المحاسبة والمالية',
    'hr_payroll': 'الموارد البشرية والرواتب',
    'dashboard': 'لوحة التحكم',
    'pos_terminal': 'نقطة البيع الكاشير POS',
    'reports': 'التقارير',
    'online_orders': 'الطلبيات الإلكترونية',
    'end_of_day': 'إغلاق الصندوق Z-Report',
    'pos_layout_config': 'تنسيق الشاشات',
    'payment_types': 'أنواع الدفع',
    'coupons_vouchers': 'الكوبونات وقسائم الهدايا',
    'discounts': 'الخصومات',
    'price_modes': 'أنماط الأسعار',
    'workstations_printers': 'طابعات الفواتير والعمل',
    'void_reasons': 'أسباب الإلغاء',
    'vat_exemption_reasons': 'أسباب الإعفاء الضريبي',
    'invoice_message': 'رسالة الفاتورة',
    'zone_setup': 'توزيع المناطق',
    'currency_setup': 'تهيئة العملات',
    'gps_fleet_map': 'خريطة تتبع الشاحنات Live GPS',
    'km_odometer_logs': 'سجل المسافات والعدّاد',
    'fuel_consumption': 'استهلاك الوقود',
    'vehicle_maintenance': 'صيانة المركبات',
    'route_playback': 'سجل الرحلات',
    'driver_directory': 'دليل السائقين',
    'unified_inbox': 'صندوق الرسائل الموحد',
    'platform_orders': 'طلبات المنصات',
    'publishing_calendar': 'رزنامة المحتوى',
    'ad_campaigns': 'الحملات الإعلانية',
    'support_agents': 'فريق الدعم الداخلي',
    'distributors_directory': 'دليل الموزعين',
    'wholesale_sales': 'مبيعات الجملة',
    'quotations': 'عروض الأسعار',
    'delivery_goods': 'تسليم البضائع',
    'purchases': 'المشتريات',
    'purchase_orders': 'أوامر الشراء',
    'reorder_guide': 'دليل إعادة الطلب',
    'stock_transfer': 'تحويلات المخزون',
    'lost_damaged_goods': 'البضائع المفقودة والتالفة',
    'bom_assembly': 'تجميع المنتجات BOM',
    'inventory_adjustments': 'تسويات المخزون',
    'product_requests': 'طلبات المنتجات',
    'events_management': 'الفعاليات والمناسبات',
    'quick_setup': 'الإعداد السريع',
    'products_services': 'المنتجات والخدمات',
    'product_groups': 'المجموعات',
    'categories': 'الفئات والتصنيفات',
    'uom_tanks': 'وحدات القياس والخزانات',
    'warehouses_locations': 'المواقع والمستودعات',
    'suppliers_directory': 'دليل الموردين',
    'customer_directory': 'دليل حسابات العملاء',
    'receipts_vouchers': 'إيصالات المقبوضات',
    'aged_debtors': 'أعمار ديون العملاء',
    'ltv_insights': 'تحليلات القيمة الدائمة LTV',
    'tasks_appointments': 'المهام والمواعيد',
    'leads_opportunities': 'الفرص والاتصالات',
    'sales_rep_performance': 'أداء فريق المبيعات',
    'complaints_dashboard': 'الشكاوى والاستطلاعات',
    'loyalty_program': 'برامج الولاء والنقاط',
    'chart_of_accounts': 'شجرة الحسابات العامة (COA)',
    'journal_vouchers': 'سندات اليومية (JV)',
    'payables_ap': 'ذمم الموردين الدائنة (AP)',
    'bank_reconciliation': 'مطابقة الحسابات البنكية',
    'vat_closing': 'إغلاق ضريبة T.V.A',
    'employee_schedule': 'جدول دوام الموظفين',
    'employee_directory': 'سجل الموظفين',
    'payroll_management': 'مسير الرواتب والأجور',
    'recently_visited': 'المزارة مؤخراً',
    'end_of_month': 'إقفال الشهر',
    'alerts': 'التنبيهات',
    'exchange_rate': 'سعر الصرف',
    'search_placeholder': 'بحث سريع في الشاشات والمعاملات...',
    'grid_dashboard': 'لوحة المربعات الرئيسية',
    'oil_pressing_short': 'المعصرة والإنتاج',
    'system_active': 'النظام التشغيلي الفعّال',
    'tenant_identity_settings': 'إعدادات الهوية والتراخيص',
    'vanguard_system': 'نظام Vanguard ERP',
    'all_rights_reserved': '© 2026 جميع الحقوق محفوظة',
    'privacy_policy': 'سياسة الخصوصية',
    'terms_of_service': 'الشروط والأحكام',
    'support_contact': 'الدعم والاتصال',
    'search_menu': 'البحث في القائمة...',
  },
  fr: {
    'workspace': 'Espace de Travail',
    'sales_control': 'Contrôle des Ventes & POS',
    'supersonic_fleet': 'Gestion de Flotte SuperSonic',
    'social_crm': 'CRM Réseaux Sociaux',
    'operations_center': 'Centre d\'Opérations & Moulin',
    'olive_pressing': 'Pressage d\'Huile & Production',
    'crm_debtors': 'Gestion Clients & Créances',
    'accounting_finance': 'Comptabilité & Finance',
    'hr_payroll': 'Ressources Humaines & Paie',
    'dashboard': 'Tableau de Bord',
    'pos_terminal': 'Terminal Caisse POS',
    'reports': 'Rapports',
    'online_orders': 'Commandes en Ligne',
    'end_of_day': 'Rapport Z Fin de Journée',
    'pos_layout_config': 'Configuration Écran POS',
    'payment_types': 'Types de Paiement',
    'coupons_vouchers': 'Coupons & Bons',
    'discounts': 'Remises',
    'price_modes': 'Modes de Prix',
    'workstations_printers': 'Imprimantes & Postes',
    'void_reasons': 'Motifs d\'Annulation',
    'vat_exemption_reasons': 'Exonération de TVA',
    'invoice_message': 'Message sur Facture',
    'zone_setup': 'Configuration des Zones',
    'currency_setup': 'Configuration des Devises',
    'gps_fleet_map': 'Carte GPS en Direct',
    'km_odometer_logs': 'Relevés Kilométriques',
    'fuel_consumption': 'Consommation Carburant',
    'vehicle_maintenance': 'Maintenance Véhicules',
    'route_playback': 'Historique des Trajets',
    'driver_directory': 'Répertoire Chauffeurs',
    'unified_inbox': 'Boîte de Réception Unifiée',
    'platform_orders': 'Commandes Plateformes',
    'publishing_calendar': 'Calendrier de Publication',
    'ad_campaigns': 'Campagnes Publicitaires',
    'support_agents': 'Agents de Support',
    'distributors_directory': 'Répertoire Distributeurs',
    'wholesale_sales': 'Ventes en Gros',
    'quotations': 'Devis',
    'delivery_goods': 'Livraison de Marchandises',
    'purchases': 'Achats',
    'purchase_orders': 'Bons de Commande',
    'reorder_guide': 'Guide de Réapprovisionnement',
    'stock_transfer': 'Transferts de Stock',
    'lost_damaged_goods': 'Marchandises Perdues & Endommagées',
    'bom_assembly': 'Assemblage BOM',
    'inventory_adjustments': 'Ajustements d\'Inventaire',
    'product_requests': 'Demandes de Produits',
    'events_management': 'Événements & Occasions',
    'quick_setup': 'Configuration Rapide',
    'products_services': 'Produits & Services',
    'product_groups': 'Groupes de Produits',
    'categories': 'Catégories',
    'uom_tanks': 'Unités de Mesure & Cuves',
    'warehouses_locations': 'Entrepôts & Emplacements',
    'suppliers_directory': 'Répertoire Fournisseurs',
    'customer_directory': 'Répertoire Comptes Clients',
    'receipts_vouchers': 'Bons de Encaissement',
    'aged_debtors': 'Analyse des Créances',
    'ltv_insights': 'Analyses LTV Clients',
    'tasks_appointments': 'Tâches & Rendez-vous',
    'leads_opportunities': 'Pistes & Opportunités',
    'sales_rep_performance': 'Performance Commercials',
    'complaints_dashboard': 'Réclamations & Sondages',
    'loyalty_program': 'Programme de Fidélité',
    'chart_of_accounts': 'Plan Comptable (COA)',
    'journal_vouchers': 'Opérations Diverses (JV)',
    'payables_ap': 'Comptes Fournisseurs (AP)',
    'bank_reconciliation': 'Rapprochement Bancaire',
    'vat_closing': 'Clôture TVA',
    'employee_schedule': 'Planning Employés',
    'employee_directory': 'Annuaire Employés',
    'payroll_management': 'Gestion de la Paie',
    'recently_visited': 'Récemment Visité',
    'end_of_month': 'Fin de Mois',
    'alerts': 'Alertes',
    'exchange_rate': 'Taux de Change',
    'search_placeholder': 'Recherche rapide dans écrans...',
    'grid_dashboard': 'Tableau de Bord Grille',
    'oil_pressing_short': 'Pressage Huile',
    'system_active': 'Système Actif',
    'tenant_identity_settings': 'Paramètres d\'Identité',
    'vanguard_system': 'Système Vanguard ERP',
    'all_rights_reserved': '© 2026 Tous Droits Réservés',
    'privacy_policy': 'Politique de Confidentialité',
    'terms_of_service': 'Conditions d\'Utilisation',
    'support_contact': 'Support & Contact',
    'search_menu': 'Rechercher le menu...',
  },
  es: {
    'workspace': 'Espacio de Trabajo',
    'sales_control': 'Control de Ventas & TPV',
    'supersonic_fleet': 'Gestión de Flota SuperSonic',
    'social_crm': 'CRM Redes Sociales',
    'operations_center': 'Centro de Operaciones & Almazara',
    'olive_pressing': 'Prensado de Aceite & Producción',
    'crm_debtors': 'Gestión de Clientes & Deudores',
    'accounting_finance': 'Contabilidad & Finanzas',
    'hr_payroll': 'Recursos Humanos & Nóminas',
    'dashboard': 'Panel de Control',
    'pos_terminal': 'Terminal TPV Caja',
    'reports': 'Informes',
    'online_orders': 'Pedidos en Línea',
    'end_of_day': 'Informe Z Cierre de Día',
    'pos_layout_config': 'Configuración de Pantalla TPV',
    'payment_types': 'Tipos de Pago',
    'coupons_vouchers': 'Cupones & Vouchers',
    'discounts': 'Descuentos',
    'price_modes': 'Modos de Precio',
    'workstations_printers': 'Impresoras & Estaciones',
    'void_reasons': 'Motivos de Anulación',
    'vat_exemption_reasons': 'Exención de IVA',
    'invoice_message': 'Mensaje en Factura',
    'zone_setup': 'Configuración de Zonas',
    'currency_setup': 'Configuración de Moneda',
    'gps_fleet_map': 'Mapa GPS en Vivo',
    'km_odometer_logs': 'Registros de KM',
    'fuel_consumption': 'Consumo de Combustible',
    'vehicle_maintenance': 'Mantenimiento de Vehículos',
    'route_playback': 'Historial de Rutas',
    'driver_directory': 'Directorio de Conductores',
    'unified_inbox': 'Bandeja Unificada',
    'platform_orders': 'Pedidos de Plataformas',
    'publishing_calendar': 'Calendario de Publicación',
    'ad_campaigns': 'Campañas Publicitarias',
    'support_agents': 'Agentes de Soporte',
    'distributors_directory': 'Directorio de Distribuidores',
    'wholesale_sales': 'Ventas al por Mayor',
    'quotations': 'Presupuestos',
    'delivery_goods': 'Entrega de Mercancías',
    'purchases': 'Compras',
    'purchase_orders': 'Órdenes de Compra',
    'reorder_guide': 'Guía de Reaprovisionamiento',
    'stock_transfer': 'Transferencias de Stock',
    'lost_damaged_goods': 'Mercancías Perdidas & Dañadas',
    'bom_assembly': 'Ensamblaje BOM',
    'inventory_adjustments': 'Ajustes de Inventario',
    'product_requests': 'Solicitudes de Productos',
    'events_management': 'Eventos & Ocasiones',
    'quick_setup': 'Configuración Rápida',
    'products_services': 'Productos & Servicios',
    'product_groups': 'Grupos de Productos',
    'categories': 'Categorías',
    'uom_tanks': 'Unidades de Medida & Tanques',
    'warehouses_locations': 'Almacenes & Ubicaciones',
    'suppliers_directory': 'Directorio de Proveedores',
    'customer_directory': 'Directorio de Cuentas de Clientes',
    'receipts_vouchers': 'Recibos de Cobro',
    'aged_debtors': 'Análisis de Deudores',
    'ltv_insights': 'Análisis LTV Clientes',
    'tasks_appointments': 'Tareas & Citas',
    'leads_opportunities': 'Oportunidades',
    'sales_rep_performance': 'Rendimiento Comercial',
    'complaints_dashboard': 'Quejas & Encuestas',
    'loyalty_program': 'Programa de Fidelización',
    'chart_of_accounts': 'Plan de Cuentas (COA)',
    'journal_vouchers': 'Asientos Contables (JV)',
    'payables_ap': 'Cuentas por Pagar (AP)',
    'bank_reconciliation': 'Conciliación Bancaria',
    'vat_closing': 'Cierre de IVA',
    'employee_schedule': 'Horario de Empleados',
    'employee_directory': 'Directorio de Empleados',
    'payroll_management': 'Gestión de Nóminas',
    'recently_visited': 'Visitado Recientemente',
    'end_of_month': 'Cierre de Mes',
    'alerts': 'Alertas',
    'exchange_rate': 'Tipo de Cambio',
    'search_placeholder': 'Búsqueda rápida en pantallas...',
    'grid_dashboard': 'Panel de Cuadrícula',
    'oil_pressing_short': 'Prensado de Aceite',
    'system_active': 'Sistema Activo',
    'tenant_identity_settings': 'Ajustes de Identidad',
    'vanguard_system': 'Sistema Vanguard ERP',
    'all_rights_reserved': '© 2026 Todos los Derechos Reservados',
    'privacy_policy': 'Política de Privacidad',
    'terms_of_service': 'Términos del Servicio',
    'support_contact': 'Soporte & Contacto',
    'search_menu': 'Buscar menú...',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');
  const [dir, setDir] = useState<'ltr' | 'rtl'>('ltr');

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    const newDir = lang === 'ar' ? 'rtl' : 'ltr';
    setDir(newDir);

    if (typeof document !== 'undefined') {
      document.documentElement.dir = newDir;
      document.documentElement.lang = lang;
    }
  };

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.dir = dir;
      document.documentElement.lang = language;
    }
  }, [dir, language]);

  const t = (key: string, fallbackEn?: string): string => {
    const langMap = translations[language] || translations['en'];
    return langMap[key] || translations['en'][key] || fallbackEn || key;
  };

  return (
    <LanguageContext.Provider value={{ language, dir, setLanguage, t }}>
      <div dir={dir} className="w-full min-h-screen">
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      dir: 'ltr',
      setLanguage: () => {},
      t: (key: string, fallbackEn?: string) => fallbackEn || key
    };
  }
  return context;
};
