/**
 * Vanguard ERP - Lebanese Standard Chart of Accounts (COA) Master Catalog
 * Full Sub Class 3 (3-digit) and Sub Class 4 (5-digit) accounts hierarchy
 * Harvested from Lebanese standard accounting framework & Omega ERP.
 */

export interface CoaAccountHeader {
  account_name: string;
  account_number: string;
  class_id?: number;
}

export const LEBANESE_SUB_CLASSES_4: CoaAccountHeader[] = [
  { account_name: 'Account Receivables', account_number: '41110', class_id: 4 },
  { account_name: 'Accounts Receivable On Participations', account_number: '29520', class_id: 2 },
  { account_name: 'Accruals - Taxes & Fees', account_number: '44180', class_id: 4 },
  { account_name: 'Accruals-Unpaid Charges', account_number: '43180', class_id: 4 },
  { account_name: 'Accrued Charges', account_number: '47210', class_id: 4 },
  { account_name: 'Added Value', account_number: '19200', class_id: 1 },
  { account_name: 'Administrative Expenses', account_number: '68510', class_id: 6 },
  { account_name: 'Advances On Account Of Intang.Fixed Assets', account_number: '21980', class_id: 2 },
  { account_name: 'Advances To Suppliers Of Goods', account_number: '40900', class_id: 4 },
  { account_name: 'Agricultural Investments', account_number: '22640', class_id: 2 },
  { account_name: 'Amortisation Of Share Premiums', account_number: '67910', class_id: 6 },
  { account_name: 'Amounts Due From Sale Of Fixed Assets&Investments', account_number: '46910', class_id: 4 },
  { account_name: 'Amounts Due On Purchase Of Trading Investments', account_number: '46510', class_id: 4 },
  { account_name: 'Ancillary Expenses On Purchase Of Raw Mater.&Cons.', account_number: '61180', class_id: 6 },
  { account_name: 'Attendance Fees', account_number: '66110', class_id: 6 },
  { account_name: 'Balances Payable On Investment', account_number: '46530', class_id: 4 },
  { account_name: 'Bank Interest&Interest On Financing Operations', account_number: '67360', class_id: 6 },
  { account_name: 'Billing - Invoices', account_number: '70130', class_id: 7 },
  { account_name: 'Billings', account_number: '40110', class_id: 4 },
  { account_name: 'Billings2', account_number: '40310', class_id: 4 },
  { account_name: 'Billings3', account_number: '70110', class_id: 7 },
  { account_name: 'Bills Payable', account_number: '40150', class_id: 4 },
  { account_name: 'Bills Payable - Taxes & Fees', account_number: '44150', class_id: 4 },
  { account_name: 'Bills Payable For Purchase Of A Trading Company', account_number: '16810', class_id: 1 },
  { account_name: 'Bills Payable-Social Security Establishments', account_number: '43150', class_id: 4 },
  { account_name: 'Blocked Staff Accounts', account_number: '42820', class_id: 4 },
  { account_name: 'Boards Of Directors \' Remunerations', account_number: '63170', class_id: 6 },
  { account_name: 'Brevets', account_number: '62540', class_id: 6 },
  { account_name: 'Building Infrustructures ( Run-Way...)', account_number: '22330', class_id: 2 },
  { account_name: 'Buildings', account_number: '22310', class_id: 2 },
  { account_name: 'Capital', account_number: '10100', class_id: 1 },
  { account_name: 'Cash', account_number: '53000', class_id: 5 },
  { account_name: 'Cash Over', account_number: '76140', class_id: 7 },
  { account_name: 'Cash Short', account_number: '66140', class_id: 6 },
  { account_name: 'Characters Rights', account_number: '62570', class_id: 6 },
  { account_name: 'Closing Stock', account_number: '60520', class_id: 6 },
  { account_name: 'Closing Stock.', account_number: '61520', class_id: 6 },
  { account_name: 'Commercial Margins', account_number: '19100', class_id: 1 },
  { account_name: 'Constitution Expenses', account_number: '28110', class_id: 2 },
  { account_name: 'Construction On Third Parties Buildings', account_number: '22340', class_id: 2 },
  { account_name: 'Consumables', account_number: '61120', class_id: 6 },
  { account_name: 'Contributions Payable', account_number: '43110', class_id: 4 },
  { account_name: 'Copy Rights', account_number: '62530', class_id: 6 },
  { account_name: 'Cost Of Services', account_number: '61130', class_id: 6 },
  { account_name: 'Cost Of Software', account_number: '61100', class_id: 6 },
  { account_name: 'Cosumables', account_number: '60120', class_id: 6 },
  { account_name: 'Creditors-Package Material&Tools On Consignment', account_number: '46110', class_id: 4 },
  { account_name: 'Cumulative Life Annuity Income', account_number: '16840', class_id: 1 },
  { account_name: 'Current Assets', account_number: '51200', class_id: 5 },
  { account_name: 'Current Result Before Tax', account_number: '19500', class_id: 1 },
  { account_name: 'Debentures', account_number: '46520', class_id: 4 },
  { account_name: 'Debentures ( Bonds & Coupons)', account_number: '25350', class_id: 2 },
  { account_name: 'Debtors-Packing Material&Tools On Consignment', account_number: '46810', class_id: 4 },
  { account_name: 'Decrease In Creditors', account_number: '47520', class_id: 4 },
  { account_name: 'Decrease In Debtors', account_number: '47610', class_id: 4 },
  { account_name: 'Deferred Charges', account_number: '65150', class_id: 6 },
  { account_name: 'Deposits & Guarantees', account_number: '16820', class_id: 1 },
  { account_name: 'Depreciable Major Repairs', account_number: '47120', class_id: 4 },
  { account_name: 'Differences Compensated By Exchange Results', account_number: '47580', class_id: 4 },
  { account_name: 'Discount', account_number: '71190', class_id: 7 },
  { account_name: 'Discounts Allowable', account_number: '67350', class_id: 6 },
  { account_name: 'Discounts Allowed', account_number: '41190', class_id: 4 },
  { account_name: 'Discounts Allowed.', account_number: '70900', class_id: 7 },
  { account_name: 'Discounts Receivable', account_number: '60190', class_id: 6 },
  { account_name: 'Discounts Receivable.', account_number: '61190', class_id: 6 },
  { account_name: 'Discounts Receivable..', account_number: '62190', class_id: 6 },
  { account_name: 'Discounts Received', account_number: '40190', class_id: 4 },
  { account_name: 'Discounts Received.', account_number: '40390', class_id: 4 },
  { account_name: 'Discounts Received..', account_number: '77330', class_id: 7 },
  { account_name: 'Doubtful Debtors', account_number: '41150', class_id: 4 },
  { account_name: 'Due Salaries', account_number: '47000', class_id: 4 },
  { account_name: 'E,D,L', account_number: '47400', class_id: 4 },
  { account_name: 'Electricity', account_number: '61140', class_id: 6 },
  { account_name: 'Exceptional Depreciation Of Fixed Assets', account_number: '68910', class_id: 6 },
  { account_name: 'Exceptional Income On Normal Transactions', account_number: '78810', class_id: 7 },
  { account_name: 'Exceptional Provision For Diminution In Value', account_number: '68920', class_id: 6 },
  { account_name: 'Expenditure On Capital Operations', account_number: '68550', class_id: 6 },
  { account_name: 'External Services', account_number: '62600', class_id: 6 },
  { account_name: 'Factory Residuals', account_number: '72580', class_id: 7 },
  { account_name: 'Financial Fixed Assets', account_number: '25000', class_id: 2 },
  { account_name: 'Financial Fixed Assets.', account_number: '68150', class_id: 6 },
  { account_name: 'Financial Fixed Assets..', account_number: '78150', class_id: 7 },
  { account_name: 'Finished Goods Produced', account_number: '72550', class_id: 7 },
  { account_name: 'Fixed Assets', account_number: '22510', class_id: 2 },
  { account_name: 'Fixed Commission', account_number: '63140', class_id: 6 },
  { account_name: 'Furniture', account_number: '22630', class_id: 2 },
  { account_name: 'General Improvements On Buildings', account_number: '22320', class_id: 2 },
  { account_name: 'General Instal.& Other Repairs & Maintenance', account_number: '22610', class_id: 2 },
  { account_name: 'Goods', account_number: '60110', class_id: 6 },
  { account_name: 'Goods For Resale', account_number: '37100', class_id: 3 },
  { account_name: 'Government Advances', account_number: '16830', class_id: 1 },
  { account_name: 'Gross Operating Profit', account_number: '19300', class_id: 1 },
  { account_name: 'Gross Profit/Loss Final', account_number: '19400', class_id: 1 },
  { account_name: 'Hardware Revenue', account_number: '71110', class_id: 7 },
  { account_name: 'I Tax.', account_number: '64510', class_id: 6 },
  { account_name: 'Income Receivable', account_number: '44980', class_id: 4 },
  { account_name: 'Income Tax', account_number: '69000', class_id: 6 },
  { account_name: 'Increase In Creditors', account_number: '47620', class_id: 4 },
  { account_name: 'Increase In Debtors', account_number: '47510', class_id: 4 },
  { account_name: 'Industrial Equipment', account_number: '22430', class_id: 2 },
  { account_name: 'Industrial Tools', account_number: '22440', class_id: 2 },
  { account_name: 'Insurance Premiums', account_number: '62680', class_id: 6 },
  { account_name: 'Intangible Fixed Assets', account_number: '65110', class_id: 6 },
  { account_name: 'Intangible Fixed Assets.', account_number: '78110', class_id: 7 },
  { account_name: 'Intangible Fixed Assets..', account_number: '68110', class_id: 6 },
  { account_name: 'Interest On Accounts Payable And Loans', account_number: '67310', class_id: 6 },
  { account_name: 'Interest On Current Accounts & Deposits Payable', account_number: '67320', class_id: 6 },
  { account_name: 'Interest On Guarantees', account_number: '67330', class_id: 6 },
  { account_name: 'Interest On Other Creditors', account_number: '67340', class_id: 6 },
  { account_name: 'Interets Bancaires', account_number: '77360', class_id: 7 },
  { account_name: 'Intermediary Products', account_number: '72510', class_id: 7 },
  { account_name: 'Inventory Assets', account_number: '31110', class_id: 3 },
  { account_name: 'Investments ( Shares & Parts)', account_number: '25310', class_id: 2 },
  { account_name: 'Invoices In Transit', account_number: '40180', class_id: 4 },
  { account_name: 'Invoices In Transit2', account_number: '40380', class_id: 4 },
  { account_name: 'Joint Ventures', account_number: '45180', class_id: 4 },
  { account_name: 'Land', account_number: '22710', class_id: 2 },
  { account_name: 'Land Improvements', account_number: '22140', class_id: 2 },
  { account_name: 'Land Other Than Leasehold Land', account_number: '29210', class_id: 2 },
  { account_name: 'Land With Construction', account_number: '22120', class_id: 2 },
  { account_name: 'Leasehold Land For Exploration(Mines...)', account_number: '22130', class_id: 2 },
  { account_name: 'Leashold Land For Exploration', account_number: '28210', class_id: 2 },
  { account_name: 'Legal Reserves', account_number: '11100', class_id: 1 },
  { account_name: 'Licences', account_number: '62550', class_id: 6 },
  { account_name: 'Loans & Advances To Staff', account_number: '42810', class_id: 4 },
  { account_name: 'Loans To Employees', account_number: '25520', class_id: 2 },
  { account_name: 'Loans To Partners/Shareholders', account_number: '25510', class_id: 2 },
  { account_name: 'Long & Medium Term Loans', account_number: '29550', class_id: 2 },
  { account_name: 'Loss On Exchange', account_number: '67500', class_id: 6 },
  { account_name: 'Loss Results', account_number: '13910', class_id: 1 },
  { account_name: 'Losses Brought Forward', account_number: '12500', class_id: 1 },
  { account_name: 'M.Tax', account_number: '64210', class_id: 6 },
  { account_name: 'Maintenance Contrat', account_number: '71120', class_id: 7 },
  { account_name: 'Major Shareholders\'Remunerations', account_number: '63160', class_id: 6 },
  { account_name: 'Municipalety Taxes', account_number: '64200', class_id: 6 },
  { account_name: 'Net Income On Sale Of Investment Securities', account_number: '77810', class_id: 7 },
  { account_name: 'New Result Eoy', account_number: '13200', class_id: 1 },
  { account_name: 'New Result For Year', account_number: '13100', class_id: 1 },
  { account_name: 'Nominal Rent-Immovable Properties', account_number: '62520', class_id: 6 },
  { account_name: 'Nominal Rent-Movable Properties', account_number: '62510', class_id: 6 },
  { account_name: 'Non-Operating Results', account_number: '19600', class_id: 1 },
  { account_name: 'On Capital Operations', account_number: '67520', class_id: 6 },
  { account_name: 'On Capital Transactions', account_number: '77550', class_id: 7 },
  { account_name: 'On Current Accounts', account_number: '77510', class_id: 7 },
  { account_name: 'On Ordinary Business', account_number: '67510', class_id: 6 },
  { account_name: 'Opening Stock', account_number: '60510', class_id: 6 },
  { account_name: 'Opening Stock.', account_number: '61510', class_id: 6 },
  { account_name: 'Operating Bad Debts', account_number: '66120', class_id: 6 },
  { account_name: 'Operation Expenses', account_number: '62640', class_id: 6 },
  { account_name: 'Other Administrative Expenses', account_number: '66100', class_id: 6 },
  { account_name: 'Other Deferred Charges', account_number: '47190', class_id: 4 },
  { account_name: 'Other External Services', account_number: '62690', class_id: 6 },
  { account_name: 'Other Fixed Accounts Receivable', account_number: '29590', class_id: 2 },
  { account_name: 'Other Fixed Investments', account_number: '29530', class_id: 2 },
  { account_name: 'Other Income On Except.Transact.Of Capital Nature', account_number: '78880', class_id: 7 },
  { account_name: 'Other Intangible Fixed Assets', account_number: '28190', class_id: 2 },
  { account_name: 'Other Intangible Fixed Assets2', account_number: '29190', class_id: 2 },
  { account_name: 'Other Loans', account_number: '25580', class_id: 2 },
  { account_name: 'Other Long & Medium Term Debts', account_number: '16890', class_id: 1 },
  { account_name: 'Other Receivables', account_number: '45970', class_id: 4 },
  { account_name: 'Other Receivables-State & Public Establisments', account_number: '44970', class_id: 4 },
  { account_name: 'Other Reserves', account_number: '11900', class_id: 1 },
  { account_name: 'Other Similar Rights', account_number: '62580', class_id: 6 },
  { account_name: 'Other Tangible Fixed Assets', account_number: '22760', class_id: 2 },
  { account_name: 'Other Tangible Fixed Assets.', account_number: '28260', class_id: 2 },
  { account_name: 'Other Tangible Fixed Assets..', account_number: '29260', class_id: 2 },
  { account_name: 'Other Unissued Fixed Investments', account_number: '46330', class_id: 4 },
  { account_name: 'Others Partners', account_number: '45150', class_id: 4 },
  { account_name: 'Others Payables', account_number: '45570', class_id: 4 },
  { account_name: 'Others Revenue', account_number: '71140', class_id: 7 },
  { account_name: 'Participation Investments', account_number: '29510', class_id: 2 },
  { account_name: 'Partner`S Subscriptions', account_number: '45510', class_id: 4 },
  { account_name: 'Patents,Licences,Copy Rights & Other Similar Items', account_number: '28130', class_id: 2 },
  { account_name: 'Personnel Services', account_number: '62650', class_id: 6 },
  { account_name: 'Plain Land', account_number: '22110', class_id: 2 },
  { account_name: 'Pre-Operating Expenses', account_number: '47110', class_id: 4 },
  { account_name: 'Presence Fees & Directors & Managers Fees', account_number: '76130', class_id: 7 },
  { account_name: 'Prmium Paid On Bonds', account_number: '47130', class_id: 4 },
  { account_name: 'Production In Progress', account_number: '72110', class_id: 7 },
  { account_name: 'Profit Brought Forward', account_number: '12100', class_id: 1 },
  { account_name: 'Profit On Exchange', account_number: '77500', class_id: 7 },
  { account_name: 'Profit Results', account_number: '13810', class_id: 1 },
  { account_name: 'Prov. For Disputes &Other Probable Contingencies', account_number: '15110', class_id: 1 },
  { account_name: 'Prov.For Contingencies & Financial Charges', account_number: '67950', class_id: 6 },
  { account_name: 'Prov.For Diminut.In Value Of Accounts Receivable', account_number: '65540', class_id: 6 },
  { account_name: 'Prov.For Diminut.In Value Of Financial Fixed Asset', account_number: '67920', class_id: 6 },
  { account_name: 'Prov.For Diminut.In Value Of Intang.Fixed Assets', account_number: '65510', class_id: 6 },
  { account_name: 'Prov.For Diminut.In Value Of Stocks&Work In Progrs', account_number: '65530', class_id: 6 },
  { account_name: 'Prov.For Diminution In Value Of Investments', account_number: '67940', class_id: 6 },
  { account_name: 'Prov.For Diminution In Value Of Tangib.Fixed Asset', account_number: '65520', class_id: 6 },
  { account_name: 'Prov.For Fines And Penalties', account_number: '15150', class_id: 1 },
  { account_name: 'Prov.For Guarantees Granted To Customers', account_number: '15120', class_id: 1 },
  { account_name: 'Prov.For Loss On Exchange', account_number: '15130', class_id: 1 },
  { account_name: 'Prov.For Losses On Term Contracts', account_number: '15140', class_id: 1 },
  { account_name: 'Prov.For Operating Contingencies & Charges', account_number: '65550', class_id: 6 },
  { account_name: 'Prov.For Pension & Related Expenses', account_number: '15520', class_id: 1 },
  { account_name: 'Provision For Contingencies & Charges', account_number: '68950', class_id: 6 },
  { account_name: 'Provisions For Deffered Charges', account_number: '15510', class_id: 1 },
  { account_name: 'Provisions For Taxation', account_number: '15530', class_id: 1 },
  { account_name: 'Purchase Of Raw Materials', account_number: '61110', class_id: 6 },
  { account_name: 'Re-Allocation Of Exceptional Charges', account_number: '78890', class_id: 7 },
  { account_name: 'Reallocation Of Financial Charges', account_number: '77890', class_id: 7 },
  { account_name: 'Reallocation Of Operating Charges', account_number: '76190', class_id: 7 },
  { account_name: 'Redeemable Capital (Capital To Reimburse)', account_number: '45520', class_id: 4 },
  { account_name: 'Related Companies', account_number: '45110', class_id: 4 },
  { account_name: 'Release Of Provision For Contingencies And Charges', account_number: '77950', class_id: 7 },
  { account_name: 'Release Of Provision For Diminution In Value', account_number: '76810', class_id: 7 },
  { account_name: 'Release Of Provision For Diminution In Value.', account_number: '77930', class_id: 7 },
  { account_name: 'Rent (Buildings)', account_number: '62630', class_id: 6 },
  { account_name: 'Rental Income From Non-Operating Estates', account_number: '76120', class_id: 7 },
  { account_name: 'Repairs & Maintenance', account_number: '62620', class_id: 6 },
  { account_name: 'Research & Development Cost', account_number: '28120', class_id: 2 },
  { account_name: 'Result For The Year', account_number: '19700', class_id: 1 },
  { account_name: 'Result Of The Period - Loss', account_number: '13900', class_id: 1 },
  { account_name: 'Result Of The Period - Profit', account_number: '13800', class_id: 1 },
  { account_name: 'Reusable Wrapping Material', account_number: '22650', class_id: 2 },
  { account_name: 'Revenue From Fixed Accounts Receivable', account_number: '77250', class_id: 7 },
  { account_name: 'Revenue From Fixed Securities', account_number: '77230', class_id: 7 },
  { account_name: 'Revenue From Investment Securities', account_number: '77210', class_id: 7 },
  { account_name: 'Revenue From Loans Granted', account_number: '77310', class_id: 7 },
  { account_name: 'Revenue From Other Participations', account_number: '77160', class_id: 7 },
  { account_name: 'Revenue From Participation Accounts Receivable', account_number: '77170', class_id: 7 },
  { account_name: 'Revenue From Participation Investments', account_number: '77110', class_id: 7 },
  { account_name: 'Revenue From Sundry Accounts Receivable', account_number: '77270', class_id: 7 },
  { account_name: 'Revenue From Trading Accounts Receivable', account_number: '77260', class_id: 7 },
  { account_name: 'Royalties ...', account_number: '76110', class_id: 7 },
  { account_name: 'Salaries', account_number: '63110', class_id: 6 },
  { account_name: 'Sales Of Ancilliary Activities', account_number: '71970', class_id: 7 },
  { account_name: 'Sales Of Productions', account_number: '71910', class_id: 7 },
  { account_name: 'Sales Of Services', account_number: '71930', class_id: 7 },
  { account_name: 'Sales Of Work', account_number: '71920', class_id: 7 },
  { account_name: 'Services', account_number: '71130', class_id: 7 },
  { account_name: 'Services In Progress', account_number: '72260', class_id: 7 },
  { account_name: 'Services2', account_number: '71300', class_id: 7 },
  { account_name: 'Share Of Expenses', account_number: '76510', class_id: 7 },
  { account_name: 'Share Of Net Revenue', account_number: '76550', class_id: 7 },
  { account_name: 'Shipping & Customs', account_number: '60180', class_id: 6 },
  { account_name: 'Social Security Charges', account_number: '63500', class_id: 6 },
  { account_name: 'Software Revenue', account_number: '71100', class_id: 7 },
  { account_name: 'Special Purpose Installations', account_number: '22420', class_id: 2 },
  { account_name: 'Specialised Installations', account_number: '22410', class_id: 2 },
  { account_name: 'Stationery For Office & Computer', account_number: '22620', class_id: 2 },
  { account_name: 'Statutory And Contractual Reserves', account_number: '11200', class_id: 1 },
  { account_name: 'Stock', account_number: '34700', class_id: 3 },
  { account_name: 'Studies & Research', account_number: '62670', class_id: 6 },
  { account_name: 'Studies In Progress', account_number: '72250', class_id: 7 },
  { account_name: 'Subscribed But Uncalled Capital', account_number: '45910', class_id: 4 },
  { account_name: 'Subscribed Capital ( Uncalled )', account_number: '10110', class_id: 1 },
  { account_name: 'Subscribed,Called But Unpaid Capital', account_number: '45920', class_id: 4 },
  { account_name: 'Subsidies Receivable', account_number: '44910', class_id: 4 },
  { account_name: 'Sundry Non-Operating Creditors', account_number: '46590', class_id: 4 },
  { account_name: 'Sundry Non-Operating Debtors', account_number: '46990', class_id: 4 },
  { account_name: 'Sundry Non-Operating Debtors.', account_number: '49690', class_id: 4 },
  { account_name: 'Sundry Operating Creditors', account_number: '46190', class_id: 4 },
  { account_name: 'Sundry Operating Debtors', account_number: '46890', class_id: 4 },
  { account_name: 'Sundry Operating Debtors2', account_number: '49680', class_id: 4 },
  { account_name: 'T.V.A. Dues', account_number: '44250', class_id: 4 },
  { account_name: 'Tangible Fixed Assets', account_number: '22200', class_id: 2 },
  { account_name: 'Tangible Fixed Assets2', account_number: '65120', class_id: 6 },
  { account_name: 'Tangible Fixed Assets3', account_number: '68120', class_id: 6 },
  { account_name: 'Tangible Fixed Assets4', account_number: '78120', class_id: 7 },
  { account_name: 'Tax', account_number: '10130', class_id: 1 },
  { account_name: 'Taxes & Fees Dues', account_number: '44110', class_id: 4 },
  { account_name: 'Taxes On Profits', account_number: '44310', class_id: 4 },
  { account_name: 'Technical Installations& Industrial Machinery', account_number: '28240', class_id: 2 },
  { account_name: 'Technical Installations,Industrial', account_number: '22400', class_id: 2 },
  { account_name: 'Technical,Install.& Industrial Tools & Equipment', account_number: '22740', class_id: 2 },
  { account_name: 'Trade Marks', account_number: '62560', class_id: 6 },
  { account_name: 'Trade Marks & Similar Items', account_number: '29110', class_id: 2 },
  { account_name: 'Training & Education', account_number: '62660', class_id: 6 },
  { account_name: 'Transport & Communication', account_number: '62610', class_id: 6 },
  { account_name: 'Transport Equipment', account_number: '22500', class_id: 2 },
  { account_name: 'Transport-Vehicles', account_number: '28250', class_id: 2 },
  { account_name: 'Tva Collectes', account_number: '44270', class_id: 4 },
  { account_name: 'Tva Deductibles', account_number: '44260', class_id: 4 },
  { account_name: 'Unearned Revenue', account_number: '47310', class_id: 4 },
  { account_name: 'Unissued Participations', account_number: '46310', class_id: 4 },
  { account_name: 'Variation', account_number: '40120', class_id: 4 },
  { account_name: 'Variations', account_number: '70120', class_id: 7 },
  { account_name: 'Vat Deductible*', account_number: '44269', class_id: 4 },
  { account_name: 'Vat Payables*', account_number: '44111', class_id: 4 },
  { account_name: 'Wages', account_number: '63120', class_id: 6 },
  { account_name: 'Wages And Salaries Due To Staff', account_number: '42110', class_id: 4 },
  { account_name: 'Work In Progress', account_number: '72120', class_id: 7 }
];

export const LEBANESE_SUB_CLASSES_3: CoaAccountHeader[] = [
  { account_name: 'Accounts Receivable On Participations', account_number: '252', class_id: 2 },
  { account_name: 'Accrued Charges', account_number: '472', class_id: 4 },
  { account_name: 'Added Value', account_number: '192', class_id: 1 },
  { account_name: 'Advances On Purchase Of Tangible Fixed Assets', account_number: '228', class_id: 2 },
  { account_name: 'Advances Received On Purchase Order In Progre', account_number: '419', class_id: 4 },
  { account_name: 'Advances To Suppliers Of Goods', account_number: '409', class_id: 4 },
  { account_name: 'Amortisation & Provisions', account_number: '679', class_id: 6 },
  { account_name: 'Amortisation Of Keymoney,Goodwill...', account_number: '280', class_id: 2 },
  { account_name: 'Amortisation Of Other Intangible Fixed Assets', account_number: '281', class_id: 2 },
  { account_name: 'Amounts Due By Social Security Establishments', account_number: '438', class_id: 4 },
  { account_name: 'Amounts Due From Staff', account_number: '428', class_id: 4 },
  { account_name: 'Amounts Due To Social Security Establishments', account_number: '431', class_id: 4 },
  { account_name: 'Amounts Due To Staff', account_number: '421', class_id: 4 },
  { account_name: 'Amounts Receivable From Partners', account_number: '459', class_id: 4 },
  { account_name: 'Balances Payable On Financial Fixed Assets', account_number: '463', class_id: 4 },
  { account_name: 'Banks', account_number: '512', class_id: 5 },
  { account_name: 'Billings', account_number: '701', class_id: 7 },
  { account_name: 'Billings.', account_number: '711', class_id: 7 },
  { account_name: 'Bills Receivable - Customers', account_number: '413', class_id: 4 },
  { account_name: 'Bought Ledger ( Suppliers Of Goods)', account_number: '401', class_id: 4 },
  { account_name: 'Buildings', account_number: '223', class_id: 2 },
  { account_name: 'Capital', account_number: '101', class_id: 1 },
  { account_name: 'Cash', account_number: '530', class_id: 5 },
  { account_name: 'Changes In Goods On Hand', account_number: '605', class_id: 6 },
  { account_name: 'Charges To Branches', account_number: '186', class_id: 1 },
  { account_name: 'Cheques & Orders To Receive', account_number: '511', class_id: 5 },
  { account_name: 'Commercial Margin', account_number: '191', class_id: 1 },
  { account_name: 'Consumables', account_number: '315', class_id: 3 },
  { account_name: 'Current Results Before Tax', account_number: '195', class_id: 1 },
  { account_name: 'Debentures Issued By The Company', account_number: '505', class_id: 5 },
  { account_name: 'Deferred Charges', account_number: '471', class_id: 4 },
  { account_name: 'Depreciation And Amortisation', account_number: '651', class_id: 6 },
  { account_name: 'Depreciation Of Tangible Fixed Assets', account_number: '282', class_id: 2 },
  { account_name: 'Discount Allowed', account_number: '719', class_id: 7 },
  { account_name: 'Discounts Allowed', account_number: '709', class_id: 7 },
  { account_name: 'Dividends Payable', account_number: '453', class_id: 4 },
  { account_name: 'E D L', account_number: '474', class_id: 4 },
  { account_name: 'Establishment Expenses', account_number: '212', class_id: 2 },
  { account_name: 'Exchange Difference-Assets', account_number: '476', class_id: 4 },
  { account_name: 'Exchange Difference-Liabilities', account_number: '475', class_id: 4 },
  { account_name: 'External Services', account_number: '626', class_id: 6 },
  { account_name: 'Financial Fixed Assets', account_number: '250', class_id: 2 },
  { account_name: 'Financing Institutions', account_number: '519', class_id: 5 },
  { account_name: 'Finished Goods', account_number: '355', class_id: 3 },
  { account_name: 'For Goods', account_number: '741', class_id: 7 },
  { account_name: 'For Production', account_number: '742', class_id: 7 },
  { account_name: 'Goods And Work In Progress', account_number: '721', class_id: 7 },
  { account_name: 'Goods For Resale', account_number: '371', class_id: 3 },
  { account_name: 'Goods For Resale.', account_number: '372', class_id: 3 },
  { account_name: 'Goods Produced', account_number: '725', class_id: 7 },
  { account_name: 'Gross Operating Profits/Losses', account_number: '193', class_id: 1 },
  { account_name: 'Gross Profit/Loss Before Financ. Charges & In', account_number: '194', class_id: 1 },
  { account_name: 'Hire Purchase ...', account_number: '625', class_id: 6 },
  { account_name: 'Income From Disposal Of Fixed Assets', account_number: '781', class_id: 7 },
  { account_name: 'Income Tax', account_number: '690', class_id: 6 },
  { account_name: 'Individual Accounts', account_number: '181', class_id: 1 },
  { account_name: 'Intangible Fixed Assets', account_number: '731', class_id: 7 },
  { account_name: 'Interest & Similar Charges', account_number: '673', class_id: 6 },
  { account_name: 'Interest And Similar Income', account_number: '773', class_id: 7 },
  { account_name: 'Intermediary Products ( Semi Finished Goods)', account_number: '351', class_id: 3 },
  { account_name: 'Investment Aids Transferred To Current Operat', account_number: '785', class_id: 7 },
  { account_name: 'Invoices In Progress', account_number: '418', class_id: 4 },
  { account_name: 'Keymoney,Goodwill,Clientele...', account_number: '211', class_id: 2 },
  { account_name: 'Land', account_number: '221', class_id: 2 },
  { account_name: 'Legal Reserves', account_number: '111', class_id: 1 },
  { account_name: 'Loan From Lending Establishments', account_number: '162', class_id: 1 },
  { account_name: 'Loans Against Debenture Bonds', account_number: '161', class_id: 1 },
  { account_name: 'Long & Medium Term Loans', account_number: '255', class_id: 2 },
  { account_name: 'Loss On Exchange', account_number: '675', class_id: 6 },
  { account_name: 'Losses Brought Forward', account_number: '125', class_id: 1 },
  { account_name: 'Municipality Taxes', account_number: '642', class_id: 6 },
  { account_name: 'Net Book Amount Of Fixed Assets Disposed Of', account_number: '681', class_id: 6 },
  { account_name: 'Net Loss On Disposal Of Investment Securities', account_number: '676', class_id: 6 },
  { account_name: 'New Result Eoy', account_number: '132', class_id: 1 },
  { account_name: 'New Result For Year', account_number: '131', class_id: 1 },
  { account_name: 'Non - Operating Taxes', account_number: '443', class_id: 4 },
  { account_name: 'Non-Operating Creditors', account_number: '465', class_id: 4 },
  { account_name: 'Non-Operating Debtors', account_number: '469', class_id: 4 },
  { account_name: 'Non-Operating Depreciation, Amortisation&Prov', account_number: '689', class_id: 6 },
  { account_name: 'Non-Operating Results', account_number: '196', class_id: 1 },
  { account_name: 'On Salaries, Wages And Fees', account_number: '641', class_id: 6 },
  { account_name: 'Operating Creditors', account_number: '461', class_id: 4 },
  { account_name: 'Operating Debtors', account_number: '468', class_id: 4 },
  { account_name: 'Operating Taxes', account_number: '441', class_id: 4 },
  { account_name: 'Other Administrative Expenses', account_number: '661', class_id: 6 },
  { account_name: 'Other Amounts Due To Partners', account_number: '455', class_id: 4 },
  { account_name: 'Other Financial Revenue', account_number: '778', class_id: 7 },
  { account_name: 'Other Fixed Accounts Receivable', account_number: '259', class_id: 2 },
  { account_name: 'Other Fixed Investments', account_number: '253', class_id: 2 },
  { account_name: 'Other Intangible Fixed Assets', account_number: '219', class_id: 2 },
  { account_name: 'Other Loans & Debts', account_number: '168', class_id: 1 },
  { account_name: 'Other Non-Operating Charges', account_number: '685', class_id: 6 },
  { account_name: 'Other Non-Operating Charges.', account_number: '788', class_id: 7 },
  { account_name: 'Other Ordinary Operating Income', account_number: '761', class_id: 7 },
  { account_name: 'Other Payables-State & Public Establishments', account_number: '445', class_id: 4 },
  { account_name: 'Other Tangible Fixed Assets', account_number: '226', class_id: 2 },
  { account_name: 'Others', account_number: '645', class_id: 6 },
  { account_name: 'Others Reserves', account_number: '119', class_id: 1 },
  { account_name: 'Participation Investments', account_number: '251', class_id: 2 },
  { account_name: 'Partners Current Accounts-Receivable&Payable', account_number: '451', class_id: 4 },
  { account_name: 'Patents,Licenses,Copy Rights & Similar Items', account_number: '214', class_id: 2 },
  { account_name: 'Personnel Salaries & Wages', account_number: '631', class_id: 6 },
  { account_name: 'Prepaid Charges ( Subscriptions)', account_number: '481', class_id: 4 },
  { account_name: 'Products In Progress', account_number: '331', class_id: 3 },
  { account_name: 'Profit Brought Forward', account_number: '121', class_id: 1 },
  { account_name: 'Profit On Exchange', account_number: '775', class_id: 7 },
  { account_name: 'Proprietory Shares', account_number: '502', class_id: 5 },
  { account_name: 'Prov.For Diminut. In Value Of Financ.Fixed As', account_number: '295', class_id: 2 },
  { account_name: 'Prov.For Diminut. In Value Of Production In H', account_number: '395', class_id: 3 },
  { account_name: 'Prov.For Diminut.In Value Of Customers A/C Re', account_number: '491', class_id: 4 },
  { account_name: 'Prov.For Diminut.In Value Of Raw Material&Con', account_number: '391', class_id: 3 },
  { account_name: 'Prov.For Diminut.In Value Of Sundry A/C Recei', account_number: '496', class_id: 4 },
  { account_name: 'Prov.For Diminution In Value Of Goods In Hand', account_number: '397', class_id: 3 },
  { account_name: 'Prov.For Diminution In Value Of Intang.Fixed ', account_number: '291', class_id: 2 },
  { account_name: 'Prov.For Diminution In Value Of Keymoney,Good', account_number: '290', class_id: 2 },
  { account_name: 'Prov.For Diminution In Value Of Partner`S Acc', account_number: '495', class_id: 4 },
  { account_name: 'Prov.For Diminution In Value Of Tang.Fixed As', account_number: '292', class_id: 2 },
  { account_name: 'Prov.For Diminution In Value Of Work In Progr', account_number: '393', class_id: 3 },
  { account_name: 'Provisions', account_number: '655', class_id: 6 },
  { account_name: 'Provisions For Charges', account_number: '155', class_id: 1 },
  { account_name: 'Provisions For Contingencies', account_number: '151', class_id: 1 },
  { account_name: 'Purchase Of Goods', account_number: '601', class_id: 6 },
  { account_name: 'Purchase Of Own Issued Shares', account_number: '501', class_id: 5 },
  { account_name: 'Purchases From Sub-Contractors', account_number: '621', class_id: 6 },
  { account_name: 'Purchases Of Stores', account_number: '611', class_id: 6 },
  { account_name: 'Raw Materials', account_number: '311', class_id: 3 },
  { account_name: 'Receivables From State & Public Establishment', account_number: '449', class_id: 4 },
  { account_name: 'Registration Fees', account_number: '644', class_id: 6 },
  { account_name: 'Regularisation Accounts', account_number: '470', class_id: 4 },
  { account_name: 'Release Of Financial Provisions', account_number: '779', class_id: 7 },
  { account_name: 'Release Of Non-Operating Provisions', account_number: '789', class_id: 7 },
  { account_name: 'Release Of Prov.For Diminut.In Value Of Cur.A', account_number: '753', class_id: 7 },
  { account_name: 'Release Of Prov.For Diminut.In Value Of Fixed', account_number: '752', class_id: 7 },
  { account_name: 'Release Of Provision For Diminution In Value', account_number: '768', class_id: 7 },
  { account_name: 'Research & Development Cost', account_number: '213', class_id: 2 },
  { account_name: 'Research In Progress', account_number: '335', class_id: 3 },
  { account_name: 'Residuals', account_number: '358', class_id: 3 },
  { account_name: 'Results For The Year', account_number: '197', class_id: 1 },
  { account_name: 'Results For The Year-Losses', account_number: '139', class_id: 1 },
  { account_name: 'Results For The Year-Profits', account_number: '138', class_id: 1 },
  { account_name: 'Revenue From Branches', account_number: '187', class_id: 1 },
  { account_name: 'Revenue From Other Investments', account_number: '772', class_id: 7 },
  { account_name: 'Revenue From Participation Investments', account_number: '771', class_id: 7 },
  { account_name: 'Revenue Of Ancilliary Activities', account_number: '717', class_id: 7 },
  { account_name: 'Sales Ledger ( Debtors From Sales)', account_number: '411', class_id: 4 },
  { account_name: 'Services', account_number: '713', class_id: 7 },
  { account_name: 'Services In Progress', account_number: '336', class_id: 3 },
  { account_name: 'Services In Progress.', account_number: '722', class_id: 7 },
  { account_name: 'Share Of Loss On Joint Ventures', account_number: '665', class_id: 6 },
  { account_name: 'Share Of Profits On Joint Ventures', account_number: '765', class_id: 7 },
  { account_name: 'Social Security Charges', account_number: '635', class_id: 6 },
  { account_name: 'Statuory And Contractual Reserves', account_number: '112', class_id: 1 },
  { account_name: 'Stock', account_number: '347', class_id: 3 },
  { account_name: 'Suppliers Of Fixed Assets', account_number: '403', class_id: 4 },
  { account_name: 'Tangible Fixed Assets', account_number: '222', class_id: 2 },
  { account_name: 'Tangible Fixed Assets Under Construction', account_number: '227', class_id: 2 },
  { account_name: 'Tangible Fixed Assets.', account_number: '732', class_id: 7 },
  { account_name: 'Taxes On Non-Returnable Sales', account_number: '643', class_id: 6 },
  { account_name: 'Technical Installation & Industrial Machinery', account_number: '224', class_id: 2 },
  { account_name: 'Title Deeds To Right Of Recourse To Debts', account_number: '506', class_id: 5 },
  { account_name: 'Transport - Vehicles', account_number: '225', class_id: 2 },
  { account_name: 'Unbilled Accounts Receivable', account_number: '415', class_id: 4 },
  { account_name: 'Unearned Income ( Subscriptions)', account_number: '482', class_id: 4 },
  { account_name: 'Unearned Revenue', account_number: '473', class_id: 4 },
  { account_name: 'Variation Of Raw Material & Consumables', account_number: '615', class_id: 6 },
  { account_name: 'VAT', account_number: '442', class_id: 4 },
  { account_name: 'Work', account_number: '712', class_id: 7 },
  { account_name: 'Work In Progress', account_number: '332', class_id: 3 }
];
