// Authentic Omega ERP Inventory Divisions Data & Types

export interface InventoryDivisionItem {
  ID: number;
  DIVISIONID: number;
  BRAND_ID: number;
  BRANCHID: number;
  DIVISIONNAME: string;
  ADIVISIONNAME: string | null;
  CATEGORYID: number;
  CATEGORYNAME: string;
  SORTING: number;
  PIC: string | null;
  PLU: number | null;
  CREATED_AT: string;
  UPDATED_AT: string;
  UPDATED_BY: number;
}

export interface DivisionCategoryOption {
  CATEGORYID: number;
  CATEGORYNAME: string;
}

export const OMEGA_DIVISION_CATEGORIES: DivisionCategoryOption[] = [
  { CATEGORYID: 2, CATEGORYNAME: 'مفرق' },
  { CATEGORYID: 3, CATEGORYNAME: 'جملة' },
  { CATEGORYID: 4, CATEGORYNAME: 'عروض' },
  { CATEGORYID: 5, CATEGORYNAME: 'مواد اولية' },
  { CATEGORYID: 6, CATEGORYNAME: 'Raw Materials' }
];

export const INITIAL_OMEGA_INV_DIVISIONS: InventoryDivisionItem[] = [
  {
    "ID": 51,
    "DIVISIONID": 48,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "Assembled Items",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 48,
    "PIC": null,
    "PLU": 22,
    "CREATED_AT": "14 Jul, 2026",
    "UPDATED_AT": "14 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 45,
    "DIVISIONID": 42,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "Bottles",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 42,
    "PIC": null,
    "PLU": 21,
    "CREATED_AT": "11 Jul, 2026",
    "UPDATED_AT": "15 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 48,
    "DIVISIONID": 45,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "Demijohns",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 45,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "11 Jul, 2026",
    "UPDATED_AT": "11 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 44,
    "DIVISIONID": 41,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "Jars",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 41,
    "PIC": null,
    "PLU": 20,
    "CREATED_AT": "11 Jul, 2026",
    "UPDATED_AT": "11 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 50,
    "DIVISIONID": 47,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "Main Materials",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 47,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "12 Jul, 2026",
    "UPDATED_AT": "12 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 52,
    "DIVISIONID": 49,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "Plastic",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 49,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "14 Jul, 2026",
    "UPDATED_AT": "14 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 49,
    "DIVISIONID": 46,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "SERVICES",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 46,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "11 Jul, 2026",
    "UPDATED_AT": "11 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 47,
    "DIVISIONID": 44,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "Sprout",
    "ADIVISIONNAME": null,
    "CATEGORYID": 6,
    "CATEGORYNAME": "Raw Materials",
    "SORTING": 44,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "11 Jul, 2026",
    "UPDATED_AT": "11 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 20,
    "DIVISIONID": 18,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "زيتون جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 18,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 37,
    "DIVISIONID": 35,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "زيوت جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 35,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "28 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 22,
    "DIVISIONID": 20,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "عسل جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 20,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 24,
    "DIVISIONID": 22,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "فواكه مجففه جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 22,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 21,
    "DIVISIONID": 19,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "كبيس ومخللات جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 19,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 23,
    "DIVISIONID": 21,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "كيلو جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 21,
    "PIC": null,
    "PLU": 2,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "24 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 25,
    "DIVISIONID": 23,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مربيات جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 23,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 18,
    "DIVISIONID": 16,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مقطرات ومدبسات جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 16,
    "PIC": null,
    "PLU": 15,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 39,
    "DIVISIONID": 37,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مكعزلة جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 37,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "28 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 19,
    "DIVISIONID": 17,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مونة بلدية جملة",
    "ADIVISIONNAME": null,
    "CATEGORYID": 3,
    "CATEGORYNAME": "جملة",
    "SORTING": 17,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 40,
    "DIVISIONID": 38,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "عروض",
    "ADIVISIONNAME": null,
    "CATEGORYID": 4,
    "CATEGORYNAME": "عروض",
    "SORTING": 38,
    "PIC": null,
    "PLU": 19,
    "CREATED_AT": "02 Jan, 2026",
    "UPDATED_AT": "02 Jan, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 29,
    "DIVISIONID": 27,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "براد",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 27,
    "PIC": null,
    "PLU": 8,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "21 Jan, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 26,
    "DIVISIONID": 24,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "بهارات مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 24,
    "PIC": null,
    "PLU": 9,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 9,
    "DIVISIONID": 7,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "زيتون مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 7,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 35,
    "DIVISIONID": 33,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "زيوت مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 33,
    "PIC": null,
    "PLU": 12,
    "CREATED_AT": "28 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 12,
    "DIVISIONID": 10,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "عسل مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 10,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 13,
    "DIVISIONID": 11,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "فواكه مجففه مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 11,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 10,
    "DIVISIONID": 8,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "كبيس ومخللات مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 8,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 42,
    "DIVISIONID": 39,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "كيلو مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 39,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "02 Apr, 2026",
    "UPDATED_AT": "02 Apr, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 32,
    "DIVISIONID": 30,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مجففات",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 30,
    "PIC": null,
    "PLU": 7,
    "CREATED_AT": "12 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 36,
    "DIVISIONID": 34,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "محمصة مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 34,
    "PIC": null,
    "PLU": 18,
    "CREATED_AT": "28 Dec, 2025",
    "UPDATED_AT": "29 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 11,
    "DIVISIONID": 9,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مربيات مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 9,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  },
  {
    "ID": 43,
    "DIVISIONID": 40,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مرطبان",
    "ADIVISIONNAME": "Jar",
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 40,
    "PIC": null,
    "PLU": null,
    "CREATED_AT": "02 Jul, 2026",
    "UPDATED_AT": "02 Jul, 2026",
    "UPDATED_BY": 1
  },
  {
    "ID": 33,
    "DIVISIONID": 31,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مقرمشات",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 31,
    "PIC": null,
    "PLU": 10,
    "CREATED_AT": "12 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 7,
    "DIVISIONID": 5,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 1,
    "PIC": null,
    "PLU": 16,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 38,
    "DIVISIONID": 36,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مكعزلة مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 36,
    "PIC": null,
    "PLU": 17,
    "CREATED_AT": "28 Dec, 2025",
    "UPDATED_AT": "28 Dec, 2025",
    "UPDATED_BY": 1
  },
  {
    "ID": 8,
    "DIVISIONID": 6,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "DIVISIONNAME": "مونة بلدية مفرق",
    "ADIVISIONNAME": null,
    "CATEGORYID": 2,
    "CATEGORYNAME": "مفرق",
    "SORTING": 6,
    "PIC": null,
    "PLU": 1,
    "CREATED_AT": "08 Dec, 2025",
    "UPDATED_AT": "08 Dec, 2025",
    "UPDATED_BY": 2
  }
];
