// Authentic Omega ERP Inventory Groups Data & Types

export interface InventoryGroupItem {
  ID: number;
  GROUPID: number;
  BRAND_ID: number;
  BRANCHID: number;
  GROUPNAME: string;
  AGROUPNAME: string | null;
  OTHERDESC: string;
  DIVISIONID: number;
  DIVISIONNAME: string;
  SORTING: number;
  itemsCount: number;
  ECOM_PIC: string | null;
  MASTER_ITEM: number;
  TAX1: boolean;
  TAX2: boolean;
  TAX3: boolean;
  TAX4: boolean;
  TAX5: boolean;
  TAX6: boolean;
  ASSETACCOUNT: number;
  REVENUEACCOUNT: number;
  EXPENSEACCOUNT: number;
  STOCKVARIATIONACC: number;
  AUTDISC: number;
  CREATED_AT: string;
  UPDATED_AT: string;
  RAW_CREATED_AT?: string;
  RAW_UPDATED_AT?: string;
  UPDATED_BY: number;
}

export interface GroupDivisionOption {
  DIVISIONID: number;
  DIVISIONNAME: string;
}

export const OMEGA_GROUP_DIVISIONS: GroupDivisionOption[] = [
  {
    "DIVISIONID": 5,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق"
  },
  {
    "DIVISIONID": 6,
    "DIVISIONNAME": "مونة بلدية مفرق"
  },
  {
    "DIVISIONID": 7,
    "DIVISIONNAME": "زيتون مفرق"
  },
  {
    "DIVISIONID": 8,
    "DIVISIONNAME": "كبيس ومخللات مفرق"
  },
  {
    "DIVISIONID": 9,
    "DIVISIONNAME": "مربيات مفرق"
  },
  {
    "DIVISIONID": 10,
    "DIVISIONNAME": "عسل مفرق"
  },
  {
    "DIVISIONID": 11,
    "DIVISIONNAME": "فواكه مجففه مفرق"
  },
  {
    "DIVISIONID": 16,
    "DIVISIONNAME": "مقطرات ومدبسات جملة"
  },
  {
    "DIVISIONID": 17,
    "DIVISIONNAME": "مونة بلدية جملة"
  },
  {
    "DIVISIONID": 18,
    "DIVISIONNAME": "زيتون جملة"
  },
  {
    "DIVISIONID": 19,
    "DIVISIONNAME": "كبيس ومخللات جملة"
  },
  {
    "DIVISIONID": 20,
    "DIVISIONNAME": "عسل جملة"
  },
  {
    "DIVISIONID": 21,
    "DIVISIONNAME": "كيلو جملة"
  },
  {
    "DIVISIONID": 22,
    "DIVISIONNAME": "فواكه مجففه جملة"
  },
  {
    "DIVISIONID": 23,
    "DIVISIONNAME": "مربيات جملة"
  },
  {
    "DIVISIONID": 24,
    "DIVISIONNAME": "بهارات مفرق"
  },
  {
    "DIVISIONID": 27,
    "DIVISIONNAME": "براد"
  },
  {
    "DIVISIONID": 30,
    "DIVISIONNAME": "مجففات"
  },
  {
    "DIVISIONID": 31,
    "DIVISIONNAME": "مقرمشات"
  },
  {
    "DIVISIONID": 33,
    "DIVISIONNAME": "زيوت مفرق"
  },
  {
    "DIVISIONID": 34,
    "DIVISIONNAME": "محمصة مفرق"
  },
  {
    "DIVISIONID": 35,
    "DIVISIONNAME": "زيوت جملة"
  },
  {
    "DIVISIONID": 36,
    "DIVISIONNAME": "مكعزلة مفرق"
  },
  {
    "DIVISIONID": 37,
    "DIVISIONNAME": "مكعزلة جملة"
  },
  {
    "DIVISIONID": 38,
    "DIVISIONNAME": "عروض"
  },
  {
    "DIVISIONID": 39,
    "DIVISIONNAME": "كيلو مفرق"
  },
  {
    "DIVISIONID": 40,
    "DIVISIONNAME": "مرطبان"
  },
  {
    "DIVISIONID": 41,
    "DIVISIONNAME": "Jars"
  },
  {
    "DIVISIONID": 42,
    "DIVISIONNAME": "Bottles"
  },
  {
    "DIVISIONID": 44,
    "DIVISIONNAME": "Sprout"
  },
  {
    "DIVISIONID": 45,
    "DIVISIONNAME": "Demijohns"
  },
  {
    "DIVISIONID": 46,
    "DIVISIONNAME": "SERVICES"
  },
  {
    "DIVISIONID": 47,
    "DIVISIONNAME": "Main Materials"
  },
  {
    "DIVISIONID": 48,
    "DIVISIONNAME": "Assembled Items"
  },
  {
    "DIVISIONID": 49,
    "DIVISIONNAME": "Plastic"
  }
];

export const INITIAL_OMEGA_INV_GROUPS: InventoryGroupItem[] = [
  {
    "ID": 67,
    "GROUPID": 65,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "509 مرطبان",
    "AGROUPNAME": null,
    "OTHERDESC": "509 مرطبان",
    "DIVISIONID": 40,
    "DIVISIONNAME": "مرطبان",
    "SORTING": 65,
    "itemsCount": 65,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "26 Mar 2026",
    "UPDATED_AT": "02 Jul 2026",
    "RAW_CREATED_AT": "2026-03-26 09:01:46",
    "RAW_UPDATED_AT": "2026-07-02 14:06:59",
    "UPDATED_BY": 1
  },
  {
    "ID": 77,
    "GROUPID": 75,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "Assembled Items Per 1",
    "AGROUPNAME": null,
    "OTHERDESC": "Assembled Items Per 1",
    "DIVISIONID": 48,
    "DIVISIONNAME": "Assembled Items",
    "SORTING": 75,
    "itemsCount": 18,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "14 Jul 2026",
    "UPDATED_AT": "14 Jul 2026",
    "RAW_CREATED_AT": "2026-07-14 09:01:01",
    "RAW_UPDATED_AT": "2026-07-14 09:01:01",
    "UPDATED_BY": 1
  },
  {
    "ID": 72,
    "GROUPID": 70,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "Bottles",
    "AGROUPNAME": null,
    "OTHERDESC": "Bottles",
    "DIVISIONID": 42,
    "DIVISIONNAME": "Bottles",
    "SORTING": 70,
    "itemsCount": 11,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "11 Jul 2026",
    "UPDATED_AT": "15 Jul 2026",
    "RAW_CREATED_AT": "2026-07-11 11:55:47",
    "RAW_UPDATED_AT": "2026-07-15 06:25:55",
    "UPDATED_BY": 1
  },
  {
    "ID": 79,
    "GROUPID": 77,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "CLASSIC-C/R",
    "AGROUPNAME": null,
    "OTHERDESC": "CLASSIC-C/R",
    "DIVISIONID": 33,
    "DIVISIONNAME": "زيوت مفرق",
    "SORTING": 77,
    "itemsCount": 6,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "25 Jul 2026",
    "UPDATED_AT": "25 Jul 2026",
    "RAW_CREATED_AT": "2026-07-25 18:02:26",
    "RAW_UPDATED_AT": "2026-07-25 18:02:26",
    "UPDATED_BY": 1
  },
  {
    "ID": 80,
    "GROUPID": 78,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "CLASSIC-R/R",
    "AGROUPNAME": null,
    "OTHERDESC": "CLASSIC-R/R",
    "DIVISIONID": 33,
    "DIVISIONNAME": "زيوت مفرق",
    "SORTING": 78,
    "itemsCount": 4,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "25 Jul 2026",
    "UPDATED_AT": "25 Jul 2026",
    "RAW_CREATED_AT": "2026-07-25 18:08:04",
    "RAW_UPDATED_AT": "2026-07-25 18:08:04",
    "UPDATED_BY": 1
  },
  {
    "ID": 73,
    "GROUPID": 71,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "Demijohn",
    "AGROUPNAME": null,
    "OTHERDESC": "Demijohn",
    "DIVISIONID": 45,
    "DIVISIONNAME": "Demijohns",
    "SORTING": 71,
    "itemsCount": 6,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "11 Jul 2026",
    "UPDATED_AT": "11 Jul 2026",
    "RAW_CREATED_AT": "2026-07-11 12:20:03",
    "RAW_UPDATED_AT": "2026-07-11 12:20:03",
    "UPDATED_BY": 1
  },
  {
    "ID": 71,
    "GROUPID": 69,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "JAR",
    "AGROUPNAME": null,
    "OTHERDESC": "JAR",
    "DIVISIONID": 41,
    "DIVISIONNAME": "Jars",
    "SORTING": 69,
    "itemsCount": 8,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "11 Jul 2026",
    "UPDATED_AT": "11 Jul 2026",
    "RAW_CREATED_AT": "2026-07-11 11:48:06",
    "RAW_UPDATED_AT": "2026-07-11 11:48:06",
    "UPDATED_BY": 1
  },
  {
    "ID": 75,
    "GROUPID": 73,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "Main materials",
    "AGROUPNAME": null,
    "OTHERDESC": "Main materials",
    "DIVISIONID": 47,
    "DIVISIONNAME": "Main Materials",
    "SORTING": 73,
    "itemsCount": 15,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "12 Jul 2026",
    "UPDATED_AT": "12 Jul 2026",
    "RAW_CREATED_AT": "2026-07-12 17:23:29",
    "RAW_UPDATED_AT": "2026-07-12 17:23:29",
    "UPDATED_BY": 1
  },
  {
    "ID": 78,
    "GROUPID": 76,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "Plastic Bottles",
    "AGROUPNAME": null,
    "OTHERDESC": "Plastic Bottles",
    "DIVISIONID": 49,
    "DIVISIONNAME": "Plastic",
    "SORTING": 76,
    "itemsCount": 2,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "14 Jul 2026",
    "UPDATED_AT": "14 Jul 2026",
    "RAW_CREATED_AT": "2026-07-14 09:06:57",
    "RAW_UPDATED_AT": "2026-07-14 09:06:57",
    "UPDATED_BY": 1
  },
  {
    "ID": 76,
    "GROUPID": 74,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "Plastic Gallon",
    "AGROUPNAME": null,
    "OTHERDESC": "Plastic Gallon",
    "DIVISIONID": 49,
    "DIVISIONNAME": "Plastic",
    "SORTING": 74,
    "itemsCount": 4,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "13 Jul 2026",
    "UPDATED_AT": "14 Jul 2026",
    "RAW_CREATED_AT": "2026-07-13 08:49:45",
    "RAW_UPDATED_AT": "2026-07-14 09:04:57",
    "UPDATED_BY": 1
  },
  {
    "ID": 74,
    "GROUPID": 72,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "SERVICES",
    "AGROUPNAME": null,
    "OTHERDESC": "SERVICES",
    "DIVISIONID": 46,
    "DIVISIONNAME": "SERVICES",
    "SORTING": 72,
    "itemsCount": 3,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "11 Jul 2026",
    "UPDATED_AT": "11 Jul 2026",
    "RAW_CREATED_AT": "2026-07-11 14:14:09",
    "RAW_UPDATED_AT": "2026-07-11 14:14:09",
    "UPDATED_BY": 1
  },
  {
    "ID": 35,
    "GROUPID": 35,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "أجبان و ألبان",
    "AGROUPNAME": null,
    "OTHERDESC": "أجبان و ألبان",
    "DIVISIONID": 27,
    "DIVISIONNAME": "براد",
    "SORTING": 35,
    "itemsCount": 33,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "14 Dec 2025",
    "UPDATED_AT": "14 Dec 2025",
    "RAW_CREATED_AT": "2025-12-14 18:42:25",
    "RAW_UPDATED_AT": "2025-12-14 18:42:25",
    "UPDATED_BY": 1
  },
  {
    "ID": 51,
    "GROUPID": 49,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "بزورات مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "بزورات مفرق",
    "DIVISIONID": 34,
    "DIVISIONNAME": "محمصة مفرق",
    "SORTING": 49,
    "itemsCount": 16,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "29 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 20:18:51",
    "RAW_UPDATED_AT": "2025-12-29 13:50:11",
    "UPDATED_BY": 1
  },
  {
    "ID": 27,
    "GROUPID": 27,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "بهارات غ",
    "AGROUPNAME": null,
    "OTHERDESC": "بهارات غ",
    "DIVISIONID": 24,
    "DIVISIONNAME": "بهارات مفرق",
    "SORTING": 27,
    "itemsCount": 91,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 14:39:55",
    "RAW_UPDATED_AT": "2025-12-28 19:12:38",
    "UPDATED_BY": 1
  },
  {
    "ID": 6,
    "GROUPID": 6,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "تمور",
    "AGROUPNAME": null,
    "OTHERDESC": "تمور",
    "DIVISIONID": 6,
    "DIVISIONNAME": "مونة بلدية مفرق",
    "SORTING": 6,
    "itemsCount": 25,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "07 Apr 2026",
    "RAW_CREATED_AT": "2025-12-08 11:25:40",
    "RAW_UPDATED_AT": "2026-04-07 14:51:22",
    "UPDATED_BY": 1
  },
  {
    "ID": 30,
    "GROUPID": 30,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "جبنة مطبوخة",
    "AGROUPNAME": null,
    "OTHERDESC": "جبنة مطبوخة",
    "DIVISIONID": 27,
    "DIVISIONNAME": "براد",
    "SORTING": 30,
    "itemsCount": 17,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "10 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-10 22:04:29",
    "RAW_UPDATED_AT": "2025-12-28 18:25:30",
    "UPDATED_BY": 1
  },
  {
    "ID": 1,
    "GROUPID": 1,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "حبوب فلت",
    "AGROUPNAME": null,
    "OTHERDESC": "حبوب فلت",
    "DIVISIONID": 6,
    "DIVISIONNAME": "مونة بلدية مفرق",
    "SORTING": 1,
    "itemsCount": 37,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "07 Dec 2025",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2025-12-07 12:32:07",
    "RAW_UPDATED_AT": "2026-01-21 16:13:07",
    "UPDATED_BY": 1
  },
  {
    "ID": 61,
    "GROUPID": 59,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "حبوب مكيسة",
    "AGROUPNAME": null,
    "OTHERDESC": "حبوب مكيسة",
    "DIVISIONID": 6,
    "DIVISIONNAME": "مونة بلدية مفرق",
    "SORTING": 59,
    "itemsCount": 30,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "21 Jan 2026",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2026-01-21 16:15:42",
    "RAW_UPDATED_AT": "2026-01-21 16:15:42",
    "UPDATED_BY": 1
  },
  {
    "ID": 58,
    "GROUPID": 56,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "حلوى",
    "AGROUPNAME": null,
    "OTHERDESC": "حلوى",
    "DIVISIONID": 34,
    "DIVISIONNAME": "محمصة مفرق",
    "SORTING": 56,
    "itemsCount": 10,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "29 Dec 2025",
    "UPDATED_AT": "29 Dec 2025",
    "RAW_CREATED_AT": "2025-12-29 15:17:16",
    "RAW_UPDATED_AT": "2025-12-29 15:17:16",
    "UPDATED_BY": 1
  },
  {
    "ID": 66,
    "GROUPID": 64,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "رف",
    "AGROUPNAME": null,
    "OTHERDESC": "رف",
    "DIVISIONID": 6,
    "DIVISIONNAME": "مونة بلدية مفرق",
    "SORTING": 64,
    "itemsCount": 59,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "21 Jan 2026",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2026-01-21 18:01:01",
    "RAW_UPDATED_AT": "2026-01-21 18:01:01",
    "UPDATED_BY": 1
  },
  {
    "ID": 15,
    "GROUPID": 15,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيت اوكراني دوار الشمس جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "زيت اوكراني دوار الشمس جملة",
    "DIVISIONID": 35,
    "DIVISIONNAME": "زيوت جملة",
    "SORTING": 15,
    "itemsCount": 3,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:27:06",
    "RAW_UPDATED_AT": "2025-12-28 18:26:26",
    "UPDATED_BY": 1
  },
  {
    "ID": 4,
    "GROUPID": 4,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيت اوكراني دوار الشمس مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "زيت اوكراني دوار الشمس مفرق",
    "DIVISIONID": 33,
    "DIVISIONNAME": "زيوت مفرق",
    "SORTING": 4,
    "itemsCount": 4,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:25:01",
    "RAW_UPDATED_AT": "2025-12-28 17:11:00",
    "UPDATED_BY": 1
  },
  {
    "ID": 40,
    "GROUPID": 40,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيت زيتون خضير جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "زيت زيتون خضير جملة",
    "DIVISIONID": 35,
    "DIVISIONNAME": "زيوت جملة",
    "SORTING": 40,
    "itemsCount": 17,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 18:38:38",
    "RAW_UPDATED_AT": "2025-12-28 18:38:38",
    "UPDATED_BY": 1
  },
  {
    "ID": 2,
    "GROUPID": 2,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيت زيتون خضير مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "زيت زيتون خضير مفرق",
    "DIVISIONID": 33,
    "DIVISIONNAME": "زيوت مفرق",
    "SORTING": 2,
    "itemsCount": 9,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:24:36",
    "RAW_UPDATED_AT": "2025-12-28 17:08:49",
    "UPDATED_BY": 1
  },
  {
    "ID": 42,
    "GROUPID": 42,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيت زيتون فرجين جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "زيت زيتون فرجين جملة",
    "DIVISIONID": 35,
    "DIVISIONNAME": "زيوت جملة",
    "SORTING": 42,
    "itemsCount": 9,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 18:52:11",
    "RAW_UPDATED_AT": "2025-12-28 18:52:11",
    "UPDATED_BY": 1
  },
  {
    "ID": 3,
    "GROUPID": 3,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيت زيتون فرجين مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "زيت زيتون فرجين مفرق",
    "DIVISIONID": 33,
    "DIVISIONNAME": "زيوت مفرق",
    "SORTING": 3,
    "itemsCount": 11,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:24:48",
    "RAW_UPDATED_AT": "2025-12-28 17:57:08",
    "UPDATED_BY": 1
  },
  {
    "ID": 41,
    "GROUPID": 41,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيت زيتون كورة جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "زيت زيتون كورة جملة",
    "DIVISIONID": 35,
    "DIVISIONNAME": "زيوت جملة",
    "SORTING": 41,
    "itemsCount": 7,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 18:48:12",
    "RAW_UPDATED_AT": "2025-12-28 18:48:12",
    "UPDATED_BY": 1
  },
  {
    "ID": 53,
    "GROUPID": 51,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيتون اخضر جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "زيتون اخضر جملة",
    "DIVISIONID": 18,
    "DIVISIONNAME": "زيتون جملة",
    "SORTING": 51,
    "itemsCount": 25,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 20:38:11",
    "RAW_UPDATED_AT": "2025-12-28 20:38:11",
    "UPDATED_BY": 1
  },
  {
    "ID": 7,
    "GROUPID": 7,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيتون اخضر مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "زيتون اخضر مفرق",
    "DIVISIONID": 7,
    "DIVISIONNAME": "زيتون مفرق",
    "SORTING": 7,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:26:01",
    "RAW_UPDATED_AT": "2025-12-28 20:34:12",
    "UPDATED_BY": 1
  },
  {
    "ID": 52,
    "GROUPID": 50,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيتون اسود جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "زيتون اسود جملة",
    "DIVISIONID": 18,
    "DIVISIONNAME": "زيتون جملة",
    "SORTING": 50,
    "itemsCount": 14,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 20:34:42",
    "RAW_UPDATED_AT": "2025-12-28 20:37:03",
    "UPDATED_BY": 1
  },
  {
    "ID": 44,
    "GROUPID": 44,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيتون اسود مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "زيتون اسود مفرق",
    "DIVISIONID": 7,
    "DIVISIONNAME": "زيتون مفرق",
    "SORTING": 44,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 19:22:22",
    "RAW_UPDATED_AT": "2025-12-28 20:37:28",
    "UPDATED_BY": 1
  },
  {
    "ID": 18,
    "GROUPID": 18,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "زيتون جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "زيتون جملة",
    "DIVISIONID": 18,
    "DIVISIONNAME": "زيتون جملة",
    "SORTING": 18,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:27:39",
    "RAW_UPDATED_AT": "2025-12-08 13:27:39",
    "UPDATED_BY": 2
  },
  {
    "ID": 59,
    "GROUPID": 57,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "عروض",
    "AGROUPNAME": null,
    "OTHERDESC": "عروض",
    "DIVISIONID": 38,
    "DIVISIONNAME": "عروض",
    "SORTING": 57,
    "itemsCount": 12,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "02 Jan 2026",
    "UPDATED_AT": "02 Jan 2026",
    "RAW_CREATED_AT": "2026-01-02 08:24:46",
    "RAW_UPDATED_AT": "2026-01-02 09:51:21",
    "UPDATED_BY": 1
  },
  {
    "ID": 20,
    "GROUPID": 20,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "عسل جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "عسل جملة",
    "DIVISIONID": 20,
    "DIVISIONNAME": "عسل جملة",
    "SORTING": 20,
    "itemsCount": 24,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:27:59",
    "RAW_UPDATED_AT": "2025-12-08 13:27:59",
    "UPDATED_BY": 2
  },
  {
    "ID": 10,
    "GROUPID": 10,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "عسل مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "عسل مفرق",
    "DIVISIONID": 10,
    "DIVISIONNAME": "عسل مفرق",
    "SORTING": 10,
    "itemsCount": 24,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:26:39",
    "RAW_UPDATED_AT": "2025-12-08 11:26:39",
    "UPDATED_BY": 2
  },
  {
    "ID": 25,
    "GROUPID": 25,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "علبة بهارات",
    "AGROUPNAME": null,
    "OTHERDESC": "علبة بهارات",
    "DIVISIONID": 24,
    "DIVISIONNAME": "بهارات مفرق",
    "SORTING": 25,
    "itemsCount": 22,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 14:39:13",
    "RAW_UPDATED_AT": "2025-12-28 20:09:36",
    "UPDATED_BY": 1
  },
  {
    "ID": 32,
    "GROUPID": 32,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "علبة صغيرة",
    "AGROUPNAME": null,
    "OTHERDESC": "علبة صغيرة",
    "DIVISIONID": 30,
    "DIVISIONNAME": "مجففات",
    "SORTING": 32,
    "itemsCount": 17,
    "ECOM_PIC": null,
    "MASTER_ITEM": -1,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "12 Dec 2025",
    "UPDATED_AT": "12 Dec 2025",
    "RAW_CREATED_AT": "2025-12-12 20:45:55",
    "RAW_UPDATED_AT": "2025-12-12 20:45:55",
    "UPDATED_BY": 1
  },
  {
    "ID": 34,
    "GROUPID": 34,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "علبة صغيرة.",
    "AGROUPNAME": null,
    "OTHERDESC": "علبة صغيرة.",
    "DIVISIONID": 31,
    "DIVISIONNAME": "مقرمشات",
    "SORTING": 34,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": -1,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "12 Dec 2025",
    "UPDATED_AT": "12 Dec 2025",
    "RAW_CREATED_AT": "2025-12-12 20:47:33",
    "RAW_UPDATED_AT": "2025-12-12 20:47:33",
    "UPDATED_BY": 1
  },
  {
    "ID": 31,
    "GROUPID": 31,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "علبة كبيرة",
    "AGROUPNAME": null,
    "OTHERDESC": "علبة كبيرة",
    "DIVISIONID": 30,
    "DIVISIONNAME": "مجففات",
    "SORTING": 31,
    "itemsCount": 13,
    "ECOM_PIC": null,
    "MASTER_ITEM": -1,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "12 Dec 2025",
    "UPDATED_AT": "12 Dec 2025",
    "RAW_CREATED_AT": "2025-12-12 20:45:22",
    "RAW_UPDATED_AT": "2025-12-12 20:45:22",
    "UPDATED_BY": 1
  },
  {
    "ID": 33,
    "GROUPID": 33,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "علبة كبيرة.",
    "AGROUPNAME": null,
    "OTHERDESC": "علبة كبيرة.",
    "DIVISIONID": 31,
    "DIVISIONNAME": "مقرمشات",
    "SORTING": 33,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": -1,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "12 Dec 2025",
    "UPDATED_AT": "12 Dec 2025",
    "RAW_CREATED_AT": "2025-12-12 20:47:06",
    "RAW_UPDATED_AT": "2025-12-12 20:47:06",
    "UPDATED_BY": 1
  },
  {
    "ID": 22,
    "GROUPID": 22,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "فواكه مجففه جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "فواكه مجففه جملة",
    "DIVISIONID": 22,
    "DIVISIONNAME": "فواكه مجففه جملة",
    "SORTING": 22,
    "itemsCount": 11,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:28:20",
    "RAW_UPDATED_AT": "2025-12-08 13:28:20",
    "UPDATED_BY": 2
  },
  {
    "ID": 11,
    "GROUPID": 11,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "فواكه مجففه مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "فواكه مجففه مفرق",
    "DIVISIONID": 11,
    "DIVISIONNAME": "فواكه مجففه مفرق",
    "SORTING": 11,
    "itemsCount": 11,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:26:51",
    "RAW_UPDATED_AT": "2025-12-08 11:26:51",
    "UPDATED_BY": 2
  },
  {
    "ID": 38,
    "GROUPID": 38,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "قلوبات مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "قلوبات مفرق",
    "DIVISIONID": 34,
    "DIVISIONNAME": "محمصة مفرق",
    "SORTING": 38,
    "itemsCount": 9,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "29 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 18:03:45",
    "RAW_UPDATED_AT": "2025-12-29 13:50:30",
    "UPDATED_BY": 1
  },
  {
    "ID": 57,
    "GROUPID": 55,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "قلوبات ني",
    "AGROUPNAME": null,
    "OTHERDESC": "قلوبات ني",
    "DIVISIONID": 34,
    "DIVISIONNAME": "محمصة مفرق",
    "SORTING": 55,
    "itemsCount": 10,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "29 Dec 2025",
    "UPDATED_AT": "29 Dec 2025",
    "RAW_CREATED_AT": "2025-12-29 14:51:42",
    "RAW_UPDATED_AT": "2025-12-29 14:51:42",
    "UPDATED_BY": 1
  },
  {
    "ID": 19,
    "GROUPID": 19,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "كبيس ومخللات جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "كبيس ومخللات جملة",
    "DIVISIONID": 19,
    "DIVISIONNAME": "كبيس ومخللات جملة",
    "SORTING": 19,
    "itemsCount": 25,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:27:49",
    "RAW_UPDATED_AT": "2025-12-08 13:27:49",
    "UPDATED_BY": 2
  },
  {
    "ID": 8,
    "GROUPID": 8,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "كبيس ومخللات مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "كبيس ومخللات مفرق",
    "DIVISIONID": 8,
    "DIVISIONNAME": "كبيس ومخللات مفرق",
    "SORTING": 8,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:26:13",
    "RAW_UPDATED_AT": "2025-12-08 11:26:13",
    "UPDATED_BY": 2
  },
  {
    "ID": 21,
    "GROUPID": 21,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "كيلو جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "كيلو جملة",
    "DIVISIONID": 21,
    "DIVISIONNAME": "كيلو جملة",
    "SORTING": 21,
    "itemsCount": 49,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "24 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:28:08",
    "RAW_UPDATED_AT": "2025-12-24 11:06:26",
    "UPDATED_BY": 1
  },
  {
    "ID": 68,
    "GROUPID": 66,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "كيلو مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "كيلو مفرق",
    "DIVISIONID": 39,
    "DIVISIONNAME": "كيلو مفرق",
    "SORTING": 66,
    "itemsCount": 67,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "02 Apr 2026",
    "UPDATED_AT": "02 Apr 2026",
    "RAW_CREATED_AT": "2026-04-02 10:26:13",
    "RAW_UPDATED_AT": "2026-04-02 10:28:22",
    "UPDATED_BY": 1
  },
  {
    "ID": 50,
    "GROUPID": 48,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مدبسات جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "مدبسات جملة",
    "DIVISIONID": 16,
    "DIVISIONNAME": "مقطرات ومدبسات جملة",
    "SORTING": 48,
    "itemsCount": 26,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 20:17:29",
    "RAW_UPDATED_AT": "2025-12-28 20:17:29",
    "UPDATED_BY": 1
  },
  {
    "ID": 43,
    "GROUPID": 43,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مدبسات مفرق 509",
    "AGROUPNAME": null,
    "OTHERDESC": "مدبسات مفرق 509",
    "DIVISIONID": 5,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق",
    "SORTING": 43,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2025-12-28 18:57:09",
    "RAW_UPDATED_AT": "2026-01-21 18:58:31",
    "UPDATED_BY": 1
  },
  {
    "ID": 64,
    "GROUPID": 62,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مدبسات مفرق 510",
    "AGROUPNAME": null,
    "OTHERDESC": "مدبسات مفرق 510",
    "DIVISIONID": 5,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق",
    "SORTING": 62,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "21 Jan 2026",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2026-01-21 17:47:49",
    "RAW_UPDATED_AT": "2026-01-21 18:59:17",
    "UPDATED_BY": 1
  },
  {
    "ID": 60,
    "GROUPID": 58,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مراطبين عروض",
    "AGROUPNAME": null,
    "OTHERDESC": "عرض 120",
    "DIVISIONID": 38,
    "DIVISIONNAME": "عروض",
    "SORTING": 58,
    "itemsCount": 34,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "02 Jan 2026",
    "UPDATED_AT": "02 Jan 2026",
    "RAW_CREATED_AT": "2026-01-02 09:47:39",
    "RAW_UPDATED_AT": "2026-01-02 09:50:31",
    "UPDATED_BY": 1
  },
  {
    "ID": 23,
    "GROUPID": 23,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مربيات جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "مربيات جملة",
    "DIVISIONID": 23,
    "DIVISIONNAME": "مربيات جملة",
    "SORTING": 23,
    "itemsCount": 39,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:28:32",
    "RAW_UPDATED_AT": "2025-12-08 13:28:32",
    "UPDATED_BY": 2
  },
  {
    "ID": 9,
    "GROUPID": 9,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مربيات مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "مربيات مفرق",
    "DIVISIONID": 9,
    "DIVISIONNAME": "مربيات مفرق",
    "SORTING": 9,
    "itemsCount": 39,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 11:26:26",
    "RAW_UPDATED_AT": "2025-12-08 11:26:26",
    "UPDATED_BY": 2
  },
  {
    "ID": 28,
    "GROUPID": 28,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مرتديلا",
    "AGROUPNAME": null,
    "OTHERDESC": "مرتديلا",
    "DIVISIONID": 27,
    "DIVISIONNAME": "براد",
    "SORTING": 28,
    "itemsCount": 15,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "10 Dec 2025",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2025-12-10 19:48:50",
    "RAW_UPDATED_AT": "2026-01-21 16:00:19",
    "UPDATED_BY": 1
  },
  {
    "ID": 24,
    "GROUPID": 24,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مرشة بهار",
    "AGROUPNAME": null,
    "OTHERDESC": "مرشة بهار",
    "DIVISIONID": 24,
    "DIVISIONNAME": "بهارات مفرق",
    "SORTING": 24,
    "itemsCount": 49,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 14:38:54",
    "RAW_UPDATED_AT": "2025-12-28 20:10:04",
    "UPDATED_BY": 1
  },
  {
    "ID": 70,
    "GROUPID": 68,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مرطبان 507",
    "AGROUPNAME": null,
    "OTHERDESC": "مرطبان 507",
    "DIVISIONID": 40,
    "DIVISIONNAME": "مرطبان",
    "SORTING": 68,
    "itemsCount": 23,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "02 Jul 2026",
    "UPDATED_AT": "02 Jul 2026",
    "RAW_CREATED_AT": "2026-07-02 14:08:41",
    "RAW_UPDATED_AT": "2026-07-02 14:08:41",
    "UPDATED_BY": 1
  },
  {
    "ID": 69,
    "GROUPID": 67,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مرطبان 510",
    "AGROUPNAME": null,
    "OTHERDESC": "مرطبان 510",
    "DIVISIONID": 40,
    "DIVISIONNAME": "مرطبان",
    "SORTING": 67,
    "itemsCount": 64,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "02 Jul 2026",
    "UPDATED_AT": "02 Jul 2026",
    "RAW_CREATED_AT": "2026-07-02 14:08:10",
    "RAW_UPDATED_AT": "2026-07-02 14:08:10",
    "UPDATED_BY": 1
  },
  {
    "ID": 48,
    "GROUPID": 46,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "معلبات أخرى",
    "AGROUPNAME": null,
    "OTHERDESC": "معلبات أخرى",
    "DIVISIONID": 6,
    "DIVISIONNAME": "مونة بلدية مفرق",
    "SORTING": 46,
    "itemsCount": 23,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 20:02:46",
    "RAW_UPDATED_AT": "2025-12-28 20:08:07",
    "UPDATED_BY": 1
  },
  {
    "ID": 65,
    "GROUPID": 63,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مقطرات 1 ليتر",
    "AGROUPNAME": null,
    "OTHERDESC": "مقطرات 1 ليتر",
    "DIVISIONID": 5,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق",
    "SORTING": 63,
    "itemsCount": 5,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "21 Jan 2026",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2026-01-21 17:51:20",
    "RAW_UPDATED_AT": "2026-01-21 17:51:20",
    "UPDATED_BY": 1
  },
  {
    "ID": 49,
    "GROUPID": 47,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مقطرات جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "مقطرات جملة",
    "DIVISIONID": 16,
    "DIVISIONNAME": "مقطرات ومدبسات جملة",
    "SORTING": 47,
    "itemsCount": 30,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 20:16:52",
    "RAW_UPDATED_AT": "2025-12-28 20:16:52",
    "UPDATED_BY": 1
  },
  {
    "ID": 5,
    "GROUPID": 5,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مقطرات مفرق 250مل",
    "AGROUPNAME": null,
    "OTHERDESC": "مقطرات مفرق 250مل",
    "DIVISIONID": 5,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق",
    "SORTING": 5,
    "itemsCount": 9,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2025-12-08 11:25:26",
    "RAW_UPDATED_AT": "2026-01-21 17:46:18",
    "UPDATED_BY": 1
  },
  {
    "ID": 63,
    "GROUPID": 61,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مقطرات مفرق 500مل",
    "AGROUPNAME": null,
    "OTHERDESC": "مقطرات مفرق 500مل",
    "DIVISIONID": 5,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق",
    "SORTING": 61,
    "itemsCount": 10,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "21 Jan 2026",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2026-01-21 17:46:42",
    "RAW_UPDATED_AT": "2026-01-21 17:46:42",
    "UPDATED_BY": 1
  },
  {
    "ID": 62,
    "GROUPID": 60,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مقطرات ومدبسات غالون",
    "AGROUPNAME": null,
    "OTHERDESC": "مقطرات ومدبسات غالون",
    "DIVISIONID": 5,
    "DIVISIONNAME": "مقطرات ومدبسات مفرق",
    "SORTING": 60,
    "itemsCount": 7,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "21 Jan 2026",
    "UPDATED_AT": "21 Jan 2026",
    "RAW_CREATED_AT": "2026-01-21 17:31:58",
    "RAW_UPDATED_AT": "2026-01-21 17:31:58",
    "UPDATED_BY": 1
  },
  {
    "ID": 54,
    "GROUPID": 52,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مكعزلة بقر جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "مكعزلة بقر جملة",
    "DIVISIONID": 37,
    "DIVISIONNAME": "مكعزلة جملة",
    "SORTING": 52,
    "itemsCount": 13,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 21:33:34",
    "RAW_UPDATED_AT": "2025-12-28 21:33:34",
    "UPDATED_BY": 1
  },
  {
    "ID": 39,
    "GROUPID": 39,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مكعزلة بقر مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "مكعزلة بقر مفرق",
    "DIVISIONID": 36,
    "DIVISIONNAME": "مكعزلة مفرق",
    "SORTING": 39,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "28 Dec 2025",
    "RAW_CREATED_AT": "2025-12-28 18:18:08",
    "RAW_UPDATED_AT": "2025-12-28 21:30:12",
    "UPDATED_BY": 1
  },
  {
    "ID": 55,
    "GROUPID": 53,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مكعزلة معزة جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "مكعزلة معزة جملة",
    "DIVISIONID": 37,
    "DIVISIONNAME": "مكعزلة جملة",
    "SORTING": 53,
    "itemsCount": 12,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "24 Feb 2026",
    "RAW_CREATED_AT": "2025-12-28 21:35:45",
    "RAW_UPDATED_AT": "2026-02-24 12:39:18",
    "UPDATED_BY": 1
  },
  {
    "ID": 45,
    "GROUPID": 45,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مكعزلة معزة مفرق",
    "AGROUPNAME": null,
    "OTHERDESC": "مكعزلة معزة مفرق",
    "DIVISIONID": 36,
    "DIVISIONNAME": "مكعزلة مفرق",
    "SORTING": 45,
    "itemsCount": 0,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "28 Dec 2025",
    "UPDATED_AT": "24 Feb 2026",
    "RAW_CREATED_AT": "2025-12-28 19:53:41",
    "RAW_UPDATED_AT": "2026-02-24 12:40:18",
    "UPDATED_BY": 1
  },
  {
    "ID": 17,
    "GROUPID": 17,
    "BRAND_ID": 9606,
    "BRANCHID": 1,
    "GROUPNAME": "مونة بلدية جملة",
    "AGROUPNAME": null,
    "OTHERDESC": "مونة بلدية جملة",
    "DIVISIONID": 17,
    "DIVISIONNAME": "مونة بلدية جملة",
    "SORTING": 17,
    "itemsCount": 38,
    "ECOM_PIC": null,
    "MASTER_ITEM": 0,
    "TAX1": true,
    "TAX2": false,
    "TAX3": false,
    "TAX4": false,
    "TAX5": false,
    "TAX6": false,
    "ASSETACCOUNT": 0,
    "REVENUEACCOUNT": 0,
    "EXPENSEACCOUNT": 0,
    "STOCKVARIATIONACC": 0,
    "AUTDISC": 0,
    "CREATED_AT": "08 Dec 2025",
    "UPDATED_AT": "08 Dec 2025",
    "RAW_CREATED_AT": "2025-12-08 13:27:30",
    "RAW_UPDATED_AT": "2025-12-08 13:27:30",
    "UPDATED_BY": 2
  }
];
